// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_support.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminPeekChatTraceForAudit = `-- name: AdminPeekChatTraceForAudit :one
SELECT
    id,
    session_id,
    user_message_id,
    assistant_message_id,
    planner_model,
    answer_model,
    planner_prompt_version,
    answer_prompt_version,
    status
FROM chat_traces
WHERE id = $1 AND seller_account_id = $2
`

type AdminPeekChatTraceForAuditParams struct {
	ID              int64
	SellerAccountID int64
}

type AdminPeekChatTraceForAuditRow struct {
	ID                   int64
	SessionID            int64
	UserMessageID        pgtype.Int8
	AssistantMessageID   pgtype.Int8
	PlannerModel         string
	AnswerModel          string
	PlannerPromptVersion string
	AnswerPromptVersion  string
	Status               string
}

func (q *Queries) AdminPeekChatTraceForAudit(ctx context.Context, arg AdminPeekChatTraceForAuditParams) (AdminPeekChatTraceForAuditRow, error) {
	row := q.db.QueryRow(ctx, adminPeekChatTraceForAudit, arg.ID, arg.SellerAccountID)
	var i AdminPeekChatTraceForAuditRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.PlannerModel,
		&i.AnswerModel,
		&i.PlannerPromptVersion,
		&i.AnswerPromptVersion,
		&i.Status,
	)
	return i, err
}

const adminPeekRecommendationForAudit = `-- name: AdminPeekRecommendationForAudit :one
SELECT
    id,
    COALESCE(ai_model, '') AS ai_model,
    COALESCE(ai_prompt_version, '') AS ai_prompt_version
FROM recommendations
WHERE id = $1 AND seller_account_id = $2
`

type AdminPeekRecommendationForAuditParams struct {
	ID              int64
	SellerAccountID int64
}

type AdminPeekRecommendationForAuditRow struct {
	ID              int64
	AiModel         string
	AiPromptVersion string
}

func (q *Queries) AdminPeekRecommendationForAudit(ctx context.Context, arg AdminPeekRecommendationForAuditParams) (AdminPeekRecommendationForAuditRow, error) {
	row := q.db.QueryRow(ctx, adminPeekRecommendationForAudit, arg.ID, arg.SellerAccountID)
	var i AdminPeekRecommendationForAuditRow
	err := row.Scan(&i.ID, &i.AiModel, &i.AiPromptVersion)
	return i, err
}

const adminPeekRecommendationRunForAudit = `-- name: AdminPeekRecommendationRunForAudit :one
SELECT
    id,
    run_type,
    status,
    COALESCE(ai_model, '') AS ai_model,
    COALESCE(ai_prompt_version, '') AS ai_prompt_version
FROM recommendation_runs
WHERE id = $1 AND seller_account_id = $2
`

type AdminPeekRecommendationRunForAuditParams struct {
	ID              int64
	SellerAccountID int64
}

type AdminPeekRecommendationRunForAuditRow struct {
	ID              int64
	RunType         string
	Status          string
	AiModel         string
	AiPromptVersion string
}

func (q *Queries) AdminPeekRecommendationRunForAudit(ctx context.Context, arg AdminPeekRecommendationRunForAuditParams) (AdminPeekRecommendationRunForAuditRow, error) {
	row := q.db.QueryRow(ctx, adminPeekRecommendationRunForAudit, arg.ID, arg.SellerAccountID)
	var i AdminPeekRecommendationRunForAuditRow
	err := row.Scan(
		&i.ID,
		&i.RunType,
		&i.Status,
		&i.AiModel,
		&i.AiPromptVersion,
	)
	return i, err
}

const completeAdminActionLog = `-- name: CompleteAdminActionLog :one
UPDATE admin_action_logs
SET
    status = 'completed',
    result_payload = $2,
    error_message = NULL,
    finished_at = NOW()
WHERE id = $1
RETURNING id, admin_user_id, admin_email, seller_account_id, action_type, target_type, target_id, request_payload, result_payload, status, error_message, created_at, finished_at
`

type CompleteAdminActionLogParams struct {
	ID            int64
	ResultPayload []byte
}

func (q *Queries) CompleteAdminActionLog(ctx context.Context, arg CompleteAdminActionLogParams) (AdminActionLog, error) {
	row := q.db.QueryRow(ctx, completeAdminActionLog, arg.ID, arg.ResultPayload)
	var i AdminActionLog
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.AdminEmail,
		&i.SellerAccountID,
		&i.ActionType,
		&i.TargetType,
		&i.TargetID,
		&i.RequestPayload,
		&i.ResultPayload,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const countAdminActionLogsBySellerAccountID = `-- name: CountAdminActionLogsBySellerAccountID :one
SELECT COUNT(*)::bigint
FROM admin_action_logs
WHERE seller_account_id = $1
`

func (q *Queries) CountAdminActionLogsBySellerAccountID(ctx context.Context, sellerAccountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminActionLogsBySellerAccountID, sellerAccountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAdminActionLog = `-- name: CreateAdminActionLog :one
INSERT INTO admin_action_logs (
    admin_user_id,
    admin_email,
    seller_account_id,
    action_type,
    target_type,
    target_id,
    request_payload,
    status
) VALUES (
    $1::bigint,
    $2::text,
    $3::bigint,
    $4::text,
    $5::text,
    $6::bigint,
    $7::jsonb,
    COALESCE($8::text, 'running')
)
RETURNING id, admin_user_id, admin_email, seller_account_id, action_type, target_type, target_id, request_payload, result_payload, status, error_message, created_at, finished_at
`

type CreateAdminActionLogParams struct {
	AdminUserID     pgtype.Int8
	AdminEmail      string
	SellerAccountID int64
	ActionType      string
	TargetType      pgtype.Text
	TargetID        pgtype.Int8
	RequestPayload  []byte
	Status          pgtype.Text
}

func (q *Queries) CreateAdminActionLog(ctx context.Context, arg CreateAdminActionLogParams) (AdminActionLog, error) {
	row := q.db.QueryRow(ctx, createAdminActionLog,
		arg.AdminUserID,
		arg.AdminEmail,
		arg.SellerAccountID,
		arg.ActionType,
		arg.TargetType,
		arg.TargetID,
		arg.RequestPayload,
		arg.Status,
	)
	var i AdminActionLog
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.AdminEmail,
		&i.SellerAccountID,
		&i.ActionType,
		&i.TargetType,
		&i.TargetID,
		&i.RequestPayload,
		&i.ResultPayload,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createRecommendationRunDiagnostic = `-- name: CreateRecommendationRunDiagnostic :one
INSERT INTO recommendation_run_diagnostics (
    recommendation_run_id,
    seller_account_id,
    openai_request_id,
    ai_model,
    prompt_version,
    context_payload_summary,
    raw_openai_response,
    validation_result_payload,
    rejected_items_payload,
    error_stage,
    error_message,
    input_tokens,
    output_tokens,
    estimated_cost
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, recommendation_run_id, seller_account_id, openai_request_id, ai_model, prompt_version, context_payload_summary, raw_openai_response, validation_result_payload, rejected_items_payload, error_stage, error_message, input_tokens, output_tokens, estimated_cost, created_at
`

type CreateRecommendationRunDiagnosticParams struct {
	RecommendationRunID     pgtype.Int8
	SellerAccountID         int64
	OpenaiRequestID         pgtype.Text
	AiModel                 pgtype.Text
	PromptVersion           pgtype.Text
	ContextPayloadSummary   []byte
	RawOpenaiResponse       []byte
	ValidationResultPayload []byte
	RejectedItemsPayload    []byte
	ErrorStage              pgtype.Text
	ErrorMessage            pgtype.Text
	InputTokens             int64
	OutputTokens            int64
	EstimatedCost           pgtype.Numeric
}

func (q *Queries) CreateRecommendationRunDiagnostic(ctx context.Context, arg CreateRecommendationRunDiagnosticParams) (RecommendationRunDiagnostic, error) {
	row := q.db.QueryRow(ctx, createRecommendationRunDiagnostic,
		arg.RecommendationRunID,
		arg.SellerAccountID,
		arg.OpenaiRequestID,
		arg.AiModel,
		arg.PromptVersion,
		arg.ContextPayloadSummary,
		arg.RawOpenaiResponse,
		arg.ValidationResultPayload,
		arg.RejectedItemsPayload,
		arg.ErrorStage,
		arg.ErrorMessage,
		arg.InputTokens,
		arg.OutputTokens,
		arg.EstimatedCost,
	)
	var i RecommendationRunDiagnostic
	err := row.Scan(
		&i.ID,
		&i.RecommendationRunID,
		&i.SellerAccountID,
		&i.OpenaiRequestID,
		&i.AiModel,
		&i.PromptVersion,
		&i.ContextPayloadSummary,
		&i.RawOpenaiResponse,
		&i.ValidationResultPayload,
		&i.RejectedItemsPayload,
		&i.ErrorStage,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.EstimatedCost,
		&i.CreatedAt,
	)
	return i, err
}

const failAdminActionLog = `-- name: FailAdminActionLog :one
UPDATE admin_action_logs
SET
    status = 'failed',
    result_payload = $2,
    error_message = $3,
    finished_at = NOW()
WHERE id = $1
RETURNING id, admin_user_id, admin_email, seller_account_id, action_type, target_type, target_id, request_payload, result_payload, status, error_message, created_at, finished_at
`

type FailAdminActionLogParams struct {
	ID            int64
	ResultPayload []byte
	ErrorMessage  pgtype.Text
}

func (q *Queries) FailAdminActionLog(ctx context.Context, arg FailAdminActionLogParams) (AdminActionLog, error) {
	row := q.db.QueryRow(ctx, failAdminActionLog, arg.ID, arg.ResultPayload, arg.ErrorMessage)
	var i AdminActionLog
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.AdminEmail,
		&i.SellerAccountID,
		&i.ActionType,
		&i.TargetType,
		&i.TargetID,
		&i.RequestPayload,
		&i.ResultPayload,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getAdminActionLogByID = `-- name: GetAdminActionLogByID :one
SELECT id, admin_user_id, admin_email, seller_account_id, action_type, target_type, target_id, request_payload, result_payload, status, error_message, created_at, finished_at
FROM admin_action_logs
WHERE id = $1
`

func (q *Queries) GetAdminActionLogByID(ctx context.Context, id int64) (AdminActionLog, error) {
	row := q.db.QueryRow(ctx, getAdminActionLogByID, id)
	var i AdminActionLog
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.AdminEmail,
		&i.SellerAccountID,
		&i.ActionType,
		&i.TargetType,
		&i.TargetID,
		&i.RequestPayload,
		&i.ResultPayload,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRecommendationRunDiagnosticByID = `-- name: GetRecommendationRunDiagnosticByID :one
SELECT id, recommendation_run_id, seller_account_id, openai_request_id, ai_model, prompt_version, context_payload_summary, raw_openai_response, validation_result_payload, rejected_items_payload, error_stage, error_message, input_tokens, output_tokens, estimated_cost, created_at
FROM recommendation_run_diagnostics
WHERE seller_account_id = $1
  AND id = $2
`

type GetRecommendationRunDiagnosticByIDParams struct {
	SellerAccountID int64
	ID              int64
}

func (q *Queries) GetRecommendationRunDiagnosticByID(ctx context.Context, arg GetRecommendationRunDiagnosticByIDParams) (RecommendationRunDiagnostic, error) {
	row := q.db.QueryRow(ctx, getRecommendationRunDiagnosticByID, arg.SellerAccountID, arg.ID)
	var i RecommendationRunDiagnostic
	err := row.Scan(
		&i.ID,
		&i.RecommendationRunID,
		&i.SellerAccountID,
		&i.OpenaiRequestID,
		&i.AiModel,
		&i.PromptVersion,
		&i.ContextPayloadSummary,
		&i.RawOpenaiResponse,
		&i.ValidationResultPayload,
		&i.RejectedItemsPayload,
		&i.ErrorStage,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.EstimatedCost,
		&i.CreatedAt,
	)
	return i, err
}

const getSellerBillingState = `-- name: GetSellerBillingState :one
SELECT id, seller_account_id, plan_code, status, trial_ends_at, current_period_start, current_period_end, ai_tokens_limit_month, ai_tokens_used_month, estimated_ai_cost_month, notes, created_at, updated_at
FROM seller_billing_state
WHERE seller_account_id = $1
`

func (q *Queries) GetSellerBillingState(ctx context.Context, sellerAccountID int64) (SellerBillingState, error) {
	row := q.db.QueryRow(ctx, getSellerBillingState, sellerAccountID)
	var i SellerBillingState
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.PlanCode,
		&i.Status,
		&i.TrialEndsAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.AiTokensLimitMonth,
		&i.AiTokensUsedMonth,
		&i.EstimatedAiCostMonth,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminActionLogs = `-- name: ListAdminActionLogs :many
SELECT id, admin_user_id, admin_email, seller_account_id, action_type, target_type, target_id, request_payload, result_payload, status, error_message, created_at, finished_at
FROM admin_action_logs
WHERE (
    $1::bigint IS NULL
    OR seller_account_id = $1::bigint
)
  AND (
    $2::text IS NULL
    OR action_type = $2::text
)
  AND (
    $3::text IS NULL
    OR status = $3::text
)
ORDER BY created_at DESC, id DESC
LIMIT $5
OFFSET $4
`

type ListAdminActionLogsParams struct {
	SellerAccountID pgtype.Int8
	ActionType      pgtype.Text
	Status          pgtype.Text
	PageOffset      int32
	PageLimit       int32
}

func (q *Queries) ListAdminActionLogs(ctx context.Context, arg ListAdminActionLogsParams) ([]AdminActionLog, error) {
	rows, err := q.db.Query(ctx, listAdminActionLogs,
		arg.SellerAccountID,
		arg.ActionType,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminActionLog
	for rows.Next() {
		var i AdminActionLog
		if err := rows.Scan(
			&i.ID,
			&i.AdminUserID,
			&i.AdminEmail,
			&i.SellerAccountID,
			&i.ActionType,
			&i.TargetType,
			&i.TargetID,
			&i.RequestPayload,
			&i.ResultPayload,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationRunDiagnosticsByRun = `-- name: ListRecommendationRunDiagnosticsByRun :many
SELECT id, recommendation_run_id, seller_account_id, openai_request_id, ai_model, prompt_version, context_payload_summary, raw_openai_response, validation_result_payload, rejected_items_payload, error_stage, error_message, input_tokens, output_tokens, estimated_cost, created_at
FROM recommendation_run_diagnostics
WHERE seller_account_id = $1
  AND recommendation_run_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $4
`

type ListRecommendationRunDiagnosticsByRunParams struct {
	SellerAccountID     int64
	RecommendationRunID pgtype.Int8
	Limit               int32
	Offset              int32
}

func (q *Queries) ListRecommendationRunDiagnosticsByRun(ctx context.Context, arg ListRecommendationRunDiagnosticsByRunParams) ([]RecommendationRunDiagnostic, error) {
	rows, err := q.db.Query(ctx, listRecommendationRunDiagnosticsByRun,
		arg.SellerAccountID,
		arg.RecommendationRunID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecommendationRunDiagnostic
	for rows.Next() {
		var i RecommendationRunDiagnostic
		if err := rows.Scan(
			&i.ID,
			&i.RecommendationRunID,
			&i.SellerAccountID,
			&i.OpenaiRequestID,
			&i.AiModel,
			&i.PromptVersion,
			&i.ContextPayloadSummary,
			&i.RawOpenaiResponse,
			&i.ValidationResultPayload,
			&i.RejectedItemsPayload,
			&i.ErrorStage,
			&i.ErrorMessage,
			&i.InputTokens,
			&i.OutputTokens,
			&i.EstimatedCost,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationRunDiagnosticsBySeller = `-- name: ListRecommendationRunDiagnosticsBySeller :many
SELECT id, recommendation_run_id, seller_account_id, openai_request_id, ai_model, prompt_version, context_payload_summary, raw_openai_response, validation_result_payload, rejected_items_payload, error_stage, error_message, input_tokens, output_tokens, estimated_cost, created_at
FROM recommendation_run_diagnostics
WHERE seller_account_id = $1
  AND (
    $2::bigint IS NULL
    OR recommendation_run_id = $2::bigint
)
  AND (
    $3::text IS NULL
    OR error_stage = $3::text
)
ORDER BY created_at DESC, id DESC
LIMIT $5
OFFSET $4
`

type ListRecommendationRunDiagnosticsBySellerParams struct {
	SellerAccountID     int64
	RecommendationRunID pgtype.Int8
	ErrorStage          pgtype.Text
	PageOffset          int32
	PageLimit           int32
}

func (q *Queries) ListRecommendationRunDiagnosticsBySeller(ctx context.Context, arg ListRecommendationRunDiagnosticsBySellerParams) ([]RecommendationRunDiagnostic, error) {
	rows, err := q.db.Query(ctx, listRecommendationRunDiagnosticsBySeller,
		arg.SellerAccountID,
		arg.RecommendationRunID,
		arg.ErrorStage,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecommendationRunDiagnostic
	for rows.Next() {
		var i RecommendationRunDiagnostic
		if err := rows.Scan(
			&i.ID,
			&i.RecommendationRunID,
			&i.SellerAccountID,
			&i.OpenaiRequestID,
			&i.AiModel,
			&i.PromptVersion,
			&i.ContextPayloadSummary,
			&i.RawOpenaiResponse,
			&i.ValidationResultPayload,
			&i.RejectedItemsPayload,
			&i.ErrorStage,
			&i.ErrorMessage,
			&i.InputTokens,
			&i.OutputTokens,
			&i.EstimatedCost,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellerBillingStates = `-- name: ListSellerBillingStates :many
SELECT id, seller_account_id, plan_code, status, trial_ends_at, current_period_start, current_period_end, ai_tokens_limit_month, ai_tokens_used_month, estimated_ai_cost_month, notes, created_at, updated_at
FROM seller_billing_state
WHERE (
    $1::text IS NULL
    OR status = $1::text
)
ORDER BY updated_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListSellerBillingStatesParams struct {
	Status     pgtype.Text
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListSellerBillingStates(ctx context.Context, arg ListSellerBillingStatesParams) ([]SellerBillingState, error) {
	rows, err := q.db.Query(ctx, listSellerBillingStates, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellerBillingState
	for rows.Next() {
		var i SellerBillingState
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.PlanCode,
			&i.Status,
			&i.TrialEndsAt,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.AiTokensLimitMonth,
			&i.AiTokensUsedMonth,
			&i.EstimatedAiCostMonth,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSellerBillingState = `-- name: UpsertSellerBillingState :one
INSERT INTO seller_billing_state (
    seller_account_id,
    plan_code,
    status,
    trial_ends_at,
    current_period_start,
    current_period_end,
    ai_tokens_limit_month,
    ai_tokens_used_month,
    estimated_ai_cost_month,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (seller_account_id)
DO UPDATE SET
    plan_code = EXCLUDED.plan_code,
    status = EXCLUDED.status,
    trial_ends_at = EXCLUDED.trial_ends_at,
    current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end,
    ai_tokens_limit_month = EXCLUDED.ai_tokens_limit_month,
    ai_tokens_used_month = EXCLUDED.ai_tokens_used_month,
    estimated_ai_cost_month = EXCLUDED.estimated_ai_cost_month,
    notes = EXCLUDED.notes,
    updated_at = NOW()
RETURNING id, seller_account_id, plan_code, status, trial_ends_at, current_period_start, current_period_end, ai_tokens_limit_month, ai_tokens_used_month, estimated_ai_cost_month, notes, created_at, updated_at
`

type UpsertSellerBillingStateParams struct {
	SellerAccountID      int64
	PlanCode             string
	Status               string
	TrialEndsAt          pgtype.Timestamptz
	CurrentPeriodStart   pgtype.Timestamptz
	CurrentPeriodEnd     pgtype.Timestamptz
	AiTokensLimitMonth   pgtype.Int8
	AiTokensUsedMonth    int64
	EstimatedAiCostMonth pgtype.Numeric
	Notes                pgtype.Text
}

func (q *Queries) UpsertSellerBillingState(ctx context.Context, arg UpsertSellerBillingStateParams) (SellerBillingState, error) {
	row := q.db.QueryRow(ctx, upsertSellerBillingState,
		arg.SellerAccountID,
		arg.PlanCode,
		arg.Status,
		arg.TrialEndsAt,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.AiTokensLimitMonth,
		arg.AiTokensUsedMonth,
		arg.EstimatedAiCostMonth,
		arg.Notes,
	)
	var i SellerBillingState
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.PlanCode,
		&i.Status,
		&i.TrialEndsAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.AiTokensLimitMonth,
		&i.AiTokensUsedMonth,
		&i.EstimatedAiCostMonth,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
