// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_read.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminGetChatSessionByID = `-- name: AdminGetChatSessionByID :one
SELECT
    id,
    seller_account_id,
    title,
    status,
    created_at,
    updated_at,
    last_message_at
FROM chat_sessions
WHERE seller_account_id = $1
  AND id = $2
`

type AdminGetChatSessionByIDParams struct {
	SellerAccountID int64
	ID              int64
}

type AdminGetChatSessionByIDRow struct {
	ID              int64
	SellerAccountID int64
	Title           string
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	LastMessageAt   pgtype.Timestamptz
}

func (q *Queries) AdminGetChatSessionByID(ctx context.Context, arg AdminGetChatSessionByIDParams) (AdminGetChatSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, adminGetChatSessionByID, arg.SellerAccountID, arg.ID)
	var i AdminGetChatSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const adminGetClientOverview = `-- name: AdminGetClientOverview :one
SELECT
    sa.id AS seller_account_id,
    sa.name AS seller_name,
    sa.status AS seller_status,
    sa.user_id AS owner_user_id,
    u.email AS owner_email,
    sa.created_at,
    sa.updated_at
FROM seller_accounts sa
JOIN users u ON u.id = sa.user_id
WHERE sa.id = $1
`

type AdminGetClientOverviewRow struct {
	SellerAccountID int64
	SellerName      string
	SellerStatus    string
	OwnerUserID     int64
	OwnerEmail      string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) AdminGetClientOverview(ctx context.Context, id int64) (AdminGetClientOverviewRow, error) {
	row := q.db.QueryRow(ctx, adminGetClientOverview, id)
	var i AdminGetClientOverviewRow
	err := row.Scan(
		&i.SellerAccountID,
		&i.SellerName,
		&i.SellerStatus,
		&i.OwnerUserID,
		&i.OwnerEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetRecommendationProxyFeedbackCounts = `-- name: AdminGetRecommendationProxyFeedbackCounts :one
SELECT
    COUNT(*) FILTER (WHERE status = 'accepted')::bigint AS accepted_count,
    COUNT(*) FILTER (WHERE status = 'dismissed')::bigint AS dismissed_count,
    COUNT(*) FILTER (WHERE status = 'resolved')::bigint AS resolved_count
FROM recommendations
WHERE seller_account_id = $1
`

type AdminGetRecommendationProxyFeedbackCountsRow struct {
	AcceptedCount  int64
	DismissedCount int64
	ResolvedCount  int64
}

func (q *Queries) AdminGetRecommendationProxyFeedbackCounts(ctx context.Context, sellerAccountID int64) (AdminGetRecommendationProxyFeedbackCountsRow, error) {
	row := q.db.QueryRow(ctx, adminGetRecommendationProxyFeedbackCounts, sellerAccountID)
	var i AdminGetRecommendationProxyFeedbackCountsRow
	err := row.Scan(&i.AcceptedCount, &i.DismissedCount, &i.ResolvedCount)
	return i, err
}

const adminGetRecommendationRunByID = `-- name: AdminGetRecommendationRunByID :one
SELECT
    id,
    seller_account_id,
    run_type,
    status,
    as_of_date,
    ai_model,
    ai_prompt_version,
    input_tokens,
    output_tokens,
    estimated_cost,
    generated_recommendations_count,
    accepted_recommendations_count,
    error_message,
    started_at,
    finished_at,
    created_at
FROM recommendation_runs
WHERE seller_account_id = $1
  AND id = $2
`

type AdminGetRecommendationRunByIDParams struct {
	SellerAccountID int64
	ID              int64
}

func (q *Queries) AdminGetRecommendationRunByID(ctx context.Context, arg AdminGetRecommendationRunByIDParams) (RecommendationRun, error) {
	row := q.db.QueryRow(ctx, adminGetRecommendationRunByID, arg.SellerAccountID, arg.ID)
	var i RecommendationRun
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.RunType,
		&i.Status,
		&i.AsOfDate,
		&i.AiModel,
		&i.AiPromptVersion,
		&i.InputTokens,
		&i.OutputTokens,
		&i.EstimatedCost,
		&i.GeneratedRecommendationsCount,
		&i.AcceptedRecommendationsCount,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const adminListChatFeedback = `-- name: AdminListChatFeedback :many
SELECT
    cf.id,
    cf.seller_account_id,
    sa.name AS seller_name,
    cf.session_id,
    cf.message_id,
    cf.rating,
    cf.comment,
    cf.created_at,
    cm.role AS message_role,
    cm.message_type,
    cm.content AS message_content,
    cs.title AS session_title,
    ct.id AS trace_id
FROM chat_feedback cf
JOIN chat_messages cm ON cm.id = cf.message_id AND cm.seller_account_id = cf.seller_account_id
JOIN chat_sessions cs ON cs.id = cf.session_id AND cs.seller_account_id = cf.seller_account_id
JOIN seller_accounts sa ON sa.id = cf.seller_account_id
LEFT JOIN chat_traces ct ON ct.seller_account_id = cf.seller_account_id AND ct.assistant_message_id = cf.message_id
WHERE (
    $1::bigint IS NULL
    OR cf.seller_account_id = $1::bigint
)
  AND (
    $2::text IS NULL
    OR cf.rating = $2::text
)
ORDER BY cf.created_at DESC, cf.id DESC
LIMIT $4
OFFSET $3
`

type AdminListChatFeedbackParams struct {
	SellerAccountID pgtype.Int8
	Rating          pgtype.Text
	PageOffset      int32
	PageLimit       int32
}

type AdminListChatFeedbackRow struct {
	ID              int64
	SellerAccountID int64
	SellerName      string
	SessionID       int64
	MessageID       int64
	Rating          string
	Comment         pgtype.Text
	CreatedAt       pgtype.Timestamptz
	MessageRole     string
	MessageType     string
	MessageContent  string
	SessionTitle    string
	TraceID         pgtype.Int8
}

func (q *Queries) AdminListChatFeedback(ctx context.Context, arg AdminListChatFeedbackParams) ([]AdminListChatFeedbackRow, error) {
	rows, err := q.db.Query(ctx, adminListChatFeedback,
		arg.SellerAccountID,
		arg.Rating,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListChatFeedbackRow
	for rows.Next() {
		var i AdminListChatFeedbackRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.SellerName,
			&i.SessionID,
			&i.MessageID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.MessageRole,
			&i.MessageType,
			&i.MessageContent,
			&i.SessionTitle,
			&i.TraceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListChatMessagesBySession = `-- name: AdminListChatMessagesBySession :many
SELECT
    id,
    session_id,
    seller_account_id,
    role,
    content,
    message_type,
    created_at
FROM chat_messages
WHERE seller_account_id = $1
  AND session_id = $2
ORDER BY created_at ASC, id ASC
LIMIT $4
OFFSET $3
`

type AdminListChatMessagesBySessionParams struct {
	SellerAccountID int64
	SessionID       int64
	PageOffset      int32
	PageLimit       int32
}

func (q *Queries) AdminListChatMessagesBySession(ctx context.Context, arg AdminListChatMessagesBySessionParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, adminListChatMessagesBySession,
		arg.SellerAccountID,
		arg.SessionID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SellerAccountID,
			&i.Role,
			&i.Content,
			&i.MessageType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListChatSessionsBySeller = `-- name: AdminListChatSessionsBySeller :many
SELECT
    id,
    seller_account_id,
    title,
    status,
    created_at,
    updated_at,
    last_message_at
FROM chat_sessions
WHERE seller_account_id = $1
  AND (
    $2::text IS NULL
    OR status = $2::text
)
ORDER BY last_message_at DESC NULLS LAST, updated_at DESC, id DESC
LIMIT $4
OFFSET $3
`

type AdminListChatSessionsBySellerParams struct {
	SellerAccountID int64
	Status          pgtype.Text
	PageOffset      int32
	PageLimit       int32
}

type AdminListChatSessionsBySellerRow struct {
	ID              int64
	SellerAccountID int64
	Title           string
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	LastMessageAt   pgtype.Timestamptz
}

func (q *Queries) AdminListChatSessionsBySeller(ctx context.Context, arg AdminListChatSessionsBySellerParams) ([]AdminListChatSessionsBySellerRow, error) {
	rows, err := q.db.Query(ctx, adminListChatSessionsBySeller,
		arg.SellerAccountID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListChatSessionsBySellerRow
	for rows.Next() {
		var i AdminListChatSessionsBySellerRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListChatTracesBySeller = `-- name: AdminListChatTracesBySeller :many
SELECT
    id,
    session_id,
    user_message_id,
    assistant_message_id,
    seller_account_id,
    planner_prompt_version,
    answer_prompt_version,
    planner_model,
    answer_model,
    detected_intent,
    tool_plan_payload,
    validated_tool_plan_payload,
    tool_results_payload,
    fact_context_payload,
    raw_planner_response,
    raw_answer_response,
    answer_validation_payload,
    input_tokens,
    output_tokens,
    estimated_cost,
    status,
    error_message,
    started_at,
    finished_at,
    created_at
FROM chat_traces
WHERE seller_account_id = $1
  AND (
    $2::text IS NULL
    OR status = $2::text
)
  AND (
    $3::text IS NULL
    OR detected_intent = $3::text
)
  AND (
    $4::bigint IS NULL
    OR session_id = $4::bigint
)
ORDER BY started_at DESC, created_at DESC, id DESC
LIMIT $6
OFFSET $5
`

type AdminListChatTracesBySellerParams struct {
	SellerAccountID int64
	Status          pgtype.Text
	DetectedIntent  pgtype.Text
	SessionID       pgtype.Int8
	PageOffset      int32
	PageLimit       int32
}

func (q *Queries) AdminListChatTracesBySeller(ctx context.Context, arg AdminListChatTracesBySellerParams) ([]ChatTrace, error) {
	rows, err := q.db.Query(ctx, adminListChatTracesBySeller,
		arg.SellerAccountID,
		arg.Status,
		arg.DetectedIntent,
		arg.SessionID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatTrace
	for rows.Next() {
		var i ChatTrace
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserMessageID,
			&i.AssistantMessageID,
			&i.SellerAccountID,
			&i.PlannerPromptVersion,
			&i.AnswerPromptVersion,
			&i.PlannerModel,
			&i.AnswerModel,
			&i.DetectedIntent,
			&i.ToolPlanPayload,
			&i.ValidatedToolPlanPayload,
			&i.ToolResultsPayload,
			&i.FactContextPayload,
			&i.RawPlannerResponse,
			&i.RawAnswerResponse,
			&i.AnswerValidationPayload,
			&i.InputTokens,
			&i.OutputTokens,
			&i.EstimatedCost,
			&i.Status,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListClientConnections = `-- name: AdminListClientConnections :many
SELECT
    'ozon'::text AS provider,
    oc.status AS connection_status,
    oc.last_check_at,
    oc.last_check_result,
    oc.last_error,
    oc.updated_at
FROM ozon_connections oc
WHERE oc.seller_account_id = $1
ORDER BY oc.updated_at DESC
`

type AdminListClientConnectionsRow struct {
	Provider         string
	ConnectionStatus string
	LastCheckAt      pgtype.Timestamptz
	LastCheckResult  pgtype.Text
	LastError        pgtype.Text
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) AdminListClientConnections(ctx context.Context, sellerAccountID int64) ([]AdminListClientConnectionsRow, error) {
	rows, err := q.db.Query(ctx, adminListClientConnections, sellerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListClientConnectionsRow
	for rows.Next() {
		var i AdminListClientConnectionsRow
		if err := rows.Scan(
			&i.Provider,
			&i.ConnectionStatus,
			&i.LastCheckAt,
			&i.LastCheckResult,
			&i.LastError,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListClients = `-- name: AdminListClients :many
SELECT
    sa.id AS seller_account_id,
    sa.name AS seller_name,
    sa.status AS seller_status,
    sa.created_at AS seller_created_at,
    sa.updated_at AS seller_updated_at,
    u.id AS owner_user_id,
    u.email AS owner_email,
    oc.status AS connection_status,
    oc.last_check_at AS connection_last_check_at,
    oc.last_error AS connection_last_error,
    sj.status AS latest_sync_status,
    sj.started_at AS latest_sync_started_at,
    sj.finished_at AS latest_sync_finished_at,
    COALESCE((
        SELECT COUNT(*)
        FROM alerts a
        WHERE a.seller_account_id = sa.id
          AND a.status = 'open'
    ), 0)::bigint AS open_alerts_count,
    COALESCE((
        SELECT COUNT(*)
        FROM recommendations r
        WHERE r.seller_account_id = sa.id
          AND r.status = 'open'
    ), 0)::bigint AS open_recommendations_count,
    rr.status AS latest_recommendation_run_status,
    ct.status AS latest_chat_trace_status,
    sbs.status AS billing_status
FROM seller_accounts sa
JOIN users u ON u.id = sa.user_id
LEFT JOIN ozon_connections oc ON oc.seller_account_id = sa.id
LEFT JOIN LATERAL (
    SELECT status, started_at, finished_at
    FROM sync_jobs
    WHERE seller_account_id = sa.id
    ORDER BY created_at DESC, id DESC
    LIMIT 1
) sj ON TRUE
LEFT JOIN LATERAL (
    SELECT status
    FROM recommendation_runs
    WHERE seller_account_id = sa.id
    ORDER BY started_at DESC, id DESC
    LIMIT 1
) rr ON TRUE
LEFT JOIN LATERAL (
    SELECT status
    FROM chat_traces
    WHERE seller_account_id = sa.id
    ORDER BY started_at DESC, id DESC
    LIMIT 1
) ct ON TRUE
LEFT JOIN seller_billing_state sbs ON sbs.seller_account_id = sa.id
WHERE (
    $1::text IS NULL
    OR sa.name ILIKE '%' || $1::text || '%'
    OR u.email ILIKE '%' || $1::text || '%'
)
  AND (
    $2::text IS NULL
    OR sa.status = $2::text
)
  AND (
    $3::text IS NULL
    OR oc.status = $3::text
)
  AND (
    $4::text IS NULL
    OR sbs.status = $4::text
)
ORDER BY sa.created_at DESC, sa.id DESC
LIMIT $6
OFFSET $5
`

type AdminListClientsParams struct {
	Search           pgtype.Text
	SellerStatus     pgtype.Text
	ConnectionStatus pgtype.Text
	BillingStatus    pgtype.Text
	PageOffset       int32
	PageLimit        int32
}

type AdminListClientsRow struct {
	SellerAccountID               int64
	SellerName                    string
	SellerStatus                  string
	SellerCreatedAt               pgtype.Timestamptz
	SellerUpdatedAt               pgtype.Timestamptz
	OwnerUserID                   int64
	OwnerEmail                    string
	ConnectionStatus              pgtype.Text
	ConnectionLastCheckAt         pgtype.Timestamptz
	ConnectionLastError           pgtype.Text
	LatestSyncStatus              string
	LatestSyncStartedAt           pgtype.Timestamptz
	LatestSyncFinishedAt          pgtype.Timestamptz
	OpenAlertsCount               int64
	OpenRecommendationsCount      int64
	LatestRecommendationRunStatus string
	LatestChatTraceStatus         string
	BillingStatus                 pgtype.Text
}

func (q *Queries) AdminListClients(ctx context.Context, arg AdminListClientsParams) ([]AdminListClientsRow, error) {
	rows, err := q.db.Query(ctx, adminListClients,
		arg.Search,
		arg.SellerStatus,
		arg.ConnectionStatus,
		arg.BillingStatus,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListClientsRow
	for rows.Next() {
		var i AdminListClientsRow
		if err := rows.Scan(
			&i.SellerAccountID,
			&i.SellerName,
			&i.SellerStatus,
			&i.SellerCreatedAt,
			&i.SellerUpdatedAt,
			&i.OwnerUserID,
			&i.OwnerEmail,
			&i.ConnectionStatus,
			&i.ConnectionLastCheckAt,
			&i.ConnectionLastError,
			&i.LatestSyncStatus,
			&i.LatestSyncStartedAt,
			&i.LatestSyncFinishedAt,
			&i.OpenAlertsCount,
			&i.OpenRecommendationsCount,
			&i.LatestRecommendationRunStatus,
			&i.LatestChatTraceStatus,
			&i.BillingStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListImportErrors = `-- name: AdminListImportErrors :many
SELECT
    id,
    seller_account_id,
    sync_job_id,
    domain,
    status,
    error_message,
    records_failed,
    started_at,
    finished_at,
    created_at
FROM import_jobs
WHERE seller_account_id = $1
  AND error_message IS NOT NULL
  AND error_message <> ''
  AND (
    $2::text IS NULL
    OR domain = $2::text
)
  AND (
    status = 'failed'
    OR $3::text IS NULL
    OR status = $3::text
)
ORDER BY created_at DESC, id DESC
LIMIT $5
OFFSET $4
`

type AdminListImportErrorsParams struct {
	SellerAccountID int64
	Domain          pgtype.Text
	Status          pgtype.Text
	PageOffset      int32
	PageLimit       int32
}

type AdminListImportErrorsRow struct {
	ID              int64
	SellerAccountID int64
	SyncJobID       int64
	Domain          string
	Status          string
	ErrorMessage    pgtype.Text
	RecordsFailed   int32
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) AdminListImportErrors(ctx context.Context, arg AdminListImportErrorsParams) ([]AdminListImportErrorsRow, error) {
	rows, err := q.db.Query(ctx, adminListImportErrors,
		arg.SellerAccountID,
		arg.Domain,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListImportErrorsRow
	for rows.Next() {
		var i AdminListImportErrorsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.SyncJobID,
			&i.Domain,
			&i.Status,
			&i.ErrorMessage,
			&i.RecordsFailed,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListImportJobs = `-- name: AdminListImportJobs :many
SELECT
    id,
    seller_account_id,
    sync_job_id,
    domain,
    status,
    source_cursor,
    records_received,
    records_imported,
    records_failed,
    started_at,
    finished_at,
    error_message,
    created_at
FROM import_jobs
WHERE seller_account_id = $1
  AND (
    $2::text IS NULL
    OR status = $2::text
)
  AND (
    $3::text IS NULL
    OR domain = $3::text
)
ORDER BY created_at DESC, id DESC
LIMIT $5
OFFSET $4
`

type AdminListImportJobsParams struct {
	SellerAccountID int64
	Status          pgtype.Text
	Domain          pgtype.Text
	PageOffset      int32
	PageLimit       int32
}

func (q *Queries) AdminListImportJobs(ctx context.Context, arg AdminListImportJobsParams) ([]ImportJob, error) {
	rows, err := q.db.Query(ctx, adminListImportJobs,
		arg.SellerAccountID,
		arg.Status,
		arg.Domain,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportJob
	for rows.Next() {
		var i ImportJob
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.SyncJobID,
			&i.Domain,
			&i.Status,
			&i.SourceCursor,
			&i.RecordsReceived,
			&i.RecordsImported,
			&i.RecordsFailed,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListRecommendationFeedbackBySeller = `-- name: AdminListRecommendationFeedbackBySeller :many
SELECT
    rf.id,
    rf.seller_account_id,
    rf.recommendation_id,
    rf.rating,
    rf.comment,
    rf.created_at AS feedback_created_at,
    r.recommendation_type,
    r.title,
    r.priority_level,
    r.confidence_level,
    r.status AS recommendation_status,
    r.entity_type,
    r.entity_id,
    r.entity_sku,
    r.entity_offer_id,
    r.created_at AS recommendation_created_at
FROM recommendation_feedback rf
JOIN recommendations r ON r.id = rf.recommendation_id AND r.seller_account_id = rf.seller_account_id
WHERE rf.seller_account_id = $1
  AND (
    $2::text IS NULL
    OR rf.rating = $2::text
)
  AND (
    $3::text IS NULL
    OR r.status = $3::text
)
ORDER BY rf.created_at DESC, rf.id DESC
LIMIT $5
OFFSET $4
`

type AdminListRecommendationFeedbackBySellerParams struct {
	SellerAccountID      int64
	Rating               pgtype.Text
	RecommendationStatus pgtype.Text
	PageOffset           int32
	PageLimit            int32
}

type AdminListRecommendationFeedbackBySellerRow struct {
	ID                      int64
	SellerAccountID         int64
	RecommendationID        int64
	Rating                  string
	Comment                 pgtype.Text
	FeedbackCreatedAt       pgtype.Timestamptz
	RecommendationType      string
	Title                   string
	PriorityLevel           string
	ConfidenceLevel         string
	RecommendationStatus    string
	EntityType              string
	EntityID                pgtype.Text
	EntitySku               pgtype.Int8
	EntityOfferID           pgtype.Text
	RecommendationCreatedAt pgtype.Timestamptz
}

func (q *Queries) AdminListRecommendationFeedbackBySeller(ctx context.Context, arg AdminListRecommendationFeedbackBySellerParams) ([]AdminListRecommendationFeedbackBySellerRow, error) {
	rows, err := q.db.Query(ctx, adminListRecommendationFeedbackBySeller,
		arg.SellerAccountID,
		arg.Rating,
		arg.RecommendationStatus,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListRecommendationFeedbackBySellerRow
	for rows.Next() {
		var i AdminListRecommendationFeedbackBySellerRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.RecommendationID,
			&i.Rating,
			&i.Comment,
			&i.FeedbackCreatedAt,
			&i.RecommendationType,
			&i.Title,
			&i.PriorityLevel,
			&i.ConfidenceLevel,
			&i.RecommendationStatus,
			&i.EntityType,
			&i.EntityID,
			&i.EntitySku,
			&i.EntityOfferID,
			&i.RecommendationCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListRecommendationRuns = `-- name: AdminListRecommendationRuns :many
SELECT
    id,
    seller_account_id,
    run_type,
    status,
    as_of_date,
    ai_model,
    ai_prompt_version,
    input_tokens,
    output_tokens,
    estimated_cost,
    generated_recommendations_count,
    accepted_recommendations_count,
    error_message,
    started_at,
    finished_at,
    created_at
FROM recommendation_runs
WHERE seller_account_id = $1
  AND (
    $2::text IS NULL
    OR status = $2::text
)
  AND (
    $3::text IS NULL
    OR run_type = $3::text
)
ORDER BY started_at DESC, created_at DESC, id DESC
LIMIT $5
OFFSET $4
`

type AdminListRecommendationRunsParams struct {
	SellerAccountID int64
	Status          pgtype.Text
	RunType         pgtype.Text
	PageOffset      int32
	PageLimit       int32
}

func (q *Queries) AdminListRecommendationRuns(ctx context.Context, arg AdminListRecommendationRunsParams) ([]RecommendationRun, error) {
	rows, err := q.db.Query(ctx, adminListRecommendationRuns,
		arg.SellerAccountID,
		arg.Status,
		arg.RunType,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecommendationRun
	for rows.Next() {
		var i RecommendationRun
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.RunType,
			&i.Status,
			&i.AsOfDate,
			&i.AiModel,
			&i.AiPromptVersion,
			&i.InputTokens,
			&i.OutputTokens,
			&i.EstimatedCost,
			&i.GeneratedRecommendationsCount,
			&i.AcceptedRecommendationsCount,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListSyncCursors = `-- name: AdminListSyncCursors :many
SELECT
    id,
    seller_account_id,
    domain,
    cursor_type,
    cursor_value,
    updated_at
FROM sync_cursors
WHERE seller_account_id = $1
  AND (
    $2::text IS NULL
    OR domain = $2::text
)
ORDER BY updated_at DESC, id DESC
LIMIT $4
OFFSET $3
`

type AdminListSyncCursorsParams struct {
	SellerAccountID int64
	Domain          pgtype.Text
	PageOffset      int32
	PageLimit       int32
}

func (q *Queries) AdminListSyncCursors(ctx context.Context, arg AdminListSyncCursorsParams) ([]SyncCursor, error) {
	rows, err := q.db.Query(ctx, adminListSyncCursors,
		arg.SellerAccountID,
		arg.Domain,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncCursor
	for rows.Next() {
		var i SyncCursor
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.Domain,
			&i.CursorType,
			&i.CursorValue,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListSyncJobs = `-- name: AdminListSyncJobs :many
SELECT
    id,
    seller_account_id,
    type,
    status,
    started_at,
    finished_at,
    error_message,
    created_at
FROM sync_jobs
WHERE seller_account_id = $1
  AND (
    $2::text IS NULL
    OR status = $2::text
)
ORDER BY created_at DESC, id DESC
LIMIT $4
OFFSET $3
`

type AdminListSyncJobsParams struct {
	SellerAccountID int64
	Status          pgtype.Text
	PageOffset      int32
	PageLimit       int32
}

func (q *Queries) AdminListSyncJobs(ctx context.Context, arg AdminListSyncJobsParams) ([]SyncJob, error) {
	rows, err := q.db.Query(ctx, adminListSyncJobs,
		arg.SellerAccountID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncJob
	for rows.Next() {
		var i SyncJob
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.Type,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
