// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: advertising.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAdCampaignSKUMappingsBySellerAccountID = `-- name: ListAdCampaignSKUMappingsBySellerAccountID :many
SELECT
    l.id, l.seller_account_id, l.campaign_external_id, l.ozon_product_id, l.offer_id, l.sku, l.is_active, l.status, l.raw_attributes, l.created_at, l.updated_at,
    c.campaign_name,
    c.status AS campaign_status,
    p.name AS product_name
FROM ad_campaign_skus l
LEFT JOIN ad_campaigns c
    ON c.seller_account_id = l.seller_account_id
   AND c.campaign_external_id = l.campaign_external_id
LEFT JOIN products p
    ON p.seller_account_id = l.seller_account_id
   AND p.ozon_product_id = l.ozon_product_id
WHERE l.seller_account_id = $1
ORDER BY l.campaign_external_id ASC, l.ozon_product_id ASC
`

type ListAdCampaignSKUMappingsBySellerAccountIDRow struct {
	ID                 int64
	SellerAccountID    int64
	CampaignExternalID int64
	OzonProductID      int64
	OfferID            pgtype.Text
	Sku                pgtype.Int8
	IsActive           bool
	Status             pgtype.Text
	RawAttributes      []byte
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	CampaignName       pgtype.Text
	CampaignStatus     pgtype.Text
	ProductName        pgtype.Text
}

func (q *Queries) ListAdCampaignSKUMappingsBySellerAccountID(ctx context.Context, sellerAccountID int64) ([]ListAdCampaignSKUMappingsBySellerAccountIDRow, error) {
	rows, err := q.db.Query(ctx, listAdCampaignSKUMappingsBySellerAccountID, sellerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdCampaignSKUMappingsBySellerAccountIDRow
	for rows.Next() {
		var i ListAdCampaignSKUMappingsBySellerAccountIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.CampaignExternalID,
			&i.OzonProductID,
			&i.OfferID,
			&i.Sku,
			&i.IsActive,
			&i.Status,
			&i.RawAttributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CampaignName,
			&i.CampaignStatus,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdCampaignSummariesBySellerAndDateRange = `-- name: ListAdCampaignSummariesBySellerAndDateRange :many
SELECT
    c.seller_account_id,
    c.campaign_external_id,
    c.campaign_name,
    c.campaign_type,
    c.placement_type,
    c.status,
    c.budget_amount,
    c.budget_daily,
    COALESCE(SUM(m.impressions), 0)::bigint AS impressions_total,
    COALESCE(SUM(m.clicks), 0)::bigint AS clicks_total,
    COALESCE(SUM(m.spend), 0)::numeric(18,2) AS spend_total,
    COALESCE(SUM(m.orders_count), 0)::bigint AS orders_total,
    COALESCE(SUM(m.revenue), 0)::numeric(18,2) AS revenue_total,
    MAX(m.metric_date)::date AS latest_metric_date
FROM ad_campaigns c
LEFT JOIN ad_metrics_daily m
    ON m.seller_account_id = c.seller_account_id
   AND m.campaign_external_id = c.campaign_external_id
   AND m.metric_date >= $2::date
   AND m.metric_date <= $3::date
WHERE c.seller_account_id = $1
GROUP BY
    c.seller_account_id,
    c.campaign_external_id,
    c.campaign_name,
    c.campaign_type,
    c.placement_type,
    c.status,
    c.budget_amount,
    c.budget_daily
ORDER BY spend_total DESC, c.campaign_external_id ASC
`

type ListAdCampaignSummariesBySellerAndDateRangeParams struct {
	SellerAccountID int64
	DateFrom        pgtype.Date
	DateTo          pgtype.Date
}

type ListAdCampaignSummariesBySellerAndDateRangeRow struct {
	SellerAccountID    int64
	CampaignExternalID int64
	CampaignName       string
	CampaignType       pgtype.Text
	PlacementType      pgtype.Text
	Status             pgtype.Text
	BudgetAmount       pgtype.Numeric
	BudgetDaily        pgtype.Numeric
	ImpressionsTotal   int64
	ClicksTotal        int64
	SpendTotal         pgtype.Numeric
	OrdersTotal        int64
	RevenueTotal       pgtype.Numeric
	LatestMetricDate   pgtype.Date
}

func (q *Queries) ListAdCampaignSummariesBySellerAndDateRange(ctx context.Context, arg ListAdCampaignSummariesBySellerAndDateRangeParams) ([]ListAdCampaignSummariesBySellerAndDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listAdCampaignSummariesBySellerAndDateRange, arg.SellerAccountID, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdCampaignSummariesBySellerAndDateRangeRow
	for rows.Next() {
		var i ListAdCampaignSummariesBySellerAndDateRangeRow
		if err := rows.Scan(
			&i.SellerAccountID,
			&i.CampaignExternalID,
			&i.CampaignName,
			&i.CampaignType,
			&i.PlacementType,
			&i.Status,
			&i.BudgetAmount,
			&i.BudgetDaily,
			&i.ImpressionsTotal,
			&i.ClicksTotal,
			&i.SpendTotal,
			&i.OrdersTotal,
			&i.RevenueTotal,
			&i.LatestMetricDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdMetricsDailyBySellerAndDateRange = `-- name: ListAdMetricsDailyBySellerAndDateRange :many
SELECT id, seller_account_id, campaign_external_id, metric_date, impressions, clicks, spend, orders_count, revenue, raw_attributes, created_at, updated_at
FROM ad_metrics_daily
WHERE seller_account_id = $1
  AND metric_date >= $2::date
  AND metric_date <= $3::date
ORDER BY metric_date ASC, campaign_external_id ASC
`

type ListAdMetricsDailyBySellerAndDateRangeParams struct {
	SellerAccountID int64
	DateFrom        pgtype.Date
	DateTo          pgtype.Date
}

func (q *Queries) ListAdMetricsDailyBySellerAndDateRange(ctx context.Context, arg ListAdMetricsDailyBySellerAndDateRangeParams) ([]AdMetricsDaily, error) {
	rows, err := q.db.Query(ctx, listAdMetricsDailyBySellerAndDateRange, arg.SellerAccountID, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdMetricsDaily
	for rows.Next() {
		var i AdMetricsDaily
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.CampaignExternalID,
			&i.MetricDate,
			&i.Impressions,
			&i.Clicks,
			&i.Spend,
			&i.OrdersCount,
			&i.Revenue,
			&i.RawAttributes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAdCampaign = `-- name: UpsertAdCampaign :one
INSERT INTO ad_campaigns (
    seller_account_id,
    campaign_external_id,
    campaign_name,
    campaign_type,
    placement_type,
    status,
    budget_amount,
    budget_daily,
    raw_attributes,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW()
)
ON CONFLICT (seller_account_id, campaign_external_id)
DO UPDATE SET
    campaign_name = EXCLUDED.campaign_name,
    campaign_type = EXCLUDED.campaign_type,
    placement_type = EXCLUDED.placement_type,
    status = EXCLUDED.status,
    budget_amount = EXCLUDED.budget_amount,
    budget_daily = EXCLUDED.budget_daily,
    raw_attributes = EXCLUDED.raw_attributes,
    updated_at = NOW()
RETURNING id, seller_account_id, campaign_external_id, campaign_name, campaign_type, placement_type, status, budget_amount, budget_daily, raw_attributes, created_at, updated_at
`

type UpsertAdCampaignParams struct {
	SellerAccountID    int64
	CampaignExternalID int64
	CampaignName       string
	CampaignType       pgtype.Text
	PlacementType      pgtype.Text
	Status             pgtype.Text
	BudgetAmount       pgtype.Numeric
	BudgetDaily        pgtype.Numeric
	RawAttributes      []byte
}

func (q *Queries) UpsertAdCampaign(ctx context.Context, arg UpsertAdCampaignParams) (AdCampaign, error) {
	row := q.db.QueryRow(ctx, upsertAdCampaign,
		arg.SellerAccountID,
		arg.CampaignExternalID,
		arg.CampaignName,
		arg.CampaignType,
		arg.PlacementType,
		arg.Status,
		arg.BudgetAmount,
		arg.BudgetDaily,
		arg.RawAttributes,
	)
	var i AdCampaign
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.CampaignExternalID,
		&i.CampaignName,
		&i.CampaignType,
		&i.PlacementType,
		&i.Status,
		&i.BudgetAmount,
		&i.BudgetDaily,
		&i.RawAttributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAdCampaignSKU = `-- name: UpsertAdCampaignSKU :one
INSERT INTO ad_campaign_skus (
    seller_account_id,
    campaign_external_id,
    ozon_product_id,
    offer_id,
    sku,
    is_active,
    status,
    raw_attributes,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW()
)
ON CONFLICT (seller_account_id, campaign_external_id, ozon_product_id)
DO UPDATE SET
    offer_id = EXCLUDED.offer_id,
    sku = EXCLUDED.sku,
    is_active = EXCLUDED.is_active,
    status = EXCLUDED.status,
    raw_attributes = EXCLUDED.raw_attributes,
    updated_at = NOW()
RETURNING id, seller_account_id, campaign_external_id, ozon_product_id, offer_id, sku, is_active, status, raw_attributes, created_at, updated_at
`

type UpsertAdCampaignSKUParams struct {
	SellerAccountID    int64
	CampaignExternalID int64
	OzonProductID      int64
	OfferID            pgtype.Text
	Sku                pgtype.Int8
	IsActive           bool
	Status             pgtype.Text
	RawAttributes      []byte
}

func (q *Queries) UpsertAdCampaignSKU(ctx context.Context, arg UpsertAdCampaignSKUParams) (AdCampaignSku, error) {
	row := q.db.QueryRow(ctx, upsertAdCampaignSKU,
		arg.SellerAccountID,
		arg.CampaignExternalID,
		arg.OzonProductID,
		arg.OfferID,
		arg.Sku,
		arg.IsActive,
		arg.Status,
		arg.RawAttributes,
	)
	var i AdCampaignSku
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.CampaignExternalID,
		&i.OzonProductID,
		&i.OfferID,
		&i.Sku,
		&i.IsActive,
		&i.Status,
		&i.RawAttributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAdMetricDaily = `-- name: UpsertAdMetricDaily :one
INSERT INTO ad_metrics_daily (
    seller_account_id,
    campaign_external_id,
    metric_date,
    impressions,
    clicks,
    spend,
    orders_count,
    revenue,
    raw_attributes,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW()
)
ON CONFLICT (seller_account_id, campaign_external_id, metric_date)
DO UPDATE SET
    impressions = EXCLUDED.impressions,
    clicks = EXCLUDED.clicks,
    spend = EXCLUDED.spend,
    orders_count = EXCLUDED.orders_count,
    revenue = EXCLUDED.revenue,
    raw_attributes = EXCLUDED.raw_attributes,
    updated_at = NOW()
RETURNING id, seller_account_id, campaign_external_id, metric_date, impressions, clicks, spend, orders_count, revenue, raw_attributes, created_at, updated_at
`

type UpsertAdMetricDailyParams struct {
	SellerAccountID    int64
	CampaignExternalID int64
	MetricDate         pgtype.Date
	Impressions        int64
	Clicks             int64
	Spend              pgtype.Numeric
	OrdersCount        int32
	Revenue            pgtype.Numeric
	RawAttributes      []byte
}

func (q *Queries) UpsertAdMetricDaily(ctx context.Context, arg UpsertAdMetricDailyParams) (AdMetricsDaily, error) {
	row := q.db.QueryRow(ctx, upsertAdMetricDaily,
		arg.SellerAccountID,
		arg.CampaignExternalID,
		arg.MetricDate,
		arg.Impressions,
		arg.Clicks,
		arg.Spend,
		arg.OrdersCount,
		arg.Revenue,
		arg.RawAttributes,
	)
	var i AdMetricsDaily
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.CampaignExternalID,
		&i.MetricDate,
		&i.Impressions,
		&i.Clicks,
		&i.Spend,
		&i.OrdersCount,
		&i.Revenue,
		&i.RawAttributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
