// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeAlertRun = `-- name: CompleteAlertRun :one
UPDATE alert_runs
SET
    status = 'completed',
    finished_at = NOW(),
    sales_alerts_count = $3,
    stock_alerts_count = $4,
    ad_alerts_count = $5,
    price_alerts_count = $6,
    total_alerts_count = $7,
    error_message = NULL
WHERE id = $1
  AND seller_account_id = $2
RETURNING id, seller_account_id, run_type, status, started_at, finished_at, sales_alerts_count, stock_alerts_count, ad_alerts_count, price_alerts_count, total_alerts_count, error_message, created_at
`

type CompleteAlertRunParams struct {
	ID               int64
	SellerAccountID  int64
	SalesAlertsCount int32
	StockAlertsCount int32
	AdAlertsCount    int32
	PriceAlertsCount int32
	TotalAlertsCount int32
}

func (q *Queries) CompleteAlertRun(ctx context.Context, arg CompleteAlertRunParams) (AlertRun, error) {
	row := q.db.QueryRow(ctx, completeAlertRun,
		arg.ID,
		arg.SellerAccountID,
		arg.SalesAlertsCount,
		arg.StockAlertsCount,
		arg.AdAlertsCount,
		arg.PriceAlertsCount,
		arg.TotalAlertsCount,
	)
	var i AlertRun
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.RunType,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SalesAlertsCount,
		&i.StockAlertsCount,
		&i.AdAlertsCount,
		&i.PriceAlertsCount,
		&i.TotalAlertsCount,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const countAlertRunsBySellerAccountID = `-- name: CountAlertRunsBySellerAccountID :one
SELECT COUNT(*)::bigint
FROM alert_runs
WHERE seller_account_id = $1
`

func (q *Queries) CountAlertRunsBySellerAccountID(ctx context.Context, sellerAccountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAlertRunsBySellerAccountID, sellerAccountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countAlertsBySellerAccountID = `-- name: CountAlertsBySellerAccountID :one
SELECT COUNT(*)::bigint
FROM alerts
WHERE seller_account_id = $1
`

func (q *Queries) CountAlertsBySellerAccountID(ctx context.Context, sellerAccountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAlertsBySellerAccountID, sellerAccountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOpenAlertsByGroup = `-- name: CountOpenAlertsByGroup :many
SELECT
    alert_group,
    COUNT(*) AS alerts_count
FROM alerts
WHERE seller_account_id = $1
  AND status = 'open'
GROUP BY alert_group
ORDER BY alert_group ASC
`

type CountOpenAlertsByGroupRow struct {
	AlertGroup  string
	AlertsCount int64
}

func (q *Queries) CountOpenAlertsByGroup(ctx context.Context, sellerAccountID int64) ([]CountOpenAlertsByGroupRow, error) {
	rows, err := q.db.Query(ctx, countOpenAlertsByGroup, sellerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOpenAlertsByGroupRow
	for rows.Next() {
		var i CountOpenAlertsByGroupRow
		if err := rows.Scan(&i.AlertGroup, &i.AlertsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOpenAlertsBySellerAccountID = `-- name: CountOpenAlertsBySellerAccountID :one
SELECT COUNT(*)
FROM alerts
WHERE seller_account_id = $1
  AND status = 'open'
`

func (q *Queries) CountOpenAlertsBySellerAccountID(ctx context.Context, sellerAccountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenAlertsBySellerAccountID, sellerAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenAlertsBySeverity = `-- name: CountOpenAlertsBySeverity :many
SELECT
    severity,
    COUNT(*) AS alerts_count
FROM alerts
WHERE seller_account_id = $1
  AND status = 'open'
GROUP BY severity
ORDER BY severity ASC
`

type CountOpenAlertsBySeverityRow struct {
	Severity    string
	AlertsCount int64
}

func (q *Queries) CountOpenAlertsBySeverity(ctx context.Context, sellerAccountID int64) ([]CountOpenAlertsBySeverityRow, error) {
	rows, err := q.db.Query(ctx, countOpenAlertsBySeverity, sellerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOpenAlertsBySeverityRow
	for rows.Next() {
		var i CountOpenAlertsBySeverityRow
		if err := rows.Scan(&i.Severity, &i.AlertsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAlertRun = `-- name: CreateAlertRun :one
INSERT INTO alert_runs (
    seller_account_id,
    run_type,
    status
) VALUES (
    $1, $2, 'running'
)
RETURNING id, seller_account_id, run_type, status, started_at, finished_at, sales_alerts_count, stock_alerts_count, ad_alerts_count, price_alerts_count, total_alerts_count, error_message, created_at
`

type CreateAlertRunParams struct {
	SellerAccountID int64
	RunType         string
}

func (q *Queries) CreateAlertRun(ctx context.Context, arg CreateAlertRunParams) (AlertRun, error) {
	row := q.db.QueryRow(ctx, createAlertRun, arg.SellerAccountID, arg.RunType)
	var i AlertRun
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.RunType,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SalesAlertsCount,
		&i.StockAlertsCount,
		&i.AdAlertsCount,
		&i.PriceAlertsCount,
		&i.TotalAlertsCount,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAlertRunsBySellerAccountID = `-- name: DeleteAlertRunsBySellerAccountID :exec
DELETE FROM alert_runs
WHERE seller_account_id = $1
`

func (q *Queries) DeleteAlertRunsBySellerAccountID(ctx context.Context, sellerAccountID int64) error {
	_, err := q.db.Exec(ctx, deleteAlertRunsBySellerAccountID, sellerAccountID)
	return err
}

const deleteAlertsBySellerAccountID = `-- name: DeleteAlertsBySellerAccountID :exec
DELETE FROM alerts
WHERE seller_account_id = $1
`

func (q *Queries) DeleteAlertsBySellerAccountID(ctx context.Context, sellerAccountID int64) error {
	_, err := q.db.Exec(ctx, deleteAlertsBySellerAccountID, sellerAccountID)
	return err
}

const dismissAlert = `-- name: DismissAlert :one
UPDATE alerts
SET
    status = 'dismissed',
    resolved_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND seller_account_id = $2
RETURNING id, seller_account_id, alert_type, alert_group, entity_type, entity_id, entity_sku, entity_offer_id, title, message, severity, urgency, status, evidence_payload, fingerprint, first_seen_at, last_seen_at, resolved_at, created_at, updated_at
`

type DismissAlertParams struct {
	ID              int64
	SellerAccountID int64
}

func (q *Queries) DismissAlert(ctx context.Context, arg DismissAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, dismissAlert, arg.ID, arg.SellerAccountID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.AlertType,
		&i.AlertGroup,
		&i.EntityType,
		&i.EntityID,
		&i.EntitySku,
		&i.EntityOfferID,
		&i.Title,
		&i.Message,
		&i.Severity,
		&i.Urgency,
		&i.Status,
		&i.EvidencePayload,
		&i.Fingerprint,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failAlertRun = `-- name: FailAlertRun :one
UPDATE alert_runs
SET
    status = 'failed',
    finished_at = NOW(),
    error_message = $3
WHERE id = $1
  AND seller_account_id = $2
RETURNING id, seller_account_id, run_type, status, started_at, finished_at, sales_alerts_count, stock_alerts_count, ad_alerts_count, price_alerts_count, total_alerts_count, error_message, created_at
`

type FailAlertRunParams struct {
	ID              int64
	SellerAccountID int64
	ErrorMessage    pgtype.Text
}

func (q *Queries) FailAlertRun(ctx context.Context, arg FailAlertRunParams) (AlertRun, error) {
	row := q.db.QueryRow(ctx, failAlertRun, arg.ID, arg.SellerAccountID, arg.ErrorMessage)
	var i AlertRun
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.RunType,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SalesAlertsCount,
		&i.StockAlertsCount,
		&i.AdAlertsCount,
		&i.PriceAlertsCount,
		&i.TotalAlertsCount,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getAlertByID = `-- name: GetAlertByID :one
SELECT id, seller_account_id, alert_type, alert_group, entity_type, entity_id, entity_sku, entity_offer_id, title, message, severity, urgency, status, evidence_payload, fingerprint, first_seen_at, last_seen_at, resolved_at, created_at, updated_at
FROM alerts
WHERE id = $1
  AND seller_account_id = $2
`

type GetAlertByIDParams struct {
	ID              int64
	SellerAccountID int64
}

func (q *Queries) GetAlertByID(ctx context.Context, arg GetAlertByIDParams) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlertByID, arg.ID, arg.SellerAccountID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.AlertType,
		&i.AlertGroup,
		&i.EntityType,
		&i.EntityID,
		&i.EntitySku,
		&i.EntityOfferID,
		&i.Title,
		&i.Message,
		&i.Severity,
		&i.Urgency,
		&i.Status,
		&i.EvidencePayload,
		&i.Fingerprint,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestAlertRunBySellerAccountID = `-- name: GetLatestAlertRunBySellerAccountID :one
SELECT id, seller_account_id, run_type, status, started_at, finished_at, sales_alerts_count, stock_alerts_count, ad_alerts_count, price_alerts_count, total_alerts_count, error_message, created_at
FROM alert_runs
WHERE seller_account_id = $1
ORDER BY started_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestAlertRunBySellerAccountID(ctx context.Context, sellerAccountID int64) (AlertRun, error) {
	row := q.db.QueryRow(ctx, getLatestAlertRunBySellerAccountID, sellerAccountID)
	var i AlertRun
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.RunType,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SalesAlertsCount,
		&i.StockAlertsCount,
		&i.AdAlertsCount,
		&i.PriceAlertsCount,
		&i.TotalAlertsCount,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listAlertRunsBySellerAccountID = `-- name: ListAlertRunsBySellerAccountID :many
SELECT id, seller_account_id, run_type, status, started_at, finished_at, sales_alerts_count, stock_alerts_count, ad_alerts_count, price_alerts_count, total_alerts_count, error_message, created_at
FROM alert_runs
WHERE seller_account_id = $1
ORDER BY started_at DESC, id DESC
LIMIT $2
OFFSET $3
`

type ListAlertRunsBySellerAccountIDParams struct {
	SellerAccountID int64
	Limit           int32
	Offset          int32
}

func (q *Queries) ListAlertRunsBySellerAccountID(ctx context.Context, arg ListAlertRunsBySellerAccountIDParams) ([]AlertRun, error) {
	rows, err := q.db.Query(ctx, listAlertRunsBySellerAccountID, arg.SellerAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertRun
	for rows.Next() {
		var i AlertRun
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.RunType,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.SalesAlertsCount,
			&i.StockAlertsCount,
			&i.AdAlertsCount,
			&i.PriceAlertsCount,
			&i.TotalAlertsCount,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsByEntityID = `-- name: ListAlertsByEntityID :many
SELECT id, seller_account_id, alert_type, alert_group, entity_type, entity_id, entity_sku, entity_offer_id, title, message, severity, urgency, status, evidence_payload, fingerprint, first_seen_at, last_seen_at, resolved_at, created_at, updated_at
FROM alerts
WHERE seller_account_id = $1
  AND entity_type = $2
  AND entity_id = $3
ORDER BY last_seen_at DESC, id DESC
LIMIT $4
OFFSET $5
`

type ListAlertsByEntityIDParams struct {
	SellerAccountID int64
	EntityType      string
	EntityID        pgtype.Text
	Limit           int32
	Offset          int32
}

func (q *Queries) ListAlertsByEntityID(ctx context.Context, arg ListAlertsByEntityIDParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsByEntityID,
		arg.SellerAccountID,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.AlertType,
			&i.AlertGroup,
			&i.EntityType,
			&i.EntityID,
			&i.EntitySku,
			&i.EntityOfferID,
			&i.Title,
			&i.Message,
			&i.Severity,
			&i.Urgency,
			&i.Status,
			&i.EvidencePayload,
			&i.Fingerprint,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsByEntitySKU = `-- name: ListAlertsByEntitySKU :many
SELECT id, seller_account_id, alert_type, alert_group, entity_type, entity_id, entity_sku, entity_offer_id, title, message, severity, urgency, status, evidence_payload, fingerprint, first_seen_at, last_seen_at, resolved_at, created_at, updated_at
FROM alerts
WHERE seller_account_id = $1
  AND entity_sku = $2
ORDER BY last_seen_at DESC, id DESC
LIMIT $3
OFFSET $4
`

type ListAlertsByEntitySKUParams struct {
	SellerAccountID int64
	EntitySku       pgtype.Int8
	Limit           int32
	Offset          int32
}

func (q *Queries) ListAlertsByEntitySKU(ctx context.Context, arg ListAlertsByEntitySKUParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsByEntitySKU,
		arg.SellerAccountID,
		arg.EntitySku,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.AlertType,
			&i.AlertGroup,
			&i.EntityType,
			&i.EntityID,
			&i.EntitySku,
			&i.EntityOfferID,
			&i.Title,
			&i.Message,
			&i.Severity,
			&i.Urgency,
			&i.Status,
			&i.EvidencePayload,
			&i.Fingerprint,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsByGroup = `-- name: ListAlertsByGroup :many
SELECT id, seller_account_id, alert_type, alert_group, entity_type, entity_id, entity_sku, entity_offer_id, title, message, severity, urgency, status, evidence_payload, fingerprint, first_seen_at, last_seen_at, resolved_at, created_at, updated_at
FROM alerts
WHERE seller_account_id = $1
  AND alert_group = $2
ORDER BY last_seen_at DESC, id DESC
LIMIT $3
OFFSET $4
`

type ListAlertsByGroupParams struct {
	SellerAccountID int64
	AlertGroup      string
	Limit           int32
	Offset          int32
}

func (q *Queries) ListAlertsByGroup(ctx context.Context, arg ListAlertsByGroupParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsByGroup,
		arg.SellerAccountID,
		arg.AlertGroup,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.AlertType,
			&i.AlertGroup,
			&i.EntityType,
			&i.EntityID,
			&i.EntitySku,
			&i.EntityOfferID,
			&i.Title,
			&i.Message,
			&i.Severity,
			&i.Urgency,
			&i.Status,
			&i.EvidencePayload,
			&i.Fingerprint,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsBySellerAccountID = `-- name: ListAlertsBySellerAccountID :many
SELECT id, seller_account_id, alert_type, alert_group, entity_type, entity_id, entity_sku, entity_offer_id, title, message, severity, urgency, status, evidence_payload, fingerprint, first_seen_at, last_seen_at, resolved_at, created_at, updated_at
FROM alerts
WHERE seller_account_id = $1
ORDER BY last_seen_at DESC, id DESC
LIMIT $2
OFFSET $3
`

type ListAlertsBySellerAccountIDParams struct {
	SellerAccountID int64
	Limit           int32
	Offset          int32
}

func (q *Queries) ListAlertsBySellerAccountID(ctx context.Context, arg ListAlertsBySellerAccountIDParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsBySellerAccountID, arg.SellerAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.AlertType,
			&i.AlertGroup,
			&i.EntityType,
			&i.EntityID,
			&i.EntitySku,
			&i.EntityOfferID,
			&i.Title,
			&i.Message,
			&i.Severity,
			&i.Urgency,
			&i.Status,
			&i.EvidencePayload,
			&i.Fingerprint,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsFiltered = `-- name: ListAlertsFiltered :many
SELECT id, seller_account_id, alert_type, alert_group, entity_type, entity_id, entity_sku, entity_offer_id, title, message, severity, urgency, status, evidence_payload, fingerprint, first_seen_at, last_seen_at, resolved_at, created_at, updated_at
FROM alerts
WHERE seller_account_id = $1
  AND (
    status = $4
    OR (
      $4::text IS NULL
      AND status IS NOT NULL
    )
  )
  AND (
    alert_group = $5
    OR (
      $5::text IS NULL
      AND alert_group IS NOT NULL
    )
  )
  AND (
    severity = $6
    OR (
      $6::text IS NULL
      AND severity IS NOT NULL
    )
  )
  AND (
    entity_type = $7
    OR (
      $7::text IS NULL
      AND entity_type IS NOT NULL
    )
  )
ORDER BY last_seen_at DESC, id DESC
LIMIT $2
OFFSET $3
`

type ListAlertsFilteredParams struct {
	SellerAccountID int64
	Limit           int32
	Offset          int32
	Status          pgtype.Text
	AlertGroup      pgtype.Text
	Severity        pgtype.Text
	EntityType      pgtype.Text
}

func (q *Queries) ListAlertsFiltered(ctx context.Context, arg ListAlertsFilteredParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsFiltered,
		arg.SellerAccountID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.AlertGroup,
		arg.Severity,
		arg.EntityType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.AlertType,
			&i.AlertGroup,
			&i.EntityType,
			&i.EntityID,
			&i.EntitySku,
			&i.EntityOfferID,
			&i.Title,
			&i.Message,
			&i.Severity,
			&i.Urgency,
			&i.Status,
			&i.EvidencePayload,
			&i.Fingerprint,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenAlertsBySellerAccountID = `-- name: ListOpenAlertsBySellerAccountID :many
SELECT id, seller_account_id, alert_type, alert_group, entity_type, entity_id, entity_sku, entity_offer_id, title, message, severity, urgency, status, evidence_payload, fingerprint, first_seen_at, last_seen_at, resolved_at, created_at, updated_at
FROM alerts
WHERE seller_account_id = $1
  AND status = 'open'
ORDER BY last_seen_at DESC, id DESC
LIMIT $2
OFFSET $3
`

type ListOpenAlertsBySellerAccountIDParams struct {
	SellerAccountID int64
	Limit           int32
	Offset          int32
}

func (q *Queries) ListOpenAlertsBySellerAccountID(ctx context.Context, arg ListOpenAlertsBySellerAccountIDParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listOpenAlertsBySellerAccountID, arg.SellerAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.AlertType,
			&i.AlertGroup,
			&i.EntityType,
			&i.EntityID,
			&i.EntitySku,
			&i.EntityOfferID,
			&i.Title,
			&i.Message,
			&i.Severity,
			&i.Urgency,
			&i.Status,
			&i.EvidencePayload,
			&i.Fingerprint,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAlert = `-- name: ResolveAlert :one
UPDATE alerts
SET
    status = 'resolved',
    resolved_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND seller_account_id = $2
RETURNING id, seller_account_id, alert_type, alert_group, entity_type, entity_id, entity_sku, entity_offer_id, title, message, severity, urgency, status, evidence_payload, fingerprint, first_seen_at, last_seen_at, resolved_at, created_at, updated_at
`

type ResolveAlertParams struct {
	ID              int64
	SellerAccountID int64
}

func (q *Queries) ResolveAlert(ctx context.Context, arg ResolveAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, resolveAlert, arg.ID, arg.SellerAccountID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.AlertType,
		&i.AlertGroup,
		&i.EntityType,
		&i.EntityID,
		&i.EntitySku,
		&i.EntityOfferID,
		&i.Title,
		&i.Message,
		&i.Severity,
		&i.Urgency,
		&i.Status,
		&i.EvidencePayload,
		&i.Fingerprint,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAlert = `-- name: UpsertAlert :one
INSERT INTO alerts (
    seller_account_id,
    alert_type,
    alert_group,
    entity_type,
    entity_id,
    entity_sku,
    entity_offer_id,
    title,
    message,
    severity,
    urgency,
    status,
    evidence_payload,
    fingerprint,
    first_seen_at,
    last_seen_at,
    resolved_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 'open', $12, $13, NOW(), NOW(), NULL, NOW()
)
ON CONFLICT (seller_account_id, fingerprint)
DO UPDATE SET
    alert_type = CASE
        WHEN alerts.status = 'dismissed' THEN alerts.alert_type
        ELSE EXCLUDED.alert_type
    END,
    alert_group = CASE
        WHEN alerts.status = 'dismissed' THEN alerts.alert_group
        ELSE EXCLUDED.alert_group
    END,
    entity_type = CASE
        WHEN alerts.status = 'dismissed' THEN alerts.entity_type
        ELSE EXCLUDED.entity_type
    END,
    entity_id = CASE
        WHEN alerts.status = 'dismissed' THEN alerts.entity_id
        ELSE EXCLUDED.entity_id
    END,
    entity_sku = CASE
        WHEN alerts.status = 'dismissed' THEN alerts.entity_sku
        ELSE EXCLUDED.entity_sku
    END,
    entity_offer_id = CASE
        WHEN alerts.status = 'dismissed' THEN alerts.entity_offer_id
        ELSE EXCLUDED.entity_offer_id
    END,
    title = CASE
        WHEN alerts.status = 'dismissed' THEN alerts.title
        ELSE EXCLUDED.title
    END,
    message = CASE
        WHEN alerts.status = 'dismissed' THEN alerts.message
        ELSE EXCLUDED.message
    END,
    severity = CASE
        WHEN alerts.status = 'dismissed' THEN alerts.severity
        ELSE EXCLUDED.severity
    END,
    urgency = CASE
        WHEN alerts.status = 'dismissed' THEN alerts.urgency
        ELSE EXCLUDED.urgency
    END,
    status = CASE
        WHEN alerts.status = 'dismissed' THEN alerts.status
        ELSE 'open'
    END,
    evidence_payload = EXCLUDED.evidence_payload,
    last_seen_at = NOW(),
    resolved_at = CASE
        WHEN alerts.status = 'dismissed' THEN alerts.resolved_at
        ELSE NULL
    END,
    updated_at = NOW()
RETURNING id, seller_account_id, alert_type, alert_group, entity_type, entity_id, entity_sku, entity_offer_id, title, message, severity, urgency, status, evidence_payload, fingerprint, first_seen_at, last_seen_at, resolved_at, created_at, updated_at
`

type UpsertAlertParams struct {
	SellerAccountID int64
	AlertType       string
	AlertGroup      string
	EntityType      string
	EntityID        pgtype.Text
	EntitySku       pgtype.Int8
	EntityOfferID   pgtype.Text
	Title           string
	Message         string
	Severity        string
	Urgency         string
	EvidencePayload []byte
	Fingerprint     string
}

func (q *Queries) UpsertAlert(ctx context.Context, arg UpsertAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, upsertAlert,
		arg.SellerAccountID,
		arg.AlertType,
		arg.AlertGroup,
		arg.EntityType,
		arg.EntityID,
		arg.EntitySku,
		arg.EntityOfferID,
		arg.Title,
		arg.Message,
		arg.Severity,
		arg.Urgency,
		arg.EvidencePayload,
		arg.Fingerprint,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.AlertType,
		&i.AlertGroup,
		&i.EntityType,
		&i.EntityID,
		&i.EntitySku,
		&i.EntityOfferID,
		&i.Title,
		&i.Message,
		&i.Severity,
		&i.Urgency,
		&i.Status,
		&i.EvidencePayload,
		&i.Fingerprint,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
