// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveChatSession = `-- name: ArchiveChatSession :one
UPDATE chat_sessions
SET
    status = 'archived',
    updated_at = NOW()
WHERE seller_account_id = $1
  AND id = $2
RETURNING id, seller_account_id, user_id, title, status, created_at, updated_at, last_message_at
`

type ArchiveChatSessionParams struct {
	SellerAccountID int64
	ID              int64
}

func (q *Queries) ArchiveChatSession(ctx context.Context, arg ArchiveChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, archiveChatSession, arg.SellerAccountID, arg.ID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const completeChatTrace = `-- name: CompleteChatTrace :one
UPDATE chat_traces
SET
    assistant_message_id = $3,
    detected_intent = $4,
    tool_plan_payload = $5,
    validated_tool_plan_payload = $6,
    tool_results_payload = $7,
    fact_context_payload = $8,
    raw_planner_response = $9,
    raw_answer_response = $10,
    answer_validation_payload = $11,
    input_tokens = $12,
    output_tokens = $13,
    estimated_cost = $14,
    status = 'completed',
    error_message = NULL,
    finished_at = NOW()
WHERE seller_account_id = $1
  AND id = $2
RETURNING id, session_id, user_message_id, assistant_message_id, seller_account_id, planner_prompt_version, answer_prompt_version, planner_model, answer_model, detected_intent, tool_plan_payload, validated_tool_plan_payload, tool_results_payload, fact_context_payload, raw_planner_response, raw_answer_response, answer_validation_payload, input_tokens, output_tokens, estimated_cost, status, error_message, started_at, finished_at, created_at
`

type CompleteChatTraceParams struct {
	SellerAccountID          int64
	ID                       int64
	AssistantMessageID       pgtype.Int8
	DetectedIntent           pgtype.Text
	ToolPlanPayload          []byte
	ValidatedToolPlanPayload []byte
	ToolResultsPayload       []byte
	FactContextPayload       []byte
	RawPlannerResponse       []byte
	RawAnswerResponse        []byte
	AnswerValidationPayload  []byte
	InputTokens              int32
	OutputTokens             int32
	EstimatedCost            pgtype.Numeric
}

func (q *Queries) CompleteChatTrace(ctx context.Context, arg CompleteChatTraceParams) (ChatTrace, error) {
	row := q.db.QueryRow(ctx, completeChatTrace,
		arg.SellerAccountID,
		arg.ID,
		arg.AssistantMessageID,
		arg.DetectedIntent,
		arg.ToolPlanPayload,
		arg.ValidatedToolPlanPayload,
		arg.ToolResultsPayload,
		arg.FactContextPayload,
		arg.RawPlannerResponse,
		arg.RawAnswerResponse,
		arg.AnswerValidationPayload,
		arg.InputTokens,
		arg.OutputTokens,
		arg.EstimatedCost,
	)
	var i ChatTrace
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.SellerAccountID,
		&i.PlannerPromptVersion,
		&i.AnswerPromptVersion,
		&i.PlannerModel,
		&i.AnswerModel,
		&i.DetectedIntent,
		&i.ToolPlanPayload,
		&i.ValidatedToolPlanPayload,
		&i.ToolResultsPayload,
		&i.FactContextPayload,
		&i.RawPlannerResponse,
		&i.RawAnswerResponse,
		&i.AnswerValidationPayload,
		&i.InputTokens,
		&i.OutputTokens,
		&i.EstimatedCost,
		&i.Status,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createChatFeedback = `-- name: CreateChatFeedback :one
INSERT INTO chat_feedback (
    session_id,
    message_id,
    seller_account_id,
    rating,
    comment
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (seller_account_id, message_id)
DO UPDATE SET
    rating = EXCLUDED.rating,
    comment = EXCLUDED.comment,
    created_at = NOW()
RETURNING id, session_id, message_id, seller_account_id, rating, comment, created_at
`

type CreateChatFeedbackParams struct {
	SessionID       int64
	MessageID       int64
	SellerAccountID int64
	Rating          string
	Comment         pgtype.Text
}

func (q *Queries) CreateChatFeedback(ctx context.Context, arg CreateChatFeedbackParams) (ChatFeedback, error) {
	row := q.db.QueryRow(ctx, createChatFeedback,
		arg.SessionID,
		arg.MessageID,
		arg.SellerAccountID,
		arg.Rating,
		arg.Comment,
	)
	var i ChatFeedback
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.SellerAccountID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (
    session_id,
    seller_account_id,
    role,
    content,
    message_type
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, session_id, seller_account_id, role, content, message_type, created_at
`

type CreateChatMessageParams struct {
	SessionID       int64
	SellerAccountID int64
	Role            string
	Content         string
	MessageType     string
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.SessionID,
		arg.SellerAccountID,
		arg.Role,
		arg.Content,
		arg.MessageType,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SellerAccountID,
		&i.Role,
		&i.Content,
		&i.MessageType,
		&i.CreatedAt,
	)
	return i, err
}

const createChatSession = `-- name: CreateChatSession :one
INSERT INTO chat_sessions (
    seller_account_id,
    user_id,
    title
) VALUES (
    $1, $2, $3
)
RETURNING id, seller_account_id, user_id, title, status, created_at, updated_at, last_message_at
`

type CreateChatSessionParams struct {
	SellerAccountID int64
	UserID          pgtype.Int8
	Title           string
}

func (q *Queries) CreateChatSession(ctx context.Context, arg CreateChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, createChatSession, arg.SellerAccountID, arg.UserID, arg.Title)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const createChatTrace = `-- name: CreateChatTrace :one
INSERT INTO chat_traces (
    session_id,
    user_message_id,
    seller_account_id,
    planner_prompt_version,
    answer_prompt_version,
    planner_model,
    answer_model,
    status,
    started_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 'running', NOW()
)
RETURNING id, session_id, user_message_id, assistant_message_id, seller_account_id, planner_prompt_version, answer_prompt_version, planner_model, answer_model, detected_intent, tool_plan_payload, validated_tool_plan_payload, tool_results_payload, fact_context_payload, raw_planner_response, raw_answer_response, answer_validation_payload, input_tokens, output_tokens, estimated_cost, status, error_message, started_at, finished_at, created_at
`

type CreateChatTraceParams struct {
	SessionID            int64
	UserMessageID        pgtype.Int8
	SellerAccountID      int64
	PlannerPromptVersion string
	AnswerPromptVersion  string
	PlannerModel         string
	AnswerModel          string
}

func (q *Queries) CreateChatTrace(ctx context.Context, arg CreateChatTraceParams) (ChatTrace, error) {
	row := q.db.QueryRow(ctx, createChatTrace,
		arg.SessionID,
		arg.UserMessageID,
		arg.SellerAccountID,
		arg.PlannerPromptVersion,
		arg.AnswerPromptVersion,
		arg.PlannerModel,
		arg.AnswerModel,
	)
	var i ChatTrace
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.SellerAccountID,
		&i.PlannerPromptVersion,
		&i.AnswerPromptVersion,
		&i.PlannerModel,
		&i.AnswerModel,
		&i.DetectedIntent,
		&i.ToolPlanPayload,
		&i.ValidatedToolPlanPayload,
		&i.ToolResultsPayload,
		&i.FactContextPayload,
		&i.RawPlannerResponse,
		&i.RawAnswerResponse,
		&i.AnswerValidationPayload,
		&i.InputTokens,
		&i.OutputTokens,
		&i.EstimatedCost,
		&i.Status,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const failChatTrace = `-- name: FailChatTrace :one
UPDATE chat_traces
SET
    detected_intent = $3,
    tool_plan_payload = $4,
    validated_tool_plan_payload = $5,
    tool_results_payload = $6,
    fact_context_payload = $7,
    raw_planner_response = $8,
    raw_answer_response = $9,
    answer_validation_payload = $10,
    input_tokens = $11,
    output_tokens = $12,
    estimated_cost = $13,
    error_message = $14,
    status = 'failed',
    finished_at = NOW()
WHERE seller_account_id = $1
  AND id = $2
RETURNING id, session_id, user_message_id, assistant_message_id, seller_account_id, planner_prompt_version, answer_prompt_version, planner_model, answer_model, detected_intent, tool_plan_payload, validated_tool_plan_payload, tool_results_payload, fact_context_payload, raw_planner_response, raw_answer_response, answer_validation_payload, input_tokens, output_tokens, estimated_cost, status, error_message, started_at, finished_at, created_at
`

type FailChatTraceParams struct {
	SellerAccountID          int64
	ID                       int64
	DetectedIntent           pgtype.Text
	ToolPlanPayload          []byte
	ValidatedToolPlanPayload []byte
	ToolResultsPayload       []byte
	FactContextPayload       []byte
	RawPlannerResponse       []byte
	RawAnswerResponse        []byte
	AnswerValidationPayload  []byte
	InputTokens              int32
	OutputTokens             int32
	EstimatedCost            pgtype.Numeric
	ErrorMessage             pgtype.Text
}

func (q *Queries) FailChatTrace(ctx context.Context, arg FailChatTraceParams) (ChatTrace, error) {
	row := q.db.QueryRow(ctx, failChatTrace,
		arg.SellerAccountID,
		arg.ID,
		arg.DetectedIntent,
		arg.ToolPlanPayload,
		arg.ValidatedToolPlanPayload,
		arg.ToolResultsPayload,
		arg.FactContextPayload,
		arg.RawPlannerResponse,
		arg.RawAnswerResponse,
		arg.AnswerValidationPayload,
		arg.InputTokens,
		arg.OutputTokens,
		arg.EstimatedCost,
		arg.ErrorMessage,
	)
	var i ChatTrace
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.SellerAccountID,
		&i.PlannerPromptVersion,
		&i.AnswerPromptVersion,
		&i.PlannerModel,
		&i.AnswerModel,
		&i.DetectedIntent,
		&i.ToolPlanPayload,
		&i.ValidatedToolPlanPayload,
		&i.ToolResultsPayload,
		&i.FactContextPayload,
		&i.RawPlannerResponse,
		&i.RawAnswerResponse,
		&i.AnswerValidationPayload,
		&i.InputTokens,
		&i.OutputTokens,
		&i.EstimatedCost,
		&i.Status,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getChatFeedbackByMessageID = `-- name: GetChatFeedbackByMessageID :one
SELECT id, session_id, message_id, seller_account_id, rating, comment, created_at
FROM chat_feedback
WHERE seller_account_id = $1
  AND message_id = $2
`

type GetChatFeedbackByMessageIDParams struct {
	SellerAccountID int64
	MessageID       int64
}

func (q *Queries) GetChatFeedbackByMessageID(ctx context.Context, arg GetChatFeedbackByMessageIDParams) (ChatFeedback, error) {
	row := q.db.QueryRow(ctx, getChatFeedbackByMessageID, arg.SellerAccountID, arg.MessageID)
	var i ChatFeedback
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.SellerAccountID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getChatMessageByID = `-- name: GetChatMessageByID :one
SELECT id, session_id, seller_account_id, role, content, message_type, created_at
FROM chat_messages
WHERE seller_account_id = $1
  AND id = $2
`

type GetChatMessageByIDParams struct {
	SellerAccountID int64
	ID              int64
}

func (q *Queries) GetChatMessageByID(ctx context.Context, arg GetChatMessageByIDParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, getChatMessageByID, arg.SellerAccountID, arg.ID)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SellerAccountID,
		&i.Role,
		&i.Content,
		&i.MessageType,
		&i.CreatedAt,
	)
	return i, err
}

const getChatSessionByID = `-- name: GetChatSessionByID :one
SELECT id, seller_account_id, user_id, title, status, created_at, updated_at, last_message_at
FROM chat_sessions
WHERE seller_account_id = $1
  AND id = $2
`

type GetChatSessionByIDParams struct {
	SellerAccountID int64
	ID              int64
}

func (q *Queries) GetChatSessionByID(ctx context.Context, arg GetChatSessionByIDParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getChatSessionByID, arg.SellerAccountID, arg.ID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const getChatTraceByID = `-- name: GetChatTraceByID :one
SELECT id, session_id, user_message_id, assistant_message_id, seller_account_id, planner_prompt_version, answer_prompt_version, planner_model, answer_model, detected_intent, tool_plan_payload, validated_tool_plan_payload, tool_results_payload, fact_context_payload, raw_planner_response, raw_answer_response, answer_validation_payload, input_tokens, output_tokens, estimated_cost, status, error_message, started_at, finished_at, created_at
FROM chat_traces
WHERE seller_account_id = $1
  AND id = $2
`

type GetChatTraceByIDParams struct {
	SellerAccountID int64
	ID              int64
}

func (q *Queries) GetChatTraceByID(ctx context.Context, arg GetChatTraceByIDParams) (ChatTrace, error) {
	row := q.db.QueryRow(ctx, getChatTraceByID, arg.SellerAccountID, arg.ID)
	var i ChatTrace
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.SellerAccountID,
		&i.PlannerPromptVersion,
		&i.AnswerPromptVersion,
		&i.PlannerModel,
		&i.AnswerModel,
		&i.DetectedIntent,
		&i.ToolPlanPayload,
		&i.ValidatedToolPlanPayload,
		&i.ToolResultsPayload,
		&i.FactContextPayload,
		&i.RawPlannerResponse,
		&i.RawAnswerResponse,
		&i.AnswerValidationPayload,
		&i.InputTokens,
		&i.OutputTokens,
		&i.EstimatedCost,
		&i.Status,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestChatTraceBySessionID = `-- name: GetLatestChatTraceBySessionID :one
SELECT id, session_id, user_message_id, assistant_message_id, seller_account_id, planner_prompt_version, answer_prompt_version, planner_model, answer_model, detected_intent, tool_plan_payload, validated_tool_plan_payload, tool_results_payload, fact_context_payload, raw_planner_response, raw_answer_response, answer_validation_payload, input_tokens, output_tokens, estimated_cost, status, error_message, started_at, finished_at, created_at
FROM chat_traces
WHERE seller_account_id = $1
  AND session_id = $2
ORDER BY started_at DESC, id DESC
LIMIT 1
`

type GetLatestChatTraceBySessionIDParams struct {
	SellerAccountID int64
	SessionID       int64
}

func (q *Queries) GetLatestChatTraceBySessionID(ctx context.Context, arg GetLatestChatTraceBySessionIDParams) (ChatTrace, error) {
	row := q.db.QueryRow(ctx, getLatestChatTraceBySessionID, arg.SellerAccountID, arg.SessionID)
	var i ChatTrace
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.SellerAccountID,
		&i.PlannerPromptVersion,
		&i.AnswerPromptVersion,
		&i.PlannerModel,
		&i.AnswerModel,
		&i.DetectedIntent,
		&i.ToolPlanPayload,
		&i.ValidatedToolPlanPayload,
		&i.ToolResultsPayload,
		&i.FactContextPayload,
		&i.RawPlannerResponse,
		&i.RawAnswerResponse,
		&i.AnswerValidationPayload,
		&i.InputTokens,
		&i.OutputTokens,
		&i.EstimatedCost,
		&i.Status,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveChatSessionsBySellerAccountID = `-- name: ListActiveChatSessionsBySellerAccountID :many
SELECT id, seller_account_id, user_id, title, status, created_at, updated_at, last_message_at
FROM chat_sessions
WHERE seller_account_id = $1
  AND status = 'active'
ORDER BY COALESCE(last_message_at, created_at) DESC, id DESC
LIMIT $2
OFFSET $3
`

type ListActiveChatSessionsBySellerAccountIDParams struct {
	SellerAccountID int64
	Limit           int32
	Offset          int32
}

func (q *Queries) ListActiveChatSessionsBySellerAccountID(ctx context.Context, arg ListActiveChatSessionsBySellerAccountIDParams) ([]ChatSession, error) {
	rows, err := q.db.Query(ctx, listActiveChatSessionsBySellerAccountID, arg.SellerAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatSession
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatFeedbackBySellerAccountID = `-- name: ListChatFeedbackBySellerAccountID :many
SELECT id, session_id, message_id, seller_account_id, rating, comment, created_at
FROM chat_feedback
WHERE seller_account_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
OFFSET $3
`

type ListChatFeedbackBySellerAccountIDParams struct {
	SellerAccountID int64
	Limit           int32
	Offset          int32
}

func (q *Queries) ListChatFeedbackBySellerAccountID(ctx context.Context, arg ListChatFeedbackBySellerAccountIDParams) ([]ChatFeedback, error) {
	rows, err := q.db.Query(ctx, listChatFeedbackBySellerAccountID, arg.SellerAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatFeedback
	for rows.Next() {
		var i ChatFeedback
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MessageID,
			&i.SellerAccountID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatMessagesBySessionID = `-- name: ListChatMessagesBySessionID :many
SELECT id, session_id, seller_account_id, role, content, message_type, created_at
FROM chat_messages
WHERE seller_account_id = $1
  AND session_id = $2
ORDER BY created_at ASC, id ASC
LIMIT $3
OFFSET $4
`

type ListChatMessagesBySessionIDParams struct {
	SellerAccountID int64
	SessionID       int64
	Limit           int32
	Offset          int32
}

func (q *Queries) ListChatMessagesBySessionID(ctx context.Context, arg ListChatMessagesBySessionIDParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listChatMessagesBySessionID,
		arg.SellerAccountID,
		arg.SessionID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SellerAccountID,
			&i.Role,
			&i.Content,
			&i.MessageType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatSessionsBySellerAccountID = `-- name: ListChatSessionsBySellerAccountID :many
SELECT id, seller_account_id, user_id, title, status, created_at, updated_at, last_message_at
FROM chat_sessions
WHERE seller_account_id = $1
ORDER BY COALESCE(last_message_at, created_at) DESC, id DESC
LIMIT $2
OFFSET $3
`

type ListChatSessionsBySellerAccountIDParams struct {
	SellerAccountID int64
	Limit           int32
	Offset          int32
}

func (q *Queries) ListChatSessionsBySellerAccountID(ctx context.Context, arg ListChatSessionsBySellerAccountIDParams) ([]ChatSession, error) {
	rows, err := q.db.Query(ctx, listChatSessionsBySellerAccountID, arg.SellerAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatSession
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatTracesBySessionID = `-- name: ListChatTracesBySessionID :many
SELECT id, session_id, user_message_id, assistant_message_id, seller_account_id, planner_prompt_version, answer_prompt_version, planner_model, answer_model, detected_intent, tool_plan_payload, validated_tool_plan_payload, tool_results_payload, fact_context_payload, raw_planner_response, raw_answer_response, answer_validation_payload, input_tokens, output_tokens, estimated_cost, status, error_message, started_at, finished_at, created_at
FROM chat_traces
WHERE seller_account_id = $1
  AND session_id = $2
ORDER BY started_at DESC, id DESC
LIMIT $3
OFFSET $4
`

type ListChatTracesBySessionIDParams struct {
	SellerAccountID int64
	SessionID       int64
	Limit           int32
	Offset          int32
}

func (q *Queries) ListChatTracesBySessionID(ctx context.Context, arg ListChatTracesBySessionIDParams) ([]ChatTrace, error) {
	rows, err := q.db.Query(ctx, listChatTracesBySessionID,
		arg.SellerAccountID,
		arg.SessionID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatTrace
	for rows.Next() {
		var i ChatTrace
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserMessageID,
			&i.AssistantMessageID,
			&i.SellerAccountID,
			&i.PlannerPromptVersion,
			&i.AnswerPromptVersion,
			&i.PlannerModel,
			&i.AnswerModel,
			&i.DetectedIntent,
			&i.ToolPlanPayload,
			&i.ValidatedToolPlanPayload,
			&i.ToolResultsPayload,
			&i.FactContextPayload,
			&i.RawPlannerResponse,
			&i.RawAnswerResponse,
			&i.AnswerValidationPayload,
			&i.InputTokens,
			&i.OutputTokens,
			&i.EstimatedCost,
			&i.Status,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentChatMessagesBySessionID = `-- name: ListRecentChatMessagesBySessionID :many
SELECT id, session_id, seller_account_id, role, content, message_type, created_at
FROM chat_messages
WHERE seller_account_id = $1
  AND session_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListRecentChatMessagesBySessionIDParams struct {
	SellerAccountID int64
	SessionID       int64
	Limit           int32
}

func (q *Queries) ListRecentChatMessagesBySessionID(ctx context.Context, arg ListRecentChatMessagesBySessionIDParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listRecentChatMessagesBySessionID, arg.SellerAccountID, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SellerAccountID,
			&i.Role,
			&i.Content,
			&i.MessageType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchChatSession = `-- name: TouchChatSession :one
UPDATE chat_sessions
SET
    last_message_at = NOW(),
    updated_at = NOW()
WHERE seller_account_id = $1
  AND id = $2
RETURNING id, seller_account_id, user_id, title, status, created_at, updated_at, last_message_at
`

type TouchChatSessionParams struct {
	SellerAccountID int64
	ID              int64
}

func (q *Queries) TouchChatSession(ctx context.Context, arg TouchChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, touchChatSession, arg.SellerAccountID, arg.ID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const updateChatSessionTitle = `-- name: UpdateChatSessionTitle :one
UPDATE chat_sessions
SET
    title = $3,
    updated_at = NOW()
WHERE seller_account_id = $1
  AND id = $2
RETURNING id, seller_account_id, user_id, title, status, created_at, updated_at, last_message_at
`

type UpdateChatSessionTitleParams struct {
	SellerAccountID int64
	ID              int64
	Title           string
}

func (q *Queries) UpdateChatSessionTitle(ctx context.Context, arg UpdateChatSessionTitleParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, updateChatSessionTitle, arg.SellerAccountID, arg.ID, arg.Title)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
	)
	return i, err
}
