// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: daily_account_metrics.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDailyAccountMetricsBySellerAndDateRange = `-- name: DeleteDailyAccountMetricsBySellerAndDateRange :exec
DELETE FROM daily_account_metrics
WHERE seller_account_id = $1
  AND metric_date >= $2
  AND metric_date <= $3
`

type DeleteDailyAccountMetricsBySellerAndDateRangeParams struct {
	SellerAccountID int64
	MetricDate      pgtype.Date
	MetricDate_2    pgtype.Date
}

func (q *Queries) DeleteDailyAccountMetricsBySellerAndDateRange(ctx context.Context, arg DeleteDailyAccountMetricsBySellerAndDateRangeParams) error {
	_, err := q.db.Exec(ctx, deleteDailyAccountMetricsBySellerAndDateRange, arg.SellerAccountID, arg.MetricDate, arg.MetricDate_2)
	return err
}

const getDailyAccountMetricSourceDateBoundsBySellerAccountID = `-- name: GetDailyAccountMetricSourceDateBoundsBySellerAccountID :one
WITH source_dates AS (
    SELECT sale_date::date AS metric_date
    FROM sales s
    WHERE s.seller_account_id = $1
      AND s.sale_date IS NOT NULL

    UNION ALL

    SELECT created_at_source::date AS metric_date
    FROM orders o
    WHERE o.seller_account_id = $1
      AND o.created_at_source IS NOT NULL
)
SELECT
    MIN(metric_date)::date AS min_date,
    MAX(metric_date)::date AS max_date
FROM source_dates
`

type GetDailyAccountMetricSourceDateBoundsBySellerAccountIDRow struct {
	MinDate pgtype.Date
	MaxDate pgtype.Date
}

func (q *Queries) GetDailyAccountMetricSourceDateBoundsBySellerAccountID(ctx context.Context, sellerAccountID int64) (GetDailyAccountMetricSourceDateBoundsBySellerAccountIDRow, error) {
	row := q.db.QueryRow(ctx, getDailyAccountMetricSourceDateBoundsBySellerAccountID, sellerAccountID)
	var i GetDailyAccountMetricSourceDateBoundsBySellerAccountIDRow
	err := row.Scan(&i.MinDate, &i.MaxDate)
	return i, err
}

const getLatestAvailableDashboardMetricDateBySellerAccountID = `-- name: GetLatestAvailableDashboardMetricDateBySellerAccountID :one
SELECT GREATEST(
    COALESCE((SELECT MAX(dam.metric_date) FROM daily_account_metrics dam WHERE dam.seller_account_id = $1), '1970-01-01'::date),
    COALESCE((SELECT MAX(dsm.metric_date) FROM daily_sku_metrics dsm WHERE dsm.seller_account_id = $1), '1970-01-01'::date)
)::date AS latest_date
`

func (q *Queries) GetLatestAvailableDashboardMetricDateBySellerAccountID(ctx context.Context, sellerAccountID int64) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getLatestAvailableDashboardMetricDateBySellerAccountID, sellerAccountID)
	var latest_date pgtype.Date
	err := row.Scan(&latest_date)
	return latest_date, err
}

const listDailyAccountMetricSourcesBySellerAndDateRange = `-- name: ListDailyAccountMetricSourcesBySellerAndDateRange :many
WITH sales_by_day AS (
    SELECT
        s.sale_date::date AS metric_date,
        COALESCE(SUM(s.amount), 0)::numeric(18,2) AS revenue
    FROM sales s
    WHERE s.seller_account_id = $1
      AND s.sale_date IS NOT NULL
      AND s.sale_date::date >= $2::date
      AND s.sale_date::date <= $3::date
    GROUP BY s.sale_date::date
),
orders_by_day AS (
    SELECT
        o.created_at_source::date AS metric_date,
        COUNT(*)::integer AS orders_count,
        COUNT(*) FILTER (WHERE LOWER(COALESCE(o.status, '')) = 'returned')::integer AS returns_count,
        COUNT(*) FILTER (WHERE LOWER(COALESCE(o.status, '')) = 'cancelled')::integer AS cancel_count
    FROM orders o
    WHERE o.seller_account_id = $1
      AND o.created_at_source IS NOT NULL
      AND o.created_at_source::date >= $2::date
      AND o.created_at_source::date <= $3::date
    GROUP BY o.created_at_source::date
),
days AS (
    SELECT metric_date FROM sales_by_day
    UNION
    SELECT metric_date FROM orders_by_day
)
SELECT
    d.metric_date,
    COALESCE(s.revenue, 0)::numeric(18,2) AS revenue,
    COALESCE(o.orders_count, 0)::integer AS orders_count,
    COALESCE(o.returns_count, 0)::integer AS returns_count,
    COALESCE(o.cancel_count, 0)::integer AS cancel_count
FROM days d
LEFT JOIN sales_by_day s ON s.metric_date = d.metric_date
LEFT JOIN orders_by_day o ON o.metric_date = d.metric_date
ORDER BY d.metric_date ASC
`

type ListDailyAccountMetricSourcesBySellerAndDateRangeParams struct {
	SellerAccountID int64
	Column2         pgtype.Date
	Column3         pgtype.Date
}

type ListDailyAccountMetricSourcesBySellerAndDateRangeRow struct {
	MetricDate   pgtype.Date
	Revenue      pgtype.Numeric
	OrdersCount  int32
	ReturnsCount int32
	CancelCount  int32
}

func (q *Queries) ListDailyAccountMetricSourcesBySellerAndDateRange(ctx context.Context, arg ListDailyAccountMetricSourcesBySellerAndDateRangeParams) ([]ListDailyAccountMetricSourcesBySellerAndDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listDailyAccountMetricSourcesBySellerAndDateRange, arg.SellerAccountID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailyAccountMetricSourcesBySellerAndDateRangeRow
	for rows.Next() {
		var i ListDailyAccountMetricSourcesBySellerAndDateRangeRow
		if err := rows.Scan(
			&i.MetricDate,
			&i.Revenue,
			&i.OrdersCount,
			&i.ReturnsCount,
			&i.CancelCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyAccountMetricsBySellerAndDateRange = `-- name: ListDailyAccountMetricsBySellerAndDateRange :many
SELECT id, seller_account_id, metric_date, revenue, orders_count, returns_count, cancel_count, created_at, updated_at
FROM daily_account_metrics
WHERE seller_account_id = $1
  AND metric_date >= $2
  AND metric_date <= $3
ORDER BY metric_date ASC
`

type ListDailyAccountMetricsBySellerAndDateRangeParams struct {
	SellerAccountID int64
	MetricDate      pgtype.Date
	MetricDate_2    pgtype.Date
}

func (q *Queries) ListDailyAccountMetricsBySellerAndDateRange(ctx context.Context, arg ListDailyAccountMetricsBySellerAndDateRangeParams) ([]DailyAccountMetric, error) {
	rows, err := q.db.Query(ctx, listDailyAccountMetricsBySellerAndDateRange, arg.SellerAccountID, arg.MetricDate, arg.MetricDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyAccountMetric
	for rows.Next() {
		var i DailyAccountMetric
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.MetricDate,
			&i.Revenue,
			&i.OrdersCount,
			&i.ReturnsCount,
			&i.CancelCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyAccountMetric = `-- name: UpsertDailyAccountMetric :one
INSERT INTO daily_account_metrics (
    seller_account_id,
    metric_date,
    revenue,
    orders_count,
    returns_count,
    cancel_count,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW()
)
ON CONFLICT (seller_account_id, metric_date)
DO UPDATE SET
    revenue = EXCLUDED.revenue,
    orders_count = EXCLUDED.orders_count,
    returns_count = EXCLUDED.returns_count,
    cancel_count = EXCLUDED.cancel_count,
    updated_at = NOW()
RETURNING id, seller_account_id, metric_date, revenue, orders_count, returns_count, cancel_count, created_at, updated_at
`

type UpsertDailyAccountMetricParams struct {
	SellerAccountID int64
	MetricDate      pgtype.Date
	Revenue         pgtype.Numeric
	OrdersCount     int32
	ReturnsCount    int32
	CancelCount     int32
}

func (q *Queries) UpsertDailyAccountMetric(ctx context.Context, arg UpsertDailyAccountMetricParams) (DailyAccountMetric, error) {
	row := q.db.QueryRow(ctx, upsertDailyAccountMetric,
		arg.SellerAccountID,
		arg.MetricDate,
		arg.Revenue,
		arg.OrdersCount,
		arg.ReturnsCount,
		arg.CancelCount,
	)
	var i DailyAccountMetric
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.MetricDate,
		&i.Revenue,
		&i.OrdersCount,
		&i.ReturnsCount,
		&i.CancelCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
