// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: daily_sku_metrics.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDailySKUMetricsBySellerAndDateRange = `-- name: DeleteDailySKUMetricsBySellerAndDateRange :exec
DELETE FROM daily_sku_metrics
WHERE seller_account_id = $1
  AND metric_date >= $2
  AND metric_date <= $3
`

type DeleteDailySKUMetricsBySellerAndDateRangeParams struct {
	SellerAccountID int64
	MetricDate      pgtype.Date
	MetricDate_2    pgtype.Date
}

func (q *Queries) DeleteDailySKUMetricsBySellerAndDateRange(ctx context.Context, arg DeleteDailySKUMetricsBySellerAndDateRangeParams) error {
	_, err := q.db.Exec(ctx, deleteDailySKUMetricsBySellerAndDateRange, arg.SellerAccountID, arg.MetricDate, arg.MetricDate_2)
	return err
}

const getDailySKUMetricSourceDateBoundsBySellerAccountID = `-- name: GetDailySKUMetricSourceDateBoundsBySellerAccountID :one
WITH source_dates AS (
    SELECT s.sale_date::date AS metric_date
    FROM sales s
    WHERE s.seller_account_id = $1
      AND s.sale_date IS NOT NULL
      AND (
        (s.raw_attributes->>'product_id') ~ '^[0-9]+$'
        OR (s.raw_attributes->>'ozon_product_id') ~ '^[0-9]+$'
      )
)
SELECT
    MIN(metric_date)::date AS min_date,
    MAX(metric_date)::date AS max_date
FROM source_dates
`

type GetDailySKUMetricSourceDateBoundsBySellerAccountIDRow struct {
	MinDate pgtype.Date
	MaxDate pgtype.Date
}

func (q *Queries) GetDailySKUMetricSourceDateBoundsBySellerAccountID(ctx context.Context, sellerAccountID int64) (GetDailySKUMetricSourceDateBoundsBySellerAccountIDRow, error) {
	row := q.db.QueryRow(ctx, getDailySKUMetricSourceDateBoundsBySellerAccountID, sellerAccountID)
	var i GetDailySKUMetricSourceDateBoundsBySellerAccountIDRow
	err := row.Scan(&i.MinDate, &i.MaxDate)
	return i, err
}

const listCurrentStockBySellerAccountAndProduct = `-- name: ListCurrentStockBySellerAccountAndProduct :many
WITH latest_stock_per_warehouse AS (
    SELECT DISTINCT ON (st.product_external_id, st.warehouse_external_id)
        st.product_external_id,
        st.warehouse_external_id,
        st.quantity_available,
        st.snapshot_at
    FROM stocks st
    WHERE st.seller_account_id = $1
      AND st.product_external_id ~ '^[0-9]+$'
    ORDER BY
        st.product_external_id,
        st.warehouse_external_id,
        st.snapshot_at DESC NULLS LAST,
        st.id DESC
)
SELECT
    product_external_id::bigint AS ozon_product_id,
    COALESCE(SUM(quantity_available), 0)::integer AS stock_available
FROM latest_stock_per_warehouse
GROUP BY product_external_id
ORDER BY product_external_id::bigint
`

type ListCurrentStockBySellerAccountAndProductRow struct {
	OzonProductID  int64
	StockAvailable int32
}

func (q *Queries) ListCurrentStockBySellerAccountAndProduct(ctx context.Context, sellerAccountID int64) ([]ListCurrentStockBySellerAccountAndProductRow, error) {
	rows, err := q.db.Query(ctx, listCurrentStockBySellerAccountAndProduct, sellerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentStockBySellerAccountAndProductRow
	for rows.Next() {
		var i ListCurrentStockBySellerAccountAndProductRow
		if err := rows.Scan(&i.OzonProductID, &i.StockAvailable); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailySKUMetricsBySellerAndDateRange = `-- name: ListDailySKUMetricsBySellerAndDateRange :many
SELECT id, seller_account_id, metric_date, ozon_product_id, offer_id, sku, product_name, revenue, orders_count, stock_available, days_of_cover, created_at, updated_at
FROM daily_sku_metrics
WHERE seller_account_id = $1
  AND metric_date >= $2
  AND metric_date <= $3
ORDER BY metric_date ASC, ozon_product_id ASC
`

type ListDailySKUMetricsBySellerAndDateRangeParams struct {
	SellerAccountID int64
	MetricDate      pgtype.Date
	MetricDate_2    pgtype.Date
}

func (q *Queries) ListDailySKUMetricsBySellerAndDateRange(ctx context.Context, arg ListDailySKUMetricsBySellerAndDateRangeParams) ([]DailySkuMetric, error) {
	rows, err := q.db.Query(ctx, listDailySKUMetricsBySellerAndDateRange, arg.SellerAccountID, arg.MetricDate, arg.MetricDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailySkuMetric
	for rows.Next() {
		var i DailySkuMetric
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.MetricDate,
			&i.OzonProductID,
			&i.OfferID,
			&i.Sku,
			&i.ProductName,
			&i.Revenue,
			&i.OrdersCount,
			&i.StockAvailable,
			&i.DaysOfCover,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailySKUSourcesBySellerAndDateRange = `-- name: ListDailySKUSourcesBySellerAndDateRange :many
WITH sales_by_sku_day AS (
    SELECT
        s.sale_date::date AS metric_date,
        COALESCE(
            NULLIF(s.raw_attributes->>'product_id', ''),
            NULLIF(s.raw_attributes->>'ozon_product_id', '')
        )::bigint AS ozon_product_id,
        COALESCE(SUM(s.amount), 0)::numeric(18,2) AS revenue,
        COUNT(*)::integer AS orders_count
    FROM sales s
    WHERE s.seller_account_id = $1
      AND s.sale_date IS NOT NULL
      AND s.sale_date::date >= $2::date
      AND s.sale_date::date <= $3::date
      AND (
        (s.raw_attributes->>'product_id') ~ '^[0-9]+$'
        OR (s.raw_attributes->>'ozon_product_id') ~ '^[0-9]+$'
      )
    GROUP BY
        s.sale_date::date,
        COALESCE(
            NULLIF(s.raw_attributes->>'product_id', ''),
            NULLIF(s.raw_attributes->>'ozon_product_id', '')
        )::bigint
),
stock_rows_for_end_date AS (
    SELECT
        $3::date AS metric_date,
        p.ozon_product_id,
        0::numeric(18,2) AS revenue,
        0::integer AS orders_count
    FROM products p
    WHERE p.seller_account_id = $1
),
all_rows AS (
    SELECT metric_date, ozon_product_id, revenue, orders_count FROM sales_by_sku_day
    UNION
    SELECT metric_date, ozon_product_id, revenue, orders_count FROM stock_rows_for_end_date
)
SELECT
    r.metric_date,
    r.ozon_product_id,
    p.offer_id,
    p.sku,
    p.name AS product_name,
    COALESCE(SUM(r.revenue), 0)::numeric(18,2) AS revenue,
    COALESCE(SUM(r.orders_count), 0)::integer AS orders_count
FROM all_rows r
LEFT JOIN products p
    ON p.seller_account_id = $1
   AND p.ozon_product_id = r.ozon_product_id
GROUP BY
    r.metric_date,
    r.ozon_product_id,
    p.offer_id,
    p.sku,
    p.name
ORDER BY r.metric_date ASC, r.ozon_product_id ASC
`

type ListDailySKUSourcesBySellerAndDateRangeParams struct {
	SellerAccountID int64
	Column2         pgtype.Date
	Column3         pgtype.Date
}

type ListDailySKUSourcesBySellerAndDateRangeRow struct {
	MetricDate    pgtype.Date
	OzonProductID int64
	OfferID       pgtype.Text
	Sku           pgtype.Int8
	ProductName   pgtype.Text
	Revenue       pgtype.Numeric
	OrdersCount   int32
}

func (q *Queries) ListDailySKUSourcesBySellerAndDateRange(ctx context.Context, arg ListDailySKUSourcesBySellerAndDateRangeParams) ([]ListDailySKUSourcesBySellerAndDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listDailySKUSourcesBySellerAndDateRange, arg.SellerAccountID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailySKUSourcesBySellerAndDateRangeRow
	for rows.Next() {
		var i ListDailySKUSourcesBySellerAndDateRangeRow
		if err := rows.Scan(
			&i.MetricDate,
			&i.OzonProductID,
			&i.OfferID,
			&i.Sku,
			&i.ProductName,
			&i.Revenue,
			&i.OrdersCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailySKUMetric = `-- name: UpsertDailySKUMetric :one
INSERT INTO daily_sku_metrics (
    seller_account_id,
    metric_date,
    ozon_product_id,
    offer_id,
    sku,
    product_name,
    revenue,
    orders_count,
    stock_available,
    days_of_cover,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW()
)
ON CONFLICT (seller_account_id, metric_date, ozon_product_id)
DO UPDATE SET
    offer_id = EXCLUDED.offer_id,
    sku = EXCLUDED.sku,
    product_name = EXCLUDED.product_name,
    revenue = EXCLUDED.revenue,
    orders_count = EXCLUDED.orders_count,
    stock_available = EXCLUDED.stock_available,
    days_of_cover = EXCLUDED.days_of_cover,
    updated_at = NOW()
RETURNING id, seller_account_id, metric_date, ozon_product_id, offer_id, sku, product_name, revenue, orders_count, stock_available, days_of_cover, created_at, updated_at
`

type UpsertDailySKUMetricParams struct {
	SellerAccountID int64
	MetricDate      pgtype.Date
	OzonProductID   int64
	OfferID         pgtype.Text
	Sku             pgtype.Int8
	ProductName     pgtype.Text
	Revenue         pgtype.Numeric
	OrdersCount     int32
	StockAvailable  int32
	DaysOfCover     pgtype.Numeric
}

func (q *Queries) UpsertDailySKUMetric(ctx context.Context, arg UpsertDailySKUMetricParams) (DailySkuMetric, error) {
	row := q.db.QueryRow(ctx, upsertDailySKUMetric,
		arg.SellerAccountID,
		arg.MetricDate,
		arg.OzonProductID,
		arg.OfferID,
		arg.Sku,
		arg.ProductName,
		arg.Revenue,
		arg.OrdersCount,
		arg.StockAvailable,
		arg.DaysOfCover,
	)
	var i DailySkuMetric
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.MetricDate,
		&i.OzonProductID,
		&i.OfferID,
		&i.Sku,
		&i.ProductName,
		&i.Revenue,
		&i.OrdersCount,
		&i.StockAvailable,
		&i.DaysOfCover,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
