// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: import_jobs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countImportJobsSummaryBySyncJobID = `-- name: CountImportJobsSummaryBySyncJobID :one
SELECT
    COUNT(*)::bigint AS total_count,
    COUNT(*) FILTER (WHERE status IN ('pending', 'fetching', 'importing'))::bigint AS active_count,
    COUNT(*) FILTER (WHERE status = 'failed')::bigint AS failed_count,
    COUNT(*) FILTER (WHERE status = 'completed')::bigint AS completed_count
FROM import_jobs
WHERE sync_job_id = $1
`

type CountImportJobsSummaryBySyncJobIDRow struct {
	TotalCount     int64
	ActiveCount    int64
	FailedCount    int64
	CompletedCount int64
}

func (q *Queries) CountImportJobsSummaryBySyncJobID(ctx context.Context, syncJobID int64) (CountImportJobsSummaryBySyncJobIDRow, error) {
	row := q.db.QueryRow(ctx, countImportJobsSummaryBySyncJobID, syncJobID)
	var i CountImportJobsSummaryBySyncJobIDRow
	err := row.Scan(
		&i.TotalCount,
		&i.ActiveCount,
		&i.FailedCount,
		&i.CompletedCount,
	)
	return i, err
}

const createImportJob = `-- name: CreateImportJob :one
INSERT INTO import_jobs (
    seller_account_id,
    sync_job_id,
    domain,
    status,
    source_cursor,
    records_received,
    records_imported,
    records_failed,
    started_at,
    finished_at,
    error_message,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW()
)
RETURNING id, seller_account_id, sync_job_id, domain, status, source_cursor, records_received, records_imported, records_failed, started_at, finished_at, error_message, created_at
`

type CreateImportJobParams struct {
	SellerAccountID int64
	SyncJobID       int64
	Domain          string
	Status          string
	SourceCursor    pgtype.Text
	RecordsReceived int32
	RecordsImported int32
	RecordsFailed   int32
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	ErrorMessage    pgtype.Text
}

func (q *Queries) CreateImportJob(ctx context.Context, arg CreateImportJobParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, createImportJob,
		arg.SellerAccountID,
		arg.SyncJobID,
		arg.Domain,
		arg.Status,
		arg.SourceCursor,
		arg.RecordsReceived,
		arg.RecordsImported,
		arg.RecordsFailed,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ErrorMessage,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.SyncJobID,
		&i.Domain,
		&i.Status,
		&i.SourceCursor,
		&i.RecordsReceived,
		&i.RecordsImported,
		&i.RecordsFailed,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getImportJobByID = `-- name: GetImportJobByID :one
SELECT id, seller_account_id, sync_job_id, domain, status, source_cursor, records_received, records_imported, records_failed, started_at, finished_at, error_message, created_at
FROM import_jobs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetImportJobByID(ctx context.Context, id int64) (ImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJobByID, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.SyncJobID,
		&i.Domain,
		&i.Status,
		&i.SourceCursor,
		&i.RecordsReceived,
		&i.RecordsImported,
		&i.RecordsFailed,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listImportJobsBySyncJobID = `-- name: ListImportJobsBySyncJobID :many
SELECT id, seller_account_id, sync_job_id, domain, status, source_cursor, records_received, records_imported, records_failed, started_at, finished_at, error_message, created_at
FROM import_jobs
WHERE sync_job_id = $1
ORDER BY id ASC
`

func (q *Queries) ListImportJobsBySyncJobID(ctx context.Context, syncJobID int64) ([]ImportJob, error) {
	rows, err := q.db.Query(ctx, listImportJobsBySyncJobID, syncJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportJob
	for rows.Next() {
		var i ImportJob
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.SyncJobID,
			&i.Domain,
			&i.Status,
			&i.SourceCursor,
			&i.RecordsReceived,
			&i.RecordsImported,
			&i.RecordsFailed,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestImportJobsBySellerAccountID = `-- name: ListLatestImportJobsBySellerAccountID :many
SELECT DISTINCT ON (domain) id, seller_account_id, sync_job_id, domain, status, source_cursor, records_received, records_imported, records_failed, started_at, finished_at, error_message, created_at
FROM import_jobs
WHERE seller_account_id = $1
ORDER BY domain, created_at DESC, id DESC
`

func (q *Queries) ListLatestImportJobsBySellerAccountID(ctx context.Context, sellerAccountID int64) ([]ImportJob, error) {
	rows, err := q.db.Query(ctx, listLatestImportJobsBySellerAccountID, sellerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportJob
	for rows.Next() {
		var i ImportJob
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.SyncJobID,
			&i.Domain,
			&i.Status,
			&i.SourceCursor,
			&i.RecordsReceived,
			&i.RecordsImported,
			&i.RecordsFailed,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImportJobToCompleted = `-- name: UpdateImportJobToCompleted :one
UPDATE import_jobs
SET
    status = 'completed',
    finished_at = NOW(),
    records_received = $2,
    records_imported = $3,
    records_failed = $4,
    error_message = NULL
WHERE id = $1
RETURNING id, seller_account_id, sync_job_id, domain, status, source_cursor, records_received, records_imported, records_failed, started_at, finished_at, error_message, created_at
`

type UpdateImportJobToCompletedParams struct {
	ID              int64
	RecordsReceived int32
	RecordsImported int32
	RecordsFailed   int32
}

func (q *Queries) UpdateImportJobToCompleted(ctx context.Context, arg UpdateImportJobToCompletedParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, updateImportJobToCompleted,
		arg.ID,
		arg.RecordsReceived,
		arg.RecordsImported,
		arg.RecordsFailed,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.SyncJobID,
		&i.Domain,
		&i.Status,
		&i.SourceCursor,
		&i.RecordsReceived,
		&i.RecordsImported,
		&i.RecordsFailed,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const updateImportJobToFailed = `-- name: UpdateImportJobToFailed :one
UPDATE import_jobs
SET
    status = 'failed',
    finished_at = NOW(),
    error_message = $2
WHERE id = $1
RETURNING id, seller_account_id, sync_job_id, domain, status, source_cursor, records_received, records_imported, records_failed, started_at, finished_at, error_message, created_at
`

type UpdateImportJobToFailedParams struct {
	ID           int64
	ErrorMessage pgtype.Text
}

func (q *Queries) UpdateImportJobToFailed(ctx context.Context, arg UpdateImportJobToFailedParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, updateImportJobToFailed, arg.ID, arg.ErrorMessage)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.SyncJobID,
		&i.Domain,
		&i.Status,
		&i.SourceCursor,
		&i.RecordsReceived,
		&i.RecordsImported,
		&i.RecordsFailed,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const updateImportJobToFetching = `-- name: UpdateImportJobToFetching :one
UPDATE import_jobs
SET
    status = 'fetching',
    started_at = NOW(),
    error_message = NULL
WHERE id = $1
RETURNING id, seller_account_id, sync_job_id, domain, status, source_cursor, records_received, records_imported, records_failed, started_at, finished_at, error_message, created_at
`

func (q *Queries) UpdateImportJobToFetching(ctx context.Context, id int64) (ImportJob, error) {
	row := q.db.QueryRow(ctx, updateImportJobToFetching, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.SyncJobID,
		&i.Domain,
		&i.Status,
		&i.SourceCursor,
		&i.RecordsReceived,
		&i.RecordsImported,
		&i.RecordsFailed,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const updateImportJobToImporting = `-- name: UpdateImportJobToImporting :one
UPDATE import_jobs
SET
    status = 'importing'
WHERE id = $1
RETURNING id, seller_account_id, sync_job_id, domain, status, source_cursor, records_received, records_imported, records_failed, started_at, finished_at, error_message, created_at
`

func (q *Queries) UpdateImportJobToImporting(ctx context.Context, id int64) (ImportJob, error) {
	row := q.db.QueryRow(ctx, updateImportJobToImporting, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.SyncJobID,
		&i.Domain,
		&i.Status,
		&i.SourceCursor,
		&i.RecordsReceived,
		&i.RecordsImported,
		&i.RecordsFailed,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}
