// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdCampaign struct {
	ID                 int64
	SellerAccountID    int64
	CampaignExternalID int64
	CampaignName       string
	CampaignType       pgtype.Text
	PlacementType      pgtype.Text
	Status             pgtype.Text
	BudgetAmount       pgtype.Numeric
	BudgetDaily        pgtype.Numeric
	RawAttributes      []byte
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type AdCampaignSku struct {
	ID                 int64
	SellerAccountID    int64
	CampaignExternalID int64
	OzonProductID      int64
	OfferID            pgtype.Text
	Sku                pgtype.Int8
	IsActive           bool
	Status             pgtype.Text
	RawAttributes      []byte
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type AdMetricsDaily struct {
	ID                 int64
	SellerAccountID    int64
	CampaignExternalID int64
	MetricDate         pgtype.Date
	Impressions        int64
	Clicks             int64
	Spend              pgtype.Numeric
	OrdersCount        int32
	Revenue            pgtype.Numeric
	RawAttributes      []byte
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type Alert struct {
	ID              int64
	SellerAccountID int64
	AlertType       string
	AlertGroup      string
	EntityType      string
	EntityID        pgtype.Text
	EntitySku       pgtype.Int8
	EntityOfferID   pgtype.Text
	Title           string
	Message         string
	Severity        string
	Urgency         string
	Status          string
	EvidencePayload []byte
	Fingerprint     string
	FirstSeenAt     pgtype.Timestamptz
	LastSeenAt      pgtype.Timestamptz
	ResolvedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type AlertRun struct {
	ID               int64
	SellerAccountID  int64
	RunType          string
	Status           string
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	SalesAlertsCount int32
	StockAlertsCount int32
	AdAlertsCount    int32
	PriceAlertsCount int32
	TotalAlertsCount int32
	ErrorMessage     pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

type ChatFeedback struct {
	ID              int64
	SessionID       int64
	MessageID       int64
	SellerAccountID int64
	Rating          string
	Comment         pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

type ChatMessage struct {
	ID              int64
	SessionID       int64
	SellerAccountID int64
	Role            string
	Content         string
	MessageType     string
	CreatedAt       pgtype.Timestamptz
}

type ChatSession struct {
	ID              int64
	SellerAccountID int64
	UserID          pgtype.Int8
	Title           string
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	LastMessageAt   pgtype.Timestamptz
}

type ChatTrace struct {
	ID                       int64
	SessionID                int64
	UserMessageID            pgtype.Int8
	AssistantMessageID       pgtype.Int8
	SellerAccountID          int64
	PlannerPromptVersion     string
	AnswerPromptVersion      string
	PlannerModel             string
	AnswerModel              string
	DetectedIntent           pgtype.Text
	ToolPlanPayload          []byte
	ValidatedToolPlanPayload []byte
	ToolResultsPayload       []byte
	FactContextPayload       []byte
	RawPlannerResponse       []byte
	RawAnswerResponse        []byte
	AnswerValidationPayload  []byte
	InputTokens              int32
	OutputTokens             int32
	EstimatedCost            pgtype.Numeric
	Status                   string
	ErrorMessage             pgtype.Text
	StartedAt                pgtype.Timestamptz
	FinishedAt               pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
}

type DailyAccountMetric struct {
	ID              int64
	SellerAccountID int64
	MetricDate      pgtype.Date
	Revenue         pgtype.Numeric
	OrdersCount     int32
	ReturnsCount    int32
	CancelCount     int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type DailySkuMetric struct {
	ID              int64
	SellerAccountID int64
	MetricDate      pgtype.Date
	OzonProductID   int64
	OfferID         pgtype.Text
	Sku             pgtype.Int8
	ProductName     pgtype.Text
	Revenue         pgtype.Numeric
	OrdersCount     int32
	StockAvailable  int32
	DaysOfCover     pgtype.Numeric
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ImportJob struct {
	ID              int64
	SellerAccountID int64
	SyncJobID       int64
	Domain          string
	Status          string
	SourceCursor    pgtype.Text
	RecordsReceived int32
	RecordsImported int32
	RecordsFailed   int32
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	ErrorMessage    pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

type InternalMetum struct {
	Key       string
	Value     string
	UpdatedAt pgtype.Timestamptz
}

type Order struct {
	ID                int64
	SellerAccountID   int64
	OzonOrderID       string
	PostingNumber     pgtype.Text
	Status            pgtype.Text
	CreatedAtSource   pgtype.Timestamptz
	ProcessedAtSource pgtype.Timestamptz
	TotalAmount       pgtype.Numeric
	CurrencyCode      pgtype.Text
	RawAttributes     []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type OzonConnection struct {
	ID                int64
	SellerAccountID   int64
	ClientIDEncrypted string
	ApiKeyEncrypted   string
	Status            string
	LastCheckAt       pgtype.Timestamptz
	LastCheckResult   pgtype.Text
	LastError         pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type PricingConstraintRule struct {
	ID                     int64
	SellerAccountID        int64
	ScopeType              string
	ScopeTargetID          pgtype.Int8
	ScopeTargetCode        pgtype.Text
	MinPrice               pgtype.Numeric
	MaxPrice               pgtype.Numeric
	ReferenceMarginPercent pgtype.Numeric
	ReferencePrice         pgtype.Numeric
	ImpliedCost            pgtype.Numeric
	IsActive               bool
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	ScopeTargetKind        pgtype.Text
}

type Product struct {
	ID                    int64
	SellerAccountID       int64
	OzonProductID         int64
	OfferID               pgtype.Text
	Sku                   pgtype.Int8
	Name                  string
	Status                pgtype.Text
	IsArchived            bool
	RawAttributes         []byte
	SourceUpdatedAt       pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	ReferencePrice        pgtype.Numeric
	OldPrice              pgtype.Numeric
	OzonMinPrice          pgtype.Numeric
	DescriptionCategoryID pgtype.Int8
}

type RawPayload struct {
	ID               int64
	SellerAccountID  int64
	ImportJobID      int64
	Domain           string
	Source           string
	RequestKey       pgtype.Text
	StorageBucket    string
	StorageObjectKey string
	PayloadHash      string
	ReceivedAt       pgtype.Timestamptz
}

type Recommendation struct {
	ID                       int64
	SellerAccountID          int64
	Source                   string
	RecommendationType       string
	Horizon                  string
	EntityType               string
	EntityID                 pgtype.Text
	EntitySku                pgtype.Int8
	EntityOfferID            pgtype.Text
	Title                    string
	WhatHappened             string
	WhyItMatters             string
	RecommendedAction        string
	ExpectedEffect           pgtype.Text
	PriorityScore            pgtype.Numeric
	PriorityLevel            string
	Urgency                  string
	ConfidenceLevel          string
	Status                   string
	SupportingMetricsPayload []byte
	ConstraintsPayload       []byte
	AiModel                  pgtype.Text
	AiPromptVersion          pgtype.Text
	RawAiResponse            []byte
	Fingerprint              string
	FirstSeenAt              pgtype.Timestamptz
	LastSeenAt               pgtype.Timestamptz
	AcceptedAt               pgtype.Timestamptz
	DismissedAt              pgtype.Timestamptz
	ResolvedAt               pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
}

type RecommendationAlertLink struct {
	RecommendationID int64
	AlertID          int64
	SellerAccountID  int64
	LinkType         string
	CreatedAt        pgtype.Timestamptz
}

type RecommendationRun struct {
	ID                            int64
	SellerAccountID               int64
	RunType                       string
	Status                        string
	AsOfDate                      pgtype.Date
	AiModel                       pgtype.Text
	AiPromptVersion               pgtype.Text
	InputTokens                   int32
	OutputTokens                  int32
	EstimatedCost                 pgtype.Numeric
	GeneratedRecommendationsCount int32
	AcceptedRecommendationsCount  int32
	ErrorMessage                  pgtype.Text
	StartedAt                     pgtype.Timestamptz
	FinishedAt                    pgtype.Timestamptz
	CreatedAt                     pgtype.Timestamptz
}

type Sale struct {
	ID              int64
	SellerAccountID int64
	OzonSaleID      string
	OzonOrderID     pgtype.Text
	PostingNumber   pgtype.Text
	Quantity        pgtype.Int4
	Amount          pgtype.Numeric
	CurrencyCode    pgtype.Text
	SaleDate        pgtype.Timestamptz
	RawAttributes   []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type SellerAccount struct {
	ID        int64
	UserID    int64
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	ID        int64
	UserID    int64
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type SkuEffectiveConstraint struct {
	SellerAccountID        int64
	OzonProductID          int64
	Sku                    pgtype.Int8
	OfferID                pgtype.Text
	ResolvedFromScopeType  string
	RuleID                 int64
	EffectiveMinPrice      pgtype.Numeric
	EffectiveMaxPrice      pgtype.Numeric
	ReferencePrice         pgtype.Numeric
	ReferenceMarginPercent pgtype.Numeric
	ImpliedCost            pgtype.Numeric
	ComputedAt             pgtype.Timestamptz
}

type Stock struct {
	ID                  int64
	SellerAccountID     int64
	ProductExternalID   string
	WarehouseExternalID string
	QuantityTotal       pgtype.Int4
	QuantityReserved    pgtype.Int4
	QuantityAvailable   pgtype.Int4
	SnapshotAt          pgtype.Timestamptz
	RawAttributes       []byte
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type SyncCursor struct {
	ID              int64
	SellerAccountID int64
	Domain          string
	CursorType      string
	CursorValue     pgtype.Text
	UpdatedAt       pgtype.Timestamptz
}

type SyncJob struct {
	ID              int64
	SellerAccountID int64
	Type            string
	Status          string
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	ErrorMessage    pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
