// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InternalMetum struct {
	Key       string
	Value     string
	UpdatedAt pgtype.Timestamptz
}

type OzonConnection struct {
	ID                int64
	SellerAccountID   int64
	ClientIDEncrypted string
	ApiKeyEncrypted   string
	Status            string
	LastCheckAt       pgtype.Timestamptz
	LastCheckResult   pgtype.Text
	LastError         pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type SellerAccount struct {
	ID        int64
	UserID    int64
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	ID        int64
	UserID    int64
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type SyncJob struct {
	ID              int64
	SellerAccountID int64
	Type            string
	Status          string
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	ErrorMessage    pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
