// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrdersBySellerAccountID = `-- name: CountOrdersBySellerAccountID :one
SELECT COUNT(*)
FROM orders
WHERE seller_account_id = $1
`

func (q *Queries) CountOrdersBySellerAccountID(ctx context.Context, sellerAccountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersBySellerAccountID, sellerAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listOrdersBySellerAccountID = `-- name: ListOrdersBySellerAccountID :many
SELECT id, seller_account_id, ozon_order_id, posting_number, status, created_at_source, processed_at_source, total_amount, currency_code, raw_attributes, created_at, updated_at
FROM orders
WHERE seller_account_id = $1
ORDER BY id ASC
`

func (q *Queries) ListOrdersBySellerAccountID(ctx context.Context, sellerAccountID int64) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersBySellerAccountID, sellerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.OzonOrderID,
			&i.PostingNumber,
			&i.Status,
			&i.CreatedAtSource,
			&i.ProcessedAtSource,
			&i.TotalAmount,
			&i.CurrencyCode,
			&i.RawAttributes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOrder = `-- name: UpsertOrder :one
INSERT INTO orders (
    seller_account_id,
    ozon_order_id,
    posting_number,
    status,
    created_at_source,
    processed_at_source,
    total_amount,
    currency_code,
    raw_attributes,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW()
)
ON CONFLICT (seller_account_id, ozon_order_id)
DO UPDATE SET
    posting_number = EXCLUDED.posting_number,
    status = EXCLUDED.status,
    created_at_source = EXCLUDED.created_at_source,
    processed_at_source = EXCLUDED.processed_at_source,
    total_amount = EXCLUDED.total_amount,
    currency_code = EXCLUDED.currency_code,
    raw_attributes = EXCLUDED.raw_attributes,
    updated_at = NOW()
RETURNING id, seller_account_id, ozon_order_id, posting_number, status, created_at_source, processed_at_source, total_amount, currency_code, raw_attributes, created_at, updated_at
`

type UpsertOrderParams struct {
	SellerAccountID   int64
	OzonOrderID       string
	PostingNumber     pgtype.Text
	Status            pgtype.Text
	CreatedAtSource   pgtype.Timestamptz
	ProcessedAtSource pgtype.Timestamptz
	TotalAmount       pgtype.Numeric
	CurrencyCode      pgtype.Text
	RawAttributes     []byte
}

func (q *Queries) UpsertOrder(ctx context.Context, arg UpsertOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, upsertOrder,
		arg.SellerAccountID,
		arg.OzonOrderID,
		arg.PostingNumber,
		arg.Status,
		arg.CreatedAtSource,
		arg.ProcessedAtSource,
		arg.TotalAmount,
		arg.CurrencyCode,
		arg.RawAttributes,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.OzonOrderID,
		&i.PostingNumber,
		&i.Status,
		&i.CreatedAtSource,
		&i.ProcessedAtSource,
		&i.TotalAmount,
		&i.CurrencyCode,
		&i.RawAttributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
