// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ozon_connections.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearOzonPerformanceBearerToken = `-- name: ClearOzonPerformanceBearerToken :one
UPDATE ozon_connections
SET
    performance_token_encrypted = NULL,
    performance_status = 'not_configured',
    performance_last_check_at = NULL,
    performance_last_check_result = NULL,
    performance_last_error = NULL,
    updated_at = NOW()
WHERE seller_account_id = $1
RETURNING id, seller_account_id, client_id_encrypted, api_key_encrypted, status, last_check_at, last_check_result, last_error, created_at, updated_at, performance_token_encrypted, performance_status, performance_last_check_at, performance_last_check_result, performance_last_error
`

func (q *Queries) ClearOzonPerformanceBearerToken(ctx context.Context, sellerAccountID int64) (OzonConnection, error) {
	row := q.db.QueryRow(ctx, clearOzonPerformanceBearerToken, sellerAccountID)
	var i OzonConnection
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.ClientIDEncrypted,
		&i.ApiKeyEncrypted,
		&i.Status,
		&i.LastCheckAt,
		&i.LastCheckResult,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PerformanceTokenEncrypted,
		&i.PerformanceStatus,
		&i.PerformanceLastCheckAt,
		&i.PerformanceLastCheckResult,
		&i.PerformanceLastError,
	)
	return i, err
}

const createOzonConnection = `-- name: CreateOzonConnection :one
INSERT INTO ozon_connections (
    seller_account_id,
    client_id_encrypted,
    api_key_encrypted,
    status,
    last_check_at,
    last_check_result,
    last_error
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, seller_account_id, client_id_encrypted, api_key_encrypted, status, last_check_at, last_check_result, last_error, created_at, updated_at, performance_token_encrypted, performance_status, performance_last_check_at, performance_last_check_result, performance_last_error
`

type CreateOzonConnectionParams struct {
	SellerAccountID   int64
	ClientIDEncrypted string
	ApiKeyEncrypted   string
	Status            string
	LastCheckAt       pgtype.Timestamptz
	LastCheckResult   pgtype.Text
	LastError         pgtype.Text
}

func (q *Queries) CreateOzonConnection(ctx context.Context, arg CreateOzonConnectionParams) (OzonConnection, error) {
	row := q.db.QueryRow(ctx, createOzonConnection,
		arg.SellerAccountID,
		arg.ClientIDEncrypted,
		arg.ApiKeyEncrypted,
		arg.Status,
		arg.LastCheckAt,
		arg.LastCheckResult,
		arg.LastError,
	)
	var i OzonConnection
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.ClientIDEncrypted,
		&i.ApiKeyEncrypted,
		&i.Status,
		&i.LastCheckAt,
		&i.LastCheckResult,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PerformanceTokenEncrypted,
		&i.PerformanceStatus,
		&i.PerformanceLastCheckAt,
		&i.PerformanceLastCheckResult,
		&i.PerformanceLastError,
	)
	return i, err
}

const getOzonConnectionBySellerAccountID = `-- name: GetOzonConnectionBySellerAccountID :one
SELECT id, seller_account_id, client_id_encrypted, api_key_encrypted, status, last_check_at, last_check_result, last_error, created_at, updated_at, performance_token_encrypted, performance_status, performance_last_check_at, performance_last_check_result, performance_last_error FROM ozon_connections
WHERE seller_account_id = $1
LIMIT 1
`

func (q *Queries) GetOzonConnectionBySellerAccountID(ctx context.Context, sellerAccountID int64) (OzonConnection, error) {
	row := q.db.QueryRow(ctx, getOzonConnectionBySellerAccountID, sellerAccountID)
	var i OzonConnection
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.ClientIDEncrypted,
		&i.ApiKeyEncrypted,
		&i.Status,
		&i.LastCheckAt,
		&i.LastCheckResult,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PerformanceTokenEncrypted,
		&i.PerformanceStatus,
		&i.PerformanceLastCheckAt,
		&i.PerformanceLastCheckResult,
		&i.PerformanceLastError,
	)
	return i, err
}

const updateOzonConnectionCheckResult = `-- name: UpdateOzonConnectionCheckResult :one
UPDATE ozon_connections
SET
    status = $2,
    last_check_at = $3,
    last_check_result = $4,
    last_error = $5,
    updated_at = NOW()
WHERE seller_account_id = $1
RETURNING id, seller_account_id, client_id_encrypted, api_key_encrypted, status, last_check_at, last_check_result, last_error, created_at, updated_at, performance_token_encrypted, performance_status, performance_last_check_at, performance_last_check_result, performance_last_error
`

type UpdateOzonConnectionCheckResultParams struct {
	SellerAccountID int64
	Status          string
	LastCheckAt     pgtype.Timestamptz
	LastCheckResult pgtype.Text
	LastError       pgtype.Text
}

func (q *Queries) UpdateOzonConnectionCheckResult(ctx context.Context, arg UpdateOzonConnectionCheckResultParams) (OzonConnection, error) {
	row := q.db.QueryRow(ctx, updateOzonConnectionCheckResult,
		arg.SellerAccountID,
		arg.Status,
		arg.LastCheckAt,
		arg.LastCheckResult,
		arg.LastError,
	)
	var i OzonConnection
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.ClientIDEncrypted,
		&i.ApiKeyEncrypted,
		&i.Status,
		&i.LastCheckAt,
		&i.LastCheckResult,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PerformanceTokenEncrypted,
		&i.PerformanceStatus,
		&i.PerformanceLastCheckAt,
		&i.PerformanceLastCheckResult,
		&i.PerformanceLastError,
	)
	return i, err
}

const updateOzonConnectionCredentials = `-- name: UpdateOzonConnectionCredentials :one
UPDATE ozon_connections
SET
    client_id_encrypted = $2,
    api_key_encrypted = $3,
    status = $4,
    last_check_at = $5,
    last_check_result = $6,
    last_error = $7,
    updated_at = NOW()
WHERE seller_account_id = $1
RETURNING id, seller_account_id, client_id_encrypted, api_key_encrypted, status, last_check_at, last_check_result, last_error, created_at, updated_at, performance_token_encrypted, performance_status, performance_last_check_at, performance_last_check_result, performance_last_error
`

type UpdateOzonConnectionCredentialsParams struct {
	SellerAccountID   int64
	ClientIDEncrypted string
	ApiKeyEncrypted   string
	Status            string
	LastCheckAt       pgtype.Timestamptz
	LastCheckResult   pgtype.Text
	LastError         pgtype.Text
}

func (q *Queries) UpdateOzonConnectionCredentials(ctx context.Context, arg UpdateOzonConnectionCredentialsParams) (OzonConnection, error) {
	row := q.db.QueryRow(ctx, updateOzonConnectionCredentials,
		arg.SellerAccountID,
		arg.ClientIDEncrypted,
		arg.ApiKeyEncrypted,
		arg.Status,
		arg.LastCheckAt,
		arg.LastCheckResult,
		arg.LastError,
	)
	var i OzonConnection
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.ClientIDEncrypted,
		&i.ApiKeyEncrypted,
		&i.Status,
		&i.LastCheckAt,
		&i.LastCheckResult,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PerformanceTokenEncrypted,
		&i.PerformanceStatus,
		&i.PerformanceLastCheckAt,
		&i.PerformanceLastCheckResult,
		&i.PerformanceLastError,
	)
	return i, err
}

const updateOzonConnectionStatus = `-- name: UpdateOzonConnectionStatus :one
UPDATE ozon_connections
SET
    status = $2,
    updated_at = NOW()
WHERE seller_account_id = $1
RETURNING id, seller_account_id, client_id_encrypted, api_key_encrypted, status, last_check_at, last_check_result, last_error, created_at, updated_at, performance_token_encrypted, performance_status, performance_last_check_at, performance_last_check_result, performance_last_error
`

type UpdateOzonConnectionStatusParams struct {
	SellerAccountID int64
	Status          string
}

func (q *Queries) UpdateOzonConnectionStatus(ctx context.Context, arg UpdateOzonConnectionStatusParams) (OzonConnection, error) {
	row := q.db.QueryRow(ctx, updateOzonConnectionStatus, arg.SellerAccountID, arg.Status)
	var i OzonConnection
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.ClientIDEncrypted,
		&i.ApiKeyEncrypted,
		&i.Status,
		&i.LastCheckAt,
		&i.LastCheckResult,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PerformanceTokenEncrypted,
		&i.PerformanceStatus,
		&i.PerformanceLastCheckAt,
		&i.PerformanceLastCheckResult,
		&i.PerformanceLastError,
	)
	return i, err
}

const updateOzonPerformanceBearerToken = `-- name: UpdateOzonPerformanceBearerToken :one
UPDATE ozon_connections
SET
    performance_token_encrypted = $2,
    performance_status = 'unknown',
    performance_last_check_at = NULL,
    performance_last_check_result = NULL,
    performance_last_error = NULL,
    updated_at = NOW()
WHERE seller_account_id = $1
RETURNING id, seller_account_id, client_id_encrypted, api_key_encrypted, status, last_check_at, last_check_result, last_error, created_at, updated_at, performance_token_encrypted, performance_status, performance_last_check_at, performance_last_check_result, performance_last_error
`

type UpdateOzonPerformanceBearerTokenParams struct {
	SellerAccountID           int64
	PerformanceTokenEncrypted pgtype.Text
}

func (q *Queries) UpdateOzonPerformanceBearerToken(ctx context.Context, arg UpdateOzonPerformanceBearerTokenParams) (OzonConnection, error) {
	row := q.db.QueryRow(ctx, updateOzonPerformanceBearerToken, arg.SellerAccountID, arg.PerformanceTokenEncrypted)
	var i OzonConnection
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.ClientIDEncrypted,
		&i.ApiKeyEncrypted,
		&i.Status,
		&i.LastCheckAt,
		&i.LastCheckResult,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PerformanceTokenEncrypted,
		&i.PerformanceStatus,
		&i.PerformanceLastCheckAt,
		&i.PerformanceLastCheckResult,
		&i.PerformanceLastError,
	)
	return i, err
}

const updateOzonPerformanceCheckResult = `-- name: UpdateOzonPerformanceCheckResult :one
UPDATE ozon_connections
SET
    performance_status = $2,
    performance_last_check_at = $3,
    performance_last_check_result = $4,
    performance_last_error = $5,
    updated_at = NOW()
WHERE seller_account_id = $1
RETURNING id, seller_account_id, client_id_encrypted, api_key_encrypted, status, last_check_at, last_check_result, last_error, created_at, updated_at, performance_token_encrypted, performance_status, performance_last_check_at, performance_last_check_result, performance_last_error
`

type UpdateOzonPerformanceCheckResultParams struct {
	SellerAccountID            int64
	PerformanceStatus          string
	PerformanceLastCheckAt     pgtype.Timestamptz
	PerformanceLastCheckResult pgtype.Text
	PerformanceLastError       pgtype.Text
}

func (q *Queries) UpdateOzonPerformanceCheckResult(ctx context.Context, arg UpdateOzonPerformanceCheckResultParams) (OzonConnection, error) {
	row := q.db.QueryRow(ctx, updateOzonPerformanceCheckResult,
		arg.SellerAccountID,
		arg.PerformanceStatus,
		arg.PerformanceLastCheckAt,
		arg.PerformanceLastCheckResult,
		arg.PerformanceLastError,
	)
	var i OzonConnection
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.ClientIDEncrypted,
		&i.ApiKeyEncrypted,
		&i.Status,
		&i.LastCheckAt,
		&i.LastCheckResult,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PerformanceTokenEncrypted,
		&i.PerformanceStatus,
		&i.PerformanceLastCheckAt,
		&i.PerformanceLastCheckResult,
		&i.PerformanceLastError,
	)
	return i, err
}
