// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ozon_connections.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOzonConnection = `-- name: CreateOzonConnection :one
INSERT INTO ozon_connections (
    seller_account_id,
    client_id_encrypted,
    api_key_encrypted,
    status,
    last_check_at,
    last_check_result,
    last_error
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, seller_account_id, client_id_encrypted, api_key_encrypted, status, last_check_at, last_check_result, last_error, created_at, updated_at
`

type CreateOzonConnectionParams struct {
	SellerAccountID   int64
	ClientIDEncrypted string
	ApiKeyEncrypted   string
	Status            string
	LastCheckAt       pgtype.Timestamptz
	LastCheckResult   pgtype.Text
	LastError         pgtype.Text
}

func (q *Queries) CreateOzonConnection(ctx context.Context, arg CreateOzonConnectionParams) (OzonConnection, error) {
	row := q.db.QueryRow(ctx, createOzonConnection,
		arg.SellerAccountID,
		arg.ClientIDEncrypted,
		arg.ApiKeyEncrypted,
		arg.Status,
		arg.LastCheckAt,
		arg.LastCheckResult,
		arg.LastError,
	)
	var i OzonConnection
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.ClientIDEncrypted,
		&i.ApiKeyEncrypted,
		&i.Status,
		&i.LastCheckAt,
		&i.LastCheckResult,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOzonConnectionBySellerAccountID = `-- name: GetOzonConnectionBySellerAccountID :one
SELECT id, seller_account_id, client_id_encrypted, api_key_encrypted, status, last_check_at, last_check_result, last_error, created_at, updated_at FROM ozon_connections
WHERE seller_account_id = $1
LIMIT 1
`

func (q *Queries) GetOzonConnectionBySellerAccountID(ctx context.Context, sellerAccountID int64) (OzonConnection, error) {
	row := q.db.QueryRow(ctx, getOzonConnectionBySellerAccountID, sellerAccountID)
	var i OzonConnection
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.ClientIDEncrypted,
		&i.ApiKeyEncrypted,
		&i.Status,
		&i.LastCheckAt,
		&i.LastCheckResult,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOzonConnectionCredentials = `-- name: UpdateOzonConnectionCredentials :one
UPDATE ozon_connections
SET
    client_id_encrypted = $2,
    api_key_encrypted = $3,
    status = $4,
    last_check_at = $5,
    last_check_result = $6,
    last_error = $7,
    updated_at = NOW()
WHERE seller_account_id = $1
RETURNING id, seller_account_id, client_id_encrypted, api_key_encrypted, status, last_check_at, last_check_result, last_error, created_at, updated_at
`

type UpdateOzonConnectionCredentialsParams struct {
	SellerAccountID   int64
	ClientIDEncrypted string
	ApiKeyEncrypted   string
	Status            string
	LastCheckAt       pgtype.Timestamptz
	LastCheckResult   pgtype.Text
	LastError         pgtype.Text
}

func (q *Queries) UpdateOzonConnectionCredentials(ctx context.Context, arg UpdateOzonConnectionCredentialsParams) (OzonConnection, error) {
	row := q.db.QueryRow(ctx, updateOzonConnectionCredentials,
		arg.SellerAccountID,
		arg.ClientIDEncrypted,
		arg.ApiKeyEncrypted,
		arg.Status,
		arg.LastCheckAt,
		arg.LastCheckResult,
		arg.LastError,
	)
	var i OzonConnection
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.ClientIDEncrypted,
		&i.ApiKeyEncrypted,
		&i.Status,
		&i.LastCheckAt,
		&i.LastCheckResult,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
