// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pricing_constraints.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPricingConstraintRule = `-- name: CreatePricingConstraintRule :one
INSERT INTO pricing_constraint_rules (
    seller_account_id,
    scope_type,
    scope_target_id,
    scope_target_code,
    min_price,
    max_price,
    reference_margin_percent,
    reference_price,
    implied_cost,
    is_active,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW()
)
RETURNING id, seller_account_id, scope_type, scope_target_id, scope_target_code, min_price, max_price, reference_margin_percent, reference_price, implied_cost, is_active, created_at, updated_at
`

type CreatePricingConstraintRuleParams struct {
	SellerAccountID        int64
	ScopeType              string
	ScopeTargetID          pgtype.Int8
	ScopeTargetCode        pgtype.Text
	MinPrice               pgtype.Numeric
	MaxPrice               pgtype.Numeric
	ReferenceMarginPercent pgtype.Numeric
	ReferencePrice         pgtype.Numeric
	ImpliedCost            pgtype.Numeric
	IsActive               bool
}

func (q *Queries) CreatePricingConstraintRule(ctx context.Context, arg CreatePricingConstraintRuleParams) (PricingConstraintRule, error) {
	row := q.db.QueryRow(ctx, createPricingConstraintRule,
		arg.SellerAccountID,
		arg.ScopeType,
		arg.ScopeTargetID,
		arg.ScopeTargetCode,
		arg.MinPrice,
		arg.MaxPrice,
		arg.ReferenceMarginPercent,
		arg.ReferencePrice,
		arg.ImpliedCost,
		arg.IsActive,
	)
	var i PricingConstraintRule
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.ScopeType,
		&i.ScopeTargetID,
		&i.ScopeTargetCode,
		&i.MinPrice,
		&i.MaxPrice,
		&i.ReferenceMarginPercent,
		&i.ReferencePrice,
		&i.ImpliedCost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSKUEffectiveConstraintsBySellerAccountID = `-- name: DeleteSKUEffectiveConstraintsBySellerAccountID :exec
DELETE FROM sku_effective_constraints
WHERE seller_account_id = $1
`

func (q *Queries) DeleteSKUEffectiveConstraintsBySellerAccountID(ctx context.Context, sellerAccountID int64) error {
	_, err := q.db.Exec(ctx, deleteSKUEffectiveConstraintsBySellerAccountID, sellerAccountID)
	return err
}

const getSKUEffectiveConstraintBySellerAndProduct = `-- name: GetSKUEffectiveConstraintBySellerAndProduct :one
SELECT seller_account_id, ozon_product_id, sku, offer_id, resolved_from_scope_type, rule_id, effective_min_price, effective_max_price, reference_price, reference_margin_percent, implied_cost, computed_at
FROM sku_effective_constraints
WHERE seller_account_id = $1
  AND ozon_product_id = $2
`

type GetSKUEffectiveConstraintBySellerAndProductParams struct {
	SellerAccountID int64
	OzonProductID   int64
}

func (q *Queries) GetSKUEffectiveConstraintBySellerAndProduct(ctx context.Context, arg GetSKUEffectiveConstraintBySellerAndProductParams) (SkuEffectiveConstraint, error) {
	row := q.db.QueryRow(ctx, getSKUEffectiveConstraintBySellerAndProduct, arg.SellerAccountID, arg.OzonProductID)
	var i SkuEffectiveConstraint
	err := row.Scan(
		&i.SellerAccountID,
		&i.OzonProductID,
		&i.Sku,
		&i.OfferID,
		&i.ResolvedFromScopeType,
		&i.RuleID,
		&i.EffectiveMinPrice,
		&i.EffectiveMaxPrice,
		&i.ReferencePrice,
		&i.ReferenceMarginPercent,
		&i.ImpliedCost,
		&i.ComputedAt,
	)
	return i, err
}

const getSKUEffectiveConstraintBySellerAndSKU = `-- name: GetSKUEffectiveConstraintBySellerAndSKU :one
SELECT seller_account_id, ozon_product_id, sku, offer_id, resolved_from_scope_type, rule_id, effective_min_price, effective_max_price, reference_price, reference_margin_percent, implied_cost, computed_at
FROM sku_effective_constraints
WHERE seller_account_id = $1
  AND sku = $2
ORDER BY computed_at DESC
LIMIT 1
`

type GetSKUEffectiveConstraintBySellerAndSKUParams struct {
	SellerAccountID int64
	Sku             pgtype.Int8
}

func (q *Queries) GetSKUEffectiveConstraintBySellerAndSKU(ctx context.Context, arg GetSKUEffectiveConstraintBySellerAndSKUParams) (SkuEffectiveConstraint, error) {
	row := q.db.QueryRow(ctx, getSKUEffectiveConstraintBySellerAndSKU, arg.SellerAccountID, arg.Sku)
	var i SkuEffectiveConstraint
	err := row.Scan(
		&i.SellerAccountID,
		&i.OzonProductID,
		&i.Sku,
		&i.OfferID,
		&i.ResolvedFromScopeType,
		&i.RuleID,
		&i.EffectiveMinPrice,
		&i.EffectiveMaxPrice,
		&i.ReferencePrice,
		&i.ReferenceMarginPercent,
		&i.ImpliedCost,
		&i.ComputedAt,
	)
	return i, err
}

const listPricingConstraintRulesByScope = `-- name: ListPricingConstraintRulesByScope :many
SELECT id, seller_account_id, scope_type, scope_target_id, scope_target_code, min_price, max_price, reference_margin_percent, reference_price, implied_cost, is_active, created_at, updated_at
FROM pricing_constraint_rules
WHERE seller_account_id = $1
  AND scope_type = $2
  AND (
    scope_target_id = $3
    OR (
      $3::bigint IS NULL
      AND scope_target_id IS NULL
    )
  )
  AND (
    scope_target_code = $4
    OR (
      $4::text IS NULL
      AND scope_target_code IS NULL
    )
  )
ORDER BY is_active DESC, updated_at DESC, id DESC
`

type ListPricingConstraintRulesByScopeParams struct {
	SellerAccountID int64
	ScopeType       string
	ScopeTargetID   pgtype.Int8
	ScopeTargetCode pgtype.Text
}

func (q *Queries) ListPricingConstraintRulesByScope(ctx context.Context, arg ListPricingConstraintRulesByScopeParams) ([]PricingConstraintRule, error) {
	rows, err := q.db.Query(ctx, listPricingConstraintRulesByScope,
		arg.SellerAccountID,
		arg.ScopeType,
		arg.ScopeTargetID,
		arg.ScopeTargetCode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PricingConstraintRule
	for rows.Next() {
		var i PricingConstraintRule
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.ScopeType,
			&i.ScopeTargetID,
			&i.ScopeTargetCode,
			&i.MinPrice,
			&i.MaxPrice,
			&i.ReferenceMarginPercent,
			&i.ReferencePrice,
			&i.ImpliedCost,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricingConstraintRulesBySellerAccountID = `-- name: ListPricingConstraintRulesBySellerAccountID :many
SELECT id, seller_account_id, scope_type, scope_target_id, scope_target_code, min_price, max_price, reference_margin_percent, reference_price, implied_cost, is_active, created_at, updated_at
FROM pricing_constraint_rules
WHERE seller_account_id = $1
ORDER BY scope_type ASC, id ASC
`

func (q *Queries) ListPricingConstraintRulesBySellerAccountID(ctx context.Context, sellerAccountID int64) ([]PricingConstraintRule, error) {
	rows, err := q.db.Query(ctx, listPricingConstraintRulesBySellerAccountID, sellerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PricingConstraintRule
	for rows.Next() {
		var i PricingConstraintRule
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.ScopeType,
			&i.ScopeTargetID,
			&i.ScopeTargetCode,
			&i.MinPrice,
			&i.MaxPrice,
			&i.ReferenceMarginPercent,
			&i.ReferencePrice,
			&i.ImpliedCost,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSKUEffectiveConstraintsBySellerAccountID = `-- name: ListSKUEffectiveConstraintsBySellerAccountID :many
SELECT seller_account_id, ozon_product_id, sku, offer_id, resolved_from_scope_type, rule_id, effective_min_price, effective_max_price, reference_price, reference_margin_percent, implied_cost, computed_at
FROM sku_effective_constraints
WHERE seller_account_id = $1
ORDER BY computed_at DESC, ozon_product_id ASC
`

func (q *Queries) ListSKUEffectiveConstraintsBySellerAccountID(ctx context.Context, sellerAccountID int64) ([]SkuEffectiveConstraint, error) {
	rows, err := q.db.Query(ctx, listSKUEffectiveConstraintsBySellerAccountID, sellerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkuEffectiveConstraint
	for rows.Next() {
		var i SkuEffectiveConstraint
		if err := rows.Scan(
			&i.SellerAccountID,
			&i.OzonProductID,
			&i.Sku,
			&i.OfferID,
			&i.ResolvedFromScopeType,
			&i.RuleID,
			&i.EffectiveMinPrice,
			&i.EffectiveMaxPrice,
			&i.ReferencePrice,
			&i.ReferenceMarginPercent,
			&i.ImpliedCost,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePricingConstraintRule = `-- name: UpdatePricingConstraintRule :one
UPDATE pricing_constraint_rules
SET
    scope_type = $2,
    scope_target_id = $3,
    scope_target_code = $4,
    min_price = $5,
    max_price = $6,
    reference_margin_percent = $7,
    reference_price = $8,
    implied_cost = $9,
    is_active = $10,
    updated_at = NOW()
WHERE id = $1
  AND seller_account_id = $11
RETURNING id, seller_account_id, scope_type, scope_target_id, scope_target_code, min_price, max_price, reference_margin_percent, reference_price, implied_cost, is_active, created_at, updated_at
`

type UpdatePricingConstraintRuleParams struct {
	ID                     int64
	ScopeType              string
	ScopeTargetID          pgtype.Int8
	ScopeTargetCode        pgtype.Text
	MinPrice               pgtype.Numeric
	MaxPrice               pgtype.Numeric
	ReferenceMarginPercent pgtype.Numeric
	ReferencePrice         pgtype.Numeric
	ImpliedCost            pgtype.Numeric
	IsActive               bool
	SellerAccountID        int64
}

func (q *Queries) UpdatePricingConstraintRule(ctx context.Context, arg UpdatePricingConstraintRuleParams) (PricingConstraintRule, error) {
	row := q.db.QueryRow(ctx, updatePricingConstraintRule,
		arg.ID,
		arg.ScopeType,
		arg.ScopeTargetID,
		arg.ScopeTargetCode,
		arg.MinPrice,
		arg.MaxPrice,
		arg.ReferenceMarginPercent,
		arg.ReferencePrice,
		arg.ImpliedCost,
		arg.IsActive,
		arg.SellerAccountID,
	)
	var i PricingConstraintRule
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.ScopeType,
		&i.ScopeTargetID,
		&i.ScopeTargetCode,
		&i.MinPrice,
		&i.MaxPrice,
		&i.ReferenceMarginPercent,
		&i.ReferencePrice,
		&i.ImpliedCost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSKUEffectiveConstraint = `-- name: UpsertSKUEffectiveConstraint :one
INSERT INTO sku_effective_constraints (
    seller_account_id,
    ozon_product_id,
    sku,
    offer_id,
    resolved_from_scope_type,
    rule_id,
    effective_min_price,
    effective_max_price,
    reference_price,
    reference_margin_percent,
    implied_cost,
    computed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW()
)
ON CONFLICT (seller_account_id, ozon_product_id)
DO UPDATE SET
    sku = EXCLUDED.sku,
    offer_id = EXCLUDED.offer_id,
    resolved_from_scope_type = EXCLUDED.resolved_from_scope_type,
    rule_id = EXCLUDED.rule_id,
    effective_min_price = EXCLUDED.effective_min_price,
    effective_max_price = EXCLUDED.effective_max_price,
    reference_price = EXCLUDED.reference_price,
    reference_margin_percent = EXCLUDED.reference_margin_percent,
    implied_cost = EXCLUDED.implied_cost,
    computed_at = NOW()
RETURNING seller_account_id, ozon_product_id, sku, offer_id, resolved_from_scope_type, rule_id, effective_min_price, effective_max_price, reference_price, reference_margin_percent, implied_cost, computed_at
`

type UpsertSKUEffectiveConstraintParams struct {
	SellerAccountID        int64
	OzonProductID          int64
	Sku                    pgtype.Int8
	OfferID                pgtype.Text
	ResolvedFromScopeType  string
	RuleID                 int64
	EffectiveMinPrice      pgtype.Numeric
	EffectiveMaxPrice      pgtype.Numeric
	ReferencePrice         pgtype.Numeric
	ReferenceMarginPercent pgtype.Numeric
	ImpliedCost            pgtype.Numeric
}

func (q *Queries) UpsertSKUEffectiveConstraint(ctx context.Context, arg UpsertSKUEffectiveConstraintParams) (SkuEffectiveConstraint, error) {
	row := q.db.QueryRow(ctx, upsertSKUEffectiveConstraint,
		arg.SellerAccountID,
		arg.OzonProductID,
		arg.Sku,
		arg.OfferID,
		arg.ResolvedFromScopeType,
		arg.RuleID,
		arg.EffectiveMinPrice,
		arg.EffectiveMaxPrice,
		arg.ReferencePrice,
		arg.ReferenceMarginPercent,
		arg.ImpliedCost,
	)
	var i SkuEffectiveConstraint
	err := row.Scan(
		&i.SellerAccountID,
		&i.OzonProductID,
		&i.Sku,
		&i.OfferID,
		&i.ResolvedFromScopeType,
		&i.RuleID,
		&i.EffectiveMinPrice,
		&i.EffectiveMaxPrice,
		&i.ReferencePrice,
		&i.ReferenceMarginPercent,
		&i.ImpliedCost,
		&i.ComputedAt,
	)
	return i, err
}
