// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProductsBySellerAccountID = `-- name: CountProductsBySellerAccountID :one
SELECT COUNT(*)
FROM products
WHERE seller_account_id = $1
`

func (q *Queries) CountProductsBySellerAccountID(ctx context.Context, sellerAccountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsBySellerAccountID, sellerAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listProductsBySellerAccountID = `-- name: ListProductsBySellerAccountID :many
SELECT id, seller_account_id, ozon_product_id, offer_id, sku, name, status, is_archived, raw_attributes, source_updated_at, created_at, updated_at, reference_price, old_price, ozon_min_price, description_category_id
FROM products
WHERE seller_account_id = $1
ORDER BY id ASC
`

func (q *Queries) ListProductsBySellerAccountID(ctx context.Context, sellerAccountID int64) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsBySellerAccountID, sellerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.OzonProductID,
			&i.OfferID,
			&i.Sku,
			&i.Name,
			&i.Status,
			&i.IsArchived,
			&i.RawAttributes,
			&i.SourceUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReferencePrice,
			&i.OldPrice,
			&i.OzonMinPrice,
			&i.DescriptionCategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProduct = `-- name: UpsertProduct :one
INSERT INTO products (
    seller_account_id,
    ozon_product_id,
    offer_id,
    sku,
    name,
    status,
    reference_price,
    old_price,
    ozon_min_price,
    description_category_id,
    is_archived,
    raw_attributes,
    source_updated_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NOW()
)
ON CONFLICT (seller_account_id, ozon_product_id)
DO UPDATE SET
    offer_id = EXCLUDED.offer_id,
    sku = EXCLUDED.sku,
    name = EXCLUDED.name,
    status = EXCLUDED.status,
    reference_price = EXCLUDED.reference_price,
    old_price = EXCLUDED.old_price,
    ozon_min_price = EXCLUDED.ozon_min_price,
    description_category_id = EXCLUDED.description_category_id,
    is_archived = EXCLUDED.is_archived,
    raw_attributes = EXCLUDED.raw_attributes,
    source_updated_at = EXCLUDED.source_updated_at,
    updated_at = NOW()
RETURNING id, seller_account_id, ozon_product_id, offer_id, sku, name, status, is_archived, raw_attributes, source_updated_at, created_at, updated_at, reference_price, old_price, ozon_min_price, description_category_id
`

type UpsertProductParams struct {
	SellerAccountID       int64
	OzonProductID         int64
	OfferID               pgtype.Text
	Sku                   pgtype.Int8
	Name                  string
	Status                pgtype.Text
	ReferencePrice        pgtype.Numeric
	OldPrice              pgtype.Numeric
	OzonMinPrice          pgtype.Numeric
	DescriptionCategoryID pgtype.Int8
	IsArchived            bool
	RawAttributes         []byte
	SourceUpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, upsertProduct,
		arg.SellerAccountID,
		arg.OzonProductID,
		arg.OfferID,
		arg.Sku,
		arg.Name,
		arg.Status,
		arg.ReferencePrice,
		arg.OldPrice,
		arg.OzonMinPrice,
		arg.DescriptionCategoryID,
		arg.IsArchived,
		arg.RawAttributes,
		arg.SourceUpdatedAt,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.OzonProductID,
		&i.OfferID,
		&i.Sku,
		&i.Name,
		&i.Status,
		&i.IsArchived,
		&i.RawAttributes,
		&i.SourceUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReferencePrice,
		&i.OldPrice,
		&i.OzonMinPrice,
		&i.DescriptionCategoryID,
	)
	return i, err
}
