// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: raw_payloads.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRawPayload = `-- name: CreateRawPayload :one
INSERT INTO raw_payloads (
    seller_account_id,
    import_job_id,
    domain,
    source,
    request_key,
    storage_bucket,
    storage_object_key,
    payload_hash,
    received_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW()
)
RETURNING id, seller_account_id, import_job_id, domain, source, request_key, storage_bucket, storage_object_key, payload_hash, received_at
`

type CreateRawPayloadParams struct {
	SellerAccountID  int64
	ImportJobID      int64
	Domain           string
	Source           string
	RequestKey       pgtype.Text
	StorageBucket    string
	StorageObjectKey string
	PayloadHash      string
}

func (q *Queries) CreateRawPayload(ctx context.Context, arg CreateRawPayloadParams) (RawPayload, error) {
	row := q.db.QueryRow(ctx, createRawPayload,
		arg.SellerAccountID,
		arg.ImportJobID,
		arg.Domain,
		arg.Source,
		arg.RequestKey,
		arg.StorageBucket,
		arg.StorageObjectKey,
		arg.PayloadHash,
	)
	var i RawPayload
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.ImportJobID,
		&i.Domain,
		&i.Source,
		&i.RequestKey,
		&i.StorageBucket,
		&i.StorageObjectKey,
		&i.PayloadHash,
		&i.ReceivedAt,
	)
	return i, err
}

const listRawPayloadsByImportJobID = `-- name: ListRawPayloadsByImportJobID :many
SELECT id, seller_account_id, import_job_id, domain, source, request_key, storage_bucket, storage_object_key, payload_hash, received_at
FROM raw_payloads
WHERE import_job_id = $1
ORDER BY received_at DESC
`

func (q *Queries) ListRawPayloadsByImportJobID(ctx context.Context, importJobID int64) ([]RawPayload, error) {
	rows, err := q.db.Query(ctx, listRawPayloadsByImportJobID, importJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RawPayload
	for rows.Next() {
		var i RawPayload
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.ImportJobID,
			&i.Domain,
			&i.Source,
			&i.RequestKey,
			&i.StorageBucket,
			&i.StorageObjectKey,
			&i.PayloadHash,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
