// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendations.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptRecommendation = `-- name: AcceptRecommendation :one
UPDATE recommendations
SET
    status = 'accepted',
    accepted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND seller_account_id = $2
RETURNING id, seller_account_id, source, recommendation_type, horizon, entity_type, entity_id, entity_sku, entity_offer_id, title, what_happened, why_it_matters, recommended_action, expected_effect, priority_score, priority_level, urgency, confidence_level, status, supporting_metrics_payload, constraints_payload, ai_model, ai_prompt_version, raw_ai_response, fingerprint, first_seen_at, last_seen_at, accepted_at, dismissed_at, resolved_at, created_at, updated_at
`

type AcceptRecommendationParams struct {
	ID              int64
	SellerAccountID int64
}

func (q *Queries) AcceptRecommendation(ctx context.Context, arg AcceptRecommendationParams) (Recommendation, error) {
	row := q.db.QueryRow(ctx, acceptRecommendation, arg.ID, arg.SellerAccountID)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.Source,
		&i.RecommendationType,
		&i.Horizon,
		&i.EntityType,
		&i.EntityID,
		&i.EntitySku,
		&i.EntityOfferID,
		&i.Title,
		&i.WhatHappened,
		&i.WhyItMatters,
		&i.RecommendedAction,
		&i.ExpectedEffect,
		&i.PriorityScore,
		&i.PriorityLevel,
		&i.Urgency,
		&i.ConfidenceLevel,
		&i.Status,
		&i.SupportingMetricsPayload,
		&i.ConstraintsPayload,
		&i.AiModel,
		&i.AiPromptVersion,
		&i.RawAiResponse,
		&i.Fingerprint,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.AcceptedAt,
		&i.DismissedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeRecommendationRun = `-- name: CompleteRecommendationRun :one
UPDATE recommendation_runs
SET
    status = 'completed',
    finished_at = NOW(),
    input_tokens = $3,
    output_tokens = $4,
    estimated_cost = $5,
    generated_recommendations_count = $6,
    accepted_recommendations_count = $7,
    error_message = NULL
WHERE id = $1
  AND seller_account_id = $2
RETURNING id, seller_account_id, run_type, status, as_of_date, ai_model, ai_prompt_version, input_tokens, output_tokens, estimated_cost, generated_recommendations_count, accepted_recommendations_count, error_message, started_at, finished_at, created_at
`

type CompleteRecommendationRunParams struct {
	ID                            int64
	SellerAccountID               int64
	InputTokens                   int32
	OutputTokens                  int32
	EstimatedCost                 pgtype.Numeric
	GeneratedRecommendationsCount int32
	AcceptedRecommendationsCount  int32
}

func (q *Queries) CompleteRecommendationRun(ctx context.Context, arg CompleteRecommendationRunParams) (RecommendationRun, error) {
	row := q.db.QueryRow(ctx, completeRecommendationRun,
		arg.ID,
		arg.SellerAccountID,
		arg.InputTokens,
		arg.OutputTokens,
		arg.EstimatedCost,
		arg.GeneratedRecommendationsCount,
		arg.AcceptedRecommendationsCount,
	)
	var i RecommendationRun
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.RunType,
		&i.Status,
		&i.AsOfDate,
		&i.AiModel,
		&i.AiPromptVersion,
		&i.InputTokens,
		&i.OutputTokens,
		&i.EstimatedCost,
		&i.GeneratedRecommendationsCount,
		&i.AcceptedRecommendationsCount,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countOpenRecommendationsByConfidence = `-- name: CountOpenRecommendationsByConfidence :many
SELECT
    confidence_level,
    COUNT(*) AS recommendations_count
FROM recommendations
WHERE seller_account_id = $1
  AND status = 'open'
GROUP BY confidence_level
ORDER BY confidence_level ASC
`

type CountOpenRecommendationsByConfidenceRow struct {
	ConfidenceLevel      string
	RecommendationsCount int64
}

func (q *Queries) CountOpenRecommendationsByConfidence(ctx context.Context, sellerAccountID int64) ([]CountOpenRecommendationsByConfidenceRow, error) {
	rows, err := q.db.Query(ctx, countOpenRecommendationsByConfidence, sellerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOpenRecommendationsByConfidenceRow
	for rows.Next() {
		var i CountOpenRecommendationsByConfidenceRow
		if err := rows.Scan(&i.ConfidenceLevel, &i.RecommendationsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOpenRecommendationsByPriority = `-- name: CountOpenRecommendationsByPriority :many
SELECT
    priority_level,
    COUNT(*) AS recommendations_count
FROM recommendations
WHERE seller_account_id = $1
  AND status = 'open'
GROUP BY priority_level
ORDER BY priority_level ASC
`

type CountOpenRecommendationsByPriorityRow struct {
	PriorityLevel        string
	RecommendationsCount int64
}

func (q *Queries) CountOpenRecommendationsByPriority(ctx context.Context, sellerAccountID int64) ([]CountOpenRecommendationsByPriorityRow, error) {
	rows, err := q.db.Query(ctx, countOpenRecommendationsByPriority, sellerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOpenRecommendationsByPriorityRow
	for rows.Next() {
		var i CountOpenRecommendationsByPriorityRow
		if err := rows.Scan(&i.PriorityLevel, &i.RecommendationsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOpenRecommendationsBySellerAccountID = `-- name: CountOpenRecommendationsBySellerAccountID :one
SELECT COUNT(*)
FROM recommendations
WHERE seller_account_id = $1
  AND status = 'open'
`

func (q *Queries) CountOpenRecommendationsBySellerAccountID(ctx context.Context, sellerAccountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenRecommendationsBySellerAccountID, sellerAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecommendationAlertLinksBySellerAccountID = `-- name: CountRecommendationAlertLinksBySellerAccountID :one
SELECT COUNT(*)::bigint
FROM recommendation_alert_links
WHERE seller_account_id = $1
`

func (q *Queries) CountRecommendationAlertLinksBySellerAccountID(ctx context.Context, sellerAccountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRecommendationAlertLinksBySellerAccountID, sellerAccountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRecommendationRunsBySellerAccountID = `-- name: CountRecommendationRunsBySellerAccountID :one
SELECT COUNT(*)::bigint
FROM recommendation_runs
WHERE seller_account_id = $1
`

func (q *Queries) CountRecommendationRunsBySellerAccountID(ctx context.Context, sellerAccountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRecommendationRunsBySellerAccountID, sellerAccountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRecommendationsBySellerAccountID = `-- name: CountRecommendationsBySellerAccountID :one
SELECT COUNT(*)::bigint
FROM recommendations
WHERE seller_account_id = $1
`

func (q *Queries) CountRecommendationsBySellerAccountID(ctx context.Context, sellerAccountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRecommendationsBySellerAccountID, sellerAccountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRecommendationsWithNonEmptyPayloadsBySellerAccountID = `-- name: CountRecommendationsWithNonEmptyPayloadsBySellerAccountID :one
SELECT COUNT(*)::bigint
FROM recommendations
WHERE seller_account_id = $1
  AND supporting_metrics_payload IS NOT NULL
  AND supporting_metrics_payload <> '{}'::jsonb
  AND constraints_payload IS NOT NULL
  AND constraints_payload <> '{}'::jsonb
`

func (q *Queries) CountRecommendationsWithNonEmptyPayloadsBySellerAccountID(ctx context.Context, sellerAccountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRecommendationsWithNonEmptyPayloadsBySellerAccountID, sellerAccountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRecommendationsWithRawAIBySellerAccountID = `-- name: CountRecommendationsWithRawAIBySellerAccountID :one
SELECT COUNT(*)::bigint
FROM recommendations
WHERE seller_account_id = $1
  AND raw_ai_response IS NOT NULL
  AND raw_ai_response <> '{}'::jsonb
`

func (q *Queries) CountRecommendationsWithRawAIBySellerAccountID(ctx context.Context, sellerAccountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRecommendationsWithRawAIBySellerAccountID, sellerAccountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createRecommendationRun = `-- name: CreateRecommendationRun :one
INSERT INTO recommendation_runs (
    seller_account_id,
    run_type,
    as_of_date,
    ai_model,
    ai_prompt_version,
    status,
    started_at
) VALUES (
    $1, $2, $3, $4, $5, 'running', NOW()
)
RETURNING id, seller_account_id, run_type, status, as_of_date, ai_model, ai_prompt_version, input_tokens, output_tokens, estimated_cost, generated_recommendations_count, accepted_recommendations_count, error_message, started_at, finished_at, created_at
`

type CreateRecommendationRunParams struct {
	SellerAccountID int64
	RunType         string
	AsOfDate        pgtype.Date
	AiModel         pgtype.Text
	AiPromptVersion pgtype.Text
}

func (q *Queries) CreateRecommendationRun(ctx context.Context, arg CreateRecommendationRunParams) (RecommendationRun, error) {
	row := q.db.QueryRow(ctx, createRecommendationRun,
		arg.SellerAccountID,
		arg.RunType,
		arg.AsOfDate,
		arg.AiModel,
		arg.AiPromptVersion,
	)
	var i RecommendationRun
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.RunType,
		&i.Status,
		&i.AsOfDate,
		&i.AiModel,
		&i.AiPromptVersion,
		&i.InputTokens,
		&i.OutputTokens,
		&i.EstimatedCost,
		&i.GeneratedRecommendationsCount,
		&i.AcceptedRecommendationsCount,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecommendationAlertLinks = `-- name: DeleteRecommendationAlertLinks :exec
DELETE FROM recommendation_alert_links
WHERE recommendation_id = $1
  AND seller_account_id = $2
`

type DeleteRecommendationAlertLinksParams struct {
	RecommendationID int64
	SellerAccountID  int64
}

func (q *Queries) DeleteRecommendationAlertLinks(ctx context.Context, arg DeleteRecommendationAlertLinksParams) error {
	_, err := q.db.Exec(ctx, deleteRecommendationAlertLinks, arg.RecommendationID, arg.SellerAccountID)
	return err
}

const dismissRecommendation = `-- name: DismissRecommendation :one
UPDATE recommendations
SET
    status = 'dismissed',
    dismissed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND seller_account_id = $2
RETURNING id, seller_account_id, source, recommendation_type, horizon, entity_type, entity_id, entity_sku, entity_offer_id, title, what_happened, why_it_matters, recommended_action, expected_effect, priority_score, priority_level, urgency, confidence_level, status, supporting_metrics_payload, constraints_payload, ai_model, ai_prompt_version, raw_ai_response, fingerprint, first_seen_at, last_seen_at, accepted_at, dismissed_at, resolved_at, created_at, updated_at
`

type DismissRecommendationParams struct {
	ID              int64
	SellerAccountID int64
}

func (q *Queries) DismissRecommendation(ctx context.Context, arg DismissRecommendationParams) (Recommendation, error) {
	row := q.db.QueryRow(ctx, dismissRecommendation, arg.ID, arg.SellerAccountID)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.Source,
		&i.RecommendationType,
		&i.Horizon,
		&i.EntityType,
		&i.EntityID,
		&i.EntitySku,
		&i.EntityOfferID,
		&i.Title,
		&i.WhatHappened,
		&i.WhyItMatters,
		&i.RecommendedAction,
		&i.ExpectedEffect,
		&i.PriorityScore,
		&i.PriorityLevel,
		&i.Urgency,
		&i.ConfidenceLevel,
		&i.Status,
		&i.SupportingMetricsPayload,
		&i.ConstraintsPayload,
		&i.AiModel,
		&i.AiPromptVersion,
		&i.RawAiResponse,
		&i.Fingerprint,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.AcceptedAt,
		&i.DismissedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failRecommendationRun = `-- name: FailRecommendationRun :one
UPDATE recommendation_runs
SET
    status = 'failed',
    finished_at = NOW(),
    error_message = $3
WHERE id = $1
  AND seller_account_id = $2
RETURNING id, seller_account_id, run_type, status, as_of_date, ai_model, ai_prompt_version, input_tokens, output_tokens, estimated_cost, generated_recommendations_count, accepted_recommendations_count, error_message, started_at, finished_at, created_at
`

type FailRecommendationRunParams struct {
	ID              int64
	SellerAccountID int64
	ErrorMessage    pgtype.Text
}

func (q *Queries) FailRecommendationRun(ctx context.Context, arg FailRecommendationRunParams) (RecommendationRun, error) {
	row := q.db.QueryRow(ctx, failRecommendationRun, arg.ID, arg.SellerAccountID, arg.ErrorMessage)
	var i RecommendationRun
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.RunType,
		&i.Status,
		&i.AsOfDate,
		&i.AiModel,
		&i.AiPromptVersion,
		&i.InputTokens,
		&i.OutputTokens,
		&i.EstimatedCost,
		&i.GeneratedRecommendationsCount,
		&i.AcceptedRecommendationsCount,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestRecommendationRunBySellerAccountID = `-- name: GetLatestRecommendationRunBySellerAccountID :one
SELECT id, seller_account_id, run_type, status, as_of_date, ai_model, ai_prompt_version, input_tokens, output_tokens, estimated_cost, generated_recommendations_count, accepted_recommendations_count, error_message, started_at, finished_at, created_at
FROM recommendation_runs
WHERE seller_account_id = $1
ORDER BY started_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestRecommendationRunBySellerAccountID(ctx context.Context, sellerAccountID int64) (RecommendationRun, error) {
	row := q.db.QueryRow(ctx, getLatestRecommendationRunBySellerAccountID, sellerAccountID)
	var i RecommendationRun
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.RunType,
		&i.Status,
		&i.AsOfDate,
		&i.AiModel,
		&i.AiPromptVersion,
		&i.InputTokens,
		&i.OutputTokens,
		&i.EstimatedCost,
		&i.GeneratedRecommendationsCount,
		&i.AcceptedRecommendationsCount,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRecommendationByID = `-- name: GetRecommendationByID :one
SELECT id, seller_account_id, source, recommendation_type, horizon, entity_type, entity_id, entity_sku, entity_offer_id, title, what_happened, why_it_matters, recommended_action, expected_effect, priority_score, priority_level, urgency, confidence_level, status, supporting_metrics_payload, constraints_payload, ai_model, ai_prompt_version, raw_ai_response, fingerprint, first_seen_at, last_seen_at, accepted_at, dismissed_at, resolved_at, created_at, updated_at
FROM recommendations
WHERE id = $1
  AND seller_account_id = $2
`

type GetRecommendationByIDParams struct {
	ID              int64
	SellerAccountID int64
}

func (q *Queries) GetRecommendationByID(ctx context.Context, arg GetRecommendationByIDParams) (Recommendation, error) {
	row := q.db.QueryRow(ctx, getRecommendationByID, arg.ID, arg.SellerAccountID)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.Source,
		&i.RecommendationType,
		&i.Horizon,
		&i.EntityType,
		&i.EntityID,
		&i.EntitySku,
		&i.EntityOfferID,
		&i.Title,
		&i.WhatHappened,
		&i.WhyItMatters,
		&i.RecommendedAction,
		&i.ExpectedEffect,
		&i.PriorityScore,
		&i.PriorityLevel,
		&i.Urgency,
		&i.ConfidenceLevel,
		&i.Status,
		&i.SupportingMetricsPayload,
		&i.ConstraintsPayload,
		&i.AiModel,
		&i.AiPromptVersion,
		&i.RawAiResponse,
		&i.Fingerprint,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.AcceptedAt,
		&i.DismissedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkRecommendationAlert = `-- name: LinkRecommendationAlert :exec
INSERT INTO recommendation_alert_links (
    recommendation_id,
    alert_id,
    seller_account_id,
    link_type
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (recommendation_id, alert_id) DO NOTHING
`

type LinkRecommendationAlertParams struct {
	RecommendationID int64
	AlertID          int64
	SellerAccountID  int64
	LinkType         string
}

func (q *Queries) LinkRecommendationAlert(ctx context.Context, arg LinkRecommendationAlertParams) error {
	_, err := q.db.Exec(ctx, linkRecommendationAlert,
		arg.RecommendationID,
		arg.AlertID,
		arg.SellerAccountID,
		arg.LinkType,
	)
	return err
}

const listAlertsByRecommendationID = `-- name: ListAlertsByRecommendationID :many
SELECT a.id, a.seller_account_id, a.alert_type, a.alert_group, a.entity_type, a.entity_id, a.entity_sku, a.entity_offer_id, a.title, a.message, a.severity, a.urgency, a.status, a.evidence_payload, a.fingerprint, a.first_seen_at, a.last_seen_at, a.resolved_at, a.created_at, a.updated_at
FROM recommendation_alert_links ral
JOIN alerts a ON a.id = ral.alert_id
WHERE ral.seller_account_id = $1
  AND ral.recommendation_id = $2
ORDER BY a.last_seen_at DESC, a.id DESC
`

type ListAlertsByRecommendationIDParams struct {
	SellerAccountID  int64
	RecommendationID int64
}

func (q *Queries) ListAlertsByRecommendationID(ctx context.Context, arg ListAlertsByRecommendationIDParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsByRecommendationID, arg.SellerAccountID, arg.RecommendationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.AlertType,
			&i.AlertGroup,
			&i.EntityType,
			&i.EntityID,
			&i.EntitySku,
			&i.EntityOfferID,
			&i.Title,
			&i.Message,
			&i.Severity,
			&i.Urgency,
			&i.Status,
			&i.EvidencePayload,
			&i.Fingerprint,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenRecommendationsBySellerAccountID = `-- name: ListOpenRecommendationsBySellerAccountID :many
SELECT id, seller_account_id, source, recommendation_type, horizon, entity_type, entity_id, entity_sku, entity_offer_id, title, what_happened, why_it_matters, recommended_action, expected_effect, priority_score, priority_level, urgency, confidence_level, status, supporting_metrics_payload, constraints_payload, ai_model, ai_prompt_version, raw_ai_response, fingerprint, first_seen_at, last_seen_at, accepted_at, dismissed_at, resolved_at, created_at, updated_at
FROM recommendations
WHERE seller_account_id = $1
  AND status = 'open'
ORDER BY last_seen_at DESC, id DESC
LIMIT $2
OFFSET $3
`

type ListOpenRecommendationsBySellerAccountIDParams struct {
	SellerAccountID int64
	Limit           int32
	Offset          int32
}

func (q *Queries) ListOpenRecommendationsBySellerAccountID(ctx context.Context, arg ListOpenRecommendationsBySellerAccountIDParams) ([]Recommendation, error) {
	rows, err := q.db.Query(ctx, listOpenRecommendationsBySellerAccountID, arg.SellerAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recommendation
	for rows.Next() {
		var i Recommendation
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.Source,
			&i.RecommendationType,
			&i.Horizon,
			&i.EntityType,
			&i.EntityID,
			&i.EntitySku,
			&i.EntityOfferID,
			&i.Title,
			&i.WhatHappened,
			&i.WhyItMatters,
			&i.RecommendedAction,
			&i.ExpectedEffect,
			&i.PriorityScore,
			&i.PriorityLevel,
			&i.Urgency,
			&i.ConfidenceLevel,
			&i.Status,
			&i.SupportingMetricsPayload,
			&i.ConstraintsPayload,
			&i.AiModel,
			&i.AiPromptVersion,
			&i.RawAiResponse,
			&i.Fingerprint,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.AcceptedAt,
			&i.DismissedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationRunsBySellerAccountID = `-- name: ListRecommendationRunsBySellerAccountID :many
SELECT id, seller_account_id, run_type, status, as_of_date, ai_model, ai_prompt_version, input_tokens, output_tokens, estimated_cost, generated_recommendations_count, accepted_recommendations_count, error_message, started_at, finished_at, created_at
FROM recommendation_runs
WHERE seller_account_id = $1
ORDER BY started_at DESC, id DESC
LIMIT $2
OFFSET $3
`

type ListRecommendationRunsBySellerAccountIDParams struct {
	SellerAccountID int64
	Limit           int32
	Offset          int32
}

func (q *Queries) ListRecommendationRunsBySellerAccountID(ctx context.Context, arg ListRecommendationRunsBySellerAccountIDParams) ([]RecommendationRun, error) {
	rows, err := q.db.Query(ctx, listRecommendationRunsBySellerAccountID, arg.SellerAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecommendationRun
	for rows.Next() {
		var i RecommendationRun
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.RunType,
			&i.Status,
			&i.AsOfDate,
			&i.AiModel,
			&i.AiPromptVersion,
			&i.InputTokens,
			&i.OutputTokens,
			&i.EstimatedCost,
			&i.GeneratedRecommendationsCount,
			&i.AcceptedRecommendationsCount,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationsByAlertID = `-- name: ListRecommendationsByAlertID :many
SELECT r.id, r.seller_account_id, r.source, r.recommendation_type, r.horizon, r.entity_type, r.entity_id, r.entity_sku, r.entity_offer_id, r.title, r.what_happened, r.why_it_matters, r.recommended_action, r.expected_effect, r.priority_score, r.priority_level, r.urgency, r.confidence_level, r.status, r.supporting_metrics_payload, r.constraints_payload, r.ai_model, r.ai_prompt_version, r.raw_ai_response, r.fingerprint, r.first_seen_at, r.last_seen_at, r.accepted_at, r.dismissed_at, r.resolved_at, r.created_at, r.updated_at
FROM recommendation_alert_links ral
JOIN recommendations r ON r.id = ral.recommendation_id
WHERE ral.seller_account_id = $1
  AND ral.alert_id = $2
ORDER BY r.last_seen_at DESC, r.id DESC
`

type ListRecommendationsByAlertIDParams struct {
	SellerAccountID int64
	AlertID         int64
}

func (q *Queries) ListRecommendationsByAlertID(ctx context.Context, arg ListRecommendationsByAlertIDParams) ([]Recommendation, error) {
	rows, err := q.db.Query(ctx, listRecommendationsByAlertID, arg.SellerAccountID, arg.AlertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recommendation
	for rows.Next() {
		var i Recommendation
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.Source,
			&i.RecommendationType,
			&i.Horizon,
			&i.EntityType,
			&i.EntityID,
			&i.EntitySku,
			&i.EntityOfferID,
			&i.Title,
			&i.WhatHappened,
			&i.WhyItMatters,
			&i.RecommendedAction,
			&i.ExpectedEffect,
			&i.PriorityScore,
			&i.PriorityLevel,
			&i.Urgency,
			&i.ConfidenceLevel,
			&i.Status,
			&i.SupportingMetricsPayload,
			&i.ConstraintsPayload,
			&i.AiModel,
			&i.AiPromptVersion,
			&i.RawAiResponse,
			&i.Fingerprint,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.AcceptedAt,
			&i.DismissedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationsBySellerAccountID = `-- name: ListRecommendationsBySellerAccountID :many
SELECT id, seller_account_id, source, recommendation_type, horizon, entity_type, entity_id, entity_sku, entity_offer_id, title, what_happened, why_it_matters, recommended_action, expected_effect, priority_score, priority_level, urgency, confidence_level, status, supporting_metrics_payload, constraints_payload, ai_model, ai_prompt_version, raw_ai_response, fingerprint, first_seen_at, last_seen_at, accepted_at, dismissed_at, resolved_at, created_at, updated_at
FROM recommendations
WHERE seller_account_id = $1
ORDER BY last_seen_at DESC, id DESC
LIMIT $2
OFFSET $3
`

type ListRecommendationsBySellerAccountIDParams struct {
	SellerAccountID int64
	Limit           int32
	Offset          int32
}

func (q *Queries) ListRecommendationsBySellerAccountID(ctx context.Context, arg ListRecommendationsBySellerAccountIDParams) ([]Recommendation, error) {
	rows, err := q.db.Query(ctx, listRecommendationsBySellerAccountID, arg.SellerAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recommendation
	for rows.Next() {
		var i Recommendation
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.Source,
			&i.RecommendationType,
			&i.Horizon,
			&i.EntityType,
			&i.EntityID,
			&i.EntitySku,
			&i.EntityOfferID,
			&i.Title,
			&i.WhatHappened,
			&i.WhyItMatters,
			&i.RecommendedAction,
			&i.ExpectedEffect,
			&i.PriorityScore,
			&i.PriorityLevel,
			&i.Urgency,
			&i.ConfidenceLevel,
			&i.Status,
			&i.SupportingMetricsPayload,
			&i.ConstraintsPayload,
			&i.AiModel,
			&i.AiPromptVersion,
			&i.RawAiResponse,
			&i.Fingerprint,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.AcceptedAt,
			&i.DismissedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationsFiltered = `-- name: ListRecommendationsFiltered :many
SELECT id, seller_account_id, source, recommendation_type, horizon, entity_type, entity_id, entity_sku, entity_offer_id, title, what_happened, why_it_matters, recommended_action, expected_effect, priority_score, priority_level, urgency, confidence_level, status, supporting_metrics_payload, constraints_payload, ai_model, ai_prompt_version, raw_ai_response, fingerprint, first_seen_at, last_seen_at, accepted_at, dismissed_at, resolved_at, created_at, updated_at
FROM recommendations
WHERE seller_account_id = $1
  AND (
    status = $4
    OR (
      $4::text IS NULL
      AND status IS NOT NULL
    )
  )
  AND (
    recommendation_type = $5
    OR (
      $5::text IS NULL
      AND recommendation_type IS NOT NULL
    )
  )
  AND (
    priority_level = $6
    OR (
      $6::text IS NULL
      AND priority_level IS NOT NULL
    )
  )
  AND (
    confidence_level = $7
    OR (
      $7::text IS NULL
      AND confidence_level IS NOT NULL
    )
  )
  AND (
    horizon = $8
    OR (
      $8::text IS NULL
      AND horizon IS NOT NULL
    )
  )
  AND (
    entity_type = $9
    OR (
      $9::text IS NULL
      AND entity_type IS NOT NULL
    )
  )
ORDER BY last_seen_at DESC, id DESC
LIMIT $2
OFFSET $3
`

type ListRecommendationsFilteredParams struct {
	SellerAccountID    int64
	Limit              int32
	Offset             int32
	Status             pgtype.Text
	RecommendationType pgtype.Text
	PriorityLevel      pgtype.Text
	ConfidenceLevel    pgtype.Text
	Horizon            pgtype.Text
	EntityType         pgtype.Text
}

func (q *Queries) ListRecommendationsFiltered(ctx context.Context, arg ListRecommendationsFilteredParams) ([]Recommendation, error) {
	rows, err := q.db.Query(ctx, listRecommendationsFiltered,
		arg.SellerAccountID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.RecommendationType,
		arg.PriorityLevel,
		arg.ConfidenceLevel,
		arg.Horizon,
		arg.EntityType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recommendation
	for rows.Next() {
		var i Recommendation
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.Source,
			&i.RecommendationType,
			&i.Horizon,
			&i.EntityType,
			&i.EntityID,
			&i.EntitySku,
			&i.EntityOfferID,
			&i.Title,
			&i.WhatHappened,
			&i.WhyItMatters,
			&i.RecommendedAction,
			&i.ExpectedEffect,
			&i.PriorityScore,
			&i.PriorityLevel,
			&i.Urgency,
			&i.ConfidenceLevel,
			&i.Status,
			&i.SupportingMetricsPayload,
			&i.ConstraintsPayload,
			&i.AiModel,
			&i.AiPromptVersion,
			&i.RawAiResponse,
			&i.Fingerprint,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.AcceptedAt,
			&i.DismissedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveRecommendation = `-- name: ResolveRecommendation :one
UPDATE recommendations
SET
    status = 'resolved',
    resolved_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND seller_account_id = $2
RETURNING id, seller_account_id, source, recommendation_type, horizon, entity_type, entity_id, entity_sku, entity_offer_id, title, what_happened, why_it_matters, recommended_action, expected_effect, priority_score, priority_level, urgency, confidence_level, status, supporting_metrics_payload, constraints_payload, ai_model, ai_prompt_version, raw_ai_response, fingerprint, first_seen_at, last_seen_at, accepted_at, dismissed_at, resolved_at, created_at, updated_at
`

type ResolveRecommendationParams struct {
	ID              int64
	SellerAccountID int64
}

func (q *Queries) ResolveRecommendation(ctx context.Context, arg ResolveRecommendationParams) (Recommendation, error) {
	row := q.db.QueryRow(ctx, resolveRecommendation, arg.ID, arg.SellerAccountID)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.Source,
		&i.RecommendationType,
		&i.Horizon,
		&i.EntityType,
		&i.EntityID,
		&i.EntitySku,
		&i.EntityOfferID,
		&i.Title,
		&i.WhatHappened,
		&i.WhyItMatters,
		&i.RecommendedAction,
		&i.ExpectedEffect,
		&i.PriorityScore,
		&i.PriorityLevel,
		&i.Urgency,
		&i.ConfidenceLevel,
		&i.Status,
		&i.SupportingMetricsPayload,
		&i.ConstraintsPayload,
		&i.AiModel,
		&i.AiPromptVersion,
		&i.RawAiResponse,
		&i.Fingerprint,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.AcceptedAt,
		&i.DismissedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRecommendation = `-- name: UpsertRecommendation :one
INSERT INTO recommendations (
    seller_account_id,
    source,
    recommendation_type,
    horizon,
    entity_type,
    entity_id,
    entity_sku,
    entity_offer_id,
    title,
    what_happened,
    why_it_matters,
    recommended_action,
    expected_effect,
    priority_score,
    priority_level,
    urgency,
    confidence_level,
    supporting_metrics_payload,
    constraints_payload,
    ai_model,
    ai_prompt_version,
    raw_ai_response,
    fingerprint,
    first_seen_at,
    last_seen_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, NOW(), NOW(), NOW()
)
ON CONFLICT (seller_account_id, fingerprint)
DO UPDATE SET
    source = CASE
        WHEN recommendations.status IN ('dismissed', 'accepted') THEN recommendations.source
        ELSE EXCLUDED.source
    END,
    recommendation_type = CASE
        WHEN recommendations.status IN ('dismissed', 'accepted') THEN recommendations.recommendation_type
        ELSE EXCLUDED.recommendation_type
    END,
    horizon = CASE
        WHEN recommendations.status IN ('dismissed', 'accepted') THEN recommendations.horizon
        ELSE EXCLUDED.horizon
    END,
    entity_type = CASE
        WHEN recommendations.status IN ('dismissed', 'accepted') THEN recommendations.entity_type
        ELSE EXCLUDED.entity_type
    END,
    entity_id = CASE
        WHEN recommendations.status IN ('dismissed', 'accepted') THEN recommendations.entity_id
        ELSE EXCLUDED.entity_id
    END,
    entity_sku = CASE
        WHEN recommendations.status IN ('dismissed', 'accepted') THEN recommendations.entity_sku
        ELSE EXCLUDED.entity_sku
    END,
    entity_offer_id = CASE
        WHEN recommendations.status IN ('dismissed', 'accepted') THEN recommendations.entity_offer_id
        ELSE EXCLUDED.entity_offer_id
    END,
    title = CASE
        WHEN recommendations.status IN ('dismissed', 'accepted') THEN recommendations.title
        ELSE EXCLUDED.title
    END,
    what_happened = CASE
        WHEN recommendations.status IN ('dismissed', 'accepted') THEN recommendations.what_happened
        ELSE EXCLUDED.what_happened
    END,
    why_it_matters = CASE
        WHEN recommendations.status IN ('dismissed', 'accepted') THEN recommendations.why_it_matters
        ELSE EXCLUDED.why_it_matters
    END,
    recommended_action = CASE
        WHEN recommendations.status IN ('dismissed', 'accepted') THEN recommendations.recommended_action
        ELSE EXCLUDED.recommended_action
    END,
    expected_effect = CASE
        WHEN recommendations.status IN ('dismissed', 'accepted') THEN recommendations.expected_effect
        ELSE EXCLUDED.expected_effect
    END,
    priority_score = CASE
        WHEN recommendations.status IN ('dismissed', 'accepted') THEN recommendations.priority_score
        ELSE EXCLUDED.priority_score
    END,
    priority_level = CASE
        WHEN recommendations.status IN ('dismissed', 'accepted') THEN recommendations.priority_level
        ELSE EXCLUDED.priority_level
    END,
    urgency = CASE
        WHEN recommendations.status IN ('dismissed', 'accepted') THEN recommendations.urgency
        ELSE EXCLUDED.urgency
    END,
    confidence_level = CASE
        WHEN recommendations.status IN ('dismissed', 'accepted') THEN recommendations.confidence_level
        ELSE EXCLUDED.confidence_level
    END,
    status = CASE
        WHEN recommendations.status = 'dismissed' THEN 'dismissed'
        WHEN recommendations.status = 'accepted' THEN 'accepted'
        ELSE 'open'
    END,
    supporting_metrics_payload = EXCLUDED.supporting_metrics_payload,
    constraints_payload = EXCLUDED.constraints_payload,
    ai_model = EXCLUDED.ai_model,
    ai_prompt_version = EXCLUDED.ai_prompt_version,
    raw_ai_response = EXCLUDED.raw_ai_response,
    last_seen_at = NOW(),
    resolved_at = CASE
        WHEN recommendations.status IN ('dismissed', 'accepted') THEN recommendations.resolved_at
        ELSE NULL
    END,
    updated_at = NOW()
RETURNING id, seller_account_id, source, recommendation_type, horizon, entity_type, entity_id, entity_sku, entity_offer_id, title, what_happened, why_it_matters, recommended_action, expected_effect, priority_score, priority_level, urgency, confidence_level, status, supporting_metrics_payload, constraints_payload, ai_model, ai_prompt_version, raw_ai_response, fingerprint, first_seen_at, last_seen_at, accepted_at, dismissed_at, resolved_at, created_at, updated_at
`

type UpsertRecommendationParams struct {
	SellerAccountID          int64
	Source                   string
	RecommendationType       string
	Horizon                  string
	EntityType               string
	EntityID                 pgtype.Text
	EntitySku                pgtype.Int8
	EntityOfferID            pgtype.Text
	Title                    string
	WhatHappened             string
	WhyItMatters             string
	RecommendedAction        string
	ExpectedEffect           pgtype.Text
	PriorityScore            pgtype.Numeric
	PriorityLevel            string
	Urgency                  string
	ConfidenceLevel          string
	SupportingMetricsPayload []byte
	ConstraintsPayload       []byte
	AiModel                  pgtype.Text
	AiPromptVersion          pgtype.Text
	RawAiResponse            []byte
	Fingerprint              string
}

func (q *Queries) UpsertRecommendation(ctx context.Context, arg UpsertRecommendationParams) (Recommendation, error) {
	row := q.db.QueryRow(ctx, upsertRecommendation,
		arg.SellerAccountID,
		arg.Source,
		arg.RecommendationType,
		arg.Horizon,
		arg.EntityType,
		arg.EntityID,
		arg.EntitySku,
		arg.EntityOfferID,
		arg.Title,
		arg.WhatHappened,
		arg.WhyItMatters,
		arg.RecommendedAction,
		arg.ExpectedEffect,
		arg.PriorityScore,
		arg.PriorityLevel,
		arg.Urgency,
		arg.ConfidenceLevel,
		arg.SupportingMetricsPayload,
		arg.ConstraintsPayload,
		arg.AiModel,
		arg.AiPromptVersion,
		arg.RawAiResponse,
		arg.Fingerprint,
	)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.Source,
		&i.RecommendationType,
		&i.Horizon,
		&i.EntityType,
		&i.EntityID,
		&i.EntitySku,
		&i.EntityOfferID,
		&i.Title,
		&i.WhatHappened,
		&i.WhyItMatters,
		&i.RecommendedAction,
		&i.ExpectedEffect,
		&i.PriorityScore,
		&i.PriorityLevel,
		&i.Urgency,
		&i.ConfidenceLevel,
		&i.Status,
		&i.SupportingMetricsPayload,
		&i.ConstraintsPayload,
		&i.AiModel,
		&i.AiPromptVersion,
		&i.RawAiResponse,
		&i.Fingerprint,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.AcceptedAt,
		&i.DismissedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
