// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendation_feedback.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecommendationFeedback = `-- name: CreateRecommendationFeedback :one
INSERT INTO recommendation_feedback (
    recommendation_id,
    seller_account_id,
    rating,
    comment
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (seller_account_id, recommendation_id)
DO UPDATE SET
    rating = EXCLUDED.rating,
    comment = EXCLUDED.comment,
    created_at = NOW()
RETURNING id, recommendation_id, seller_account_id, rating, comment, created_at
`

type CreateRecommendationFeedbackParams struct {
	RecommendationID int64
	SellerAccountID  int64
	Rating           string
	Comment          pgtype.Text
}

func (q *Queries) CreateRecommendationFeedback(ctx context.Context, arg CreateRecommendationFeedbackParams) (RecommendationFeedback, error) {
	row := q.db.QueryRow(ctx, createRecommendationFeedback,
		arg.RecommendationID,
		arg.SellerAccountID,
		arg.Rating,
		arg.Comment,
	)
	var i RecommendationFeedback
	err := row.Scan(
		&i.ID,
		&i.RecommendationID,
		&i.SellerAccountID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getRecommendationFeedbackByRecommendationID = `-- name: GetRecommendationFeedbackByRecommendationID :one
SELECT id, recommendation_id, seller_account_id, rating, comment, created_at
FROM recommendation_feedback
WHERE seller_account_id = $1
  AND recommendation_id = $2
`

type GetRecommendationFeedbackByRecommendationIDParams struct {
	SellerAccountID  int64
	RecommendationID int64
}

func (q *Queries) GetRecommendationFeedbackByRecommendationID(ctx context.Context, arg GetRecommendationFeedbackByRecommendationIDParams) (RecommendationFeedback, error) {
	row := q.db.QueryRow(ctx, getRecommendationFeedbackByRecommendationID, arg.SellerAccountID, arg.RecommendationID)
	var i RecommendationFeedback
	err := row.Scan(
		&i.ID,
		&i.RecommendationID,
		&i.SellerAccountID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const listRecommendationFeedbackBySeller = `-- name: ListRecommendationFeedbackBySeller :many
SELECT id, recommendation_id, seller_account_id, rating, comment, created_at
FROM recommendation_feedback
WHERE seller_account_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
OFFSET $3
`

type ListRecommendationFeedbackBySellerParams struct {
	SellerAccountID int64
	Limit           int32
	Offset          int32
}

func (q *Queries) ListRecommendationFeedbackBySeller(ctx context.Context, arg ListRecommendationFeedbackBySellerParams) ([]RecommendationFeedback, error) {
	rows, err := q.db.Query(ctx, listRecommendationFeedbackBySeller, arg.SellerAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecommendationFeedback
	for rows.Next() {
		var i RecommendationFeedback
		if err := rows.Scan(
			&i.ID,
			&i.RecommendationID,
			&i.SellerAccountID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
