// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sales.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSalesBySellerAccountID = `-- name: CountSalesBySellerAccountID :one
SELECT COUNT(*)
FROM sales
WHERE seller_account_id = $1
`

func (q *Queries) CountSalesBySellerAccountID(ctx context.Context, sellerAccountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSalesBySellerAccountID, sellerAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listSalesBySellerAccountID = `-- name: ListSalesBySellerAccountID :many
SELECT id, seller_account_id, ozon_sale_id, ozon_order_id, posting_number, quantity, amount, currency_code, sale_date, raw_attributes, created_at, updated_at
FROM sales
WHERE seller_account_id = $1
ORDER BY id ASC
`

func (q *Queries) ListSalesBySellerAccountID(ctx context.Context, sellerAccountID int64) ([]Sale, error) {
	rows, err := q.db.Query(ctx, listSalesBySellerAccountID, sellerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sale
	for rows.Next() {
		var i Sale
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.OzonSaleID,
			&i.OzonOrderID,
			&i.PostingNumber,
			&i.Quantity,
			&i.Amount,
			&i.CurrencyCode,
			&i.SaleDate,
			&i.RawAttributes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSale = `-- name: UpsertSale :one
INSERT INTO sales (
    seller_account_id,
    ozon_sale_id,
    ozon_order_id,
    posting_number,
    quantity,
    amount,
    currency_code,
    sale_date,
    raw_attributes,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW()
)
ON CONFLICT (seller_account_id, ozon_sale_id)
DO UPDATE SET
    ozon_order_id = EXCLUDED.ozon_order_id,
    posting_number = EXCLUDED.posting_number,
    quantity = EXCLUDED.quantity,
    amount = EXCLUDED.amount,
    currency_code = EXCLUDED.currency_code,
    sale_date = EXCLUDED.sale_date,
    raw_attributes = EXCLUDED.raw_attributes,
    updated_at = NOW()
RETURNING id, seller_account_id, ozon_sale_id, ozon_order_id, posting_number, quantity, amount, currency_code, sale_date, raw_attributes, created_at, updated_at
`

type UpsertSaleParams struct {
	SellerAccountID int64
	OzonSaleID      string
	OzonOrderID     pgtype.Text
	PostingNumber   pgtype.Text
	Quantity        pgtype.Int4
	Amount          pgtype.Numeric
	CurrencyCode    pgtype.Text
	SaleDate        pgtype.Timestamptz
	RawAttributes   []byte
}

func (q *Queries) UpsertSale(ctx context.Context, arg UpsertSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, upsertSale,
		arg.SellerAccountID,
		arg.OzonSaleID,
		arg.OzonOrderID,
		arg.PostingNumber,
		arg.Quantity,
		arg.Amount,
		arg.CurrencyCode,
		arg.SaleDate,
		arg.RawAttributes,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.OzonSaleID,
		&i.OzonOrderID,
		&i.PostingNumber,
		&i.Quantity,
		&i.Amount,
		&i.CurrencyCode,
		&i.SaleDate,
		&i.RawAttributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
