// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seller_accounts.sql

package dbgen

import (
	"context"
)

const createSellerAccount = `-- name: CreateSellerAccount :one
INSERT INTO seller_accounts (
    user_id,
    name,
    status
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, name, status, created_at, updated_at
`

type CreateSellerAccountParams struct {
	UserID int64
	Name   string
	Status string
}

func (q *Queries) CreateSellerAccount(ctx context.Context, arg CreateSellerAccountParams) (SellerAccount, error) {
	row := q.db.QueryRow(ctx, createSellerAccount, arg.UserID, arg.Name, arg.Status)
	var i SellerAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSellerAccountByUserID = `-- name: GetSellerAccountByUserID :one
SELECT id, user_id, name, status, created_at, updated_at FROM seller_accounts
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetSellerAccountByUserID(ctx context.Context, userID int64) (SellerAccount, error) {
	row := q.db.QueryRow(ctx, getSellerAccountByUserID, userID)
	var i SellerAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
