// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stocks.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countStocksBySellerAccountID = `-- name: CountStocksBySellerAccountID :one
SELECT COUNT(*)
FROM stocks
WHERE seller_account_id = $1
`

func (q *Queries) CountStocksBySellerAccountID(ctx context.Context, sellerAccountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countStocksBySellerAccountID, sellerAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listStocksBySellerAccountID = `-- name: ListStocksBySellerAccountID :many
SELECT id, seller_account_id, product_external_id, warehouse_external_id, quantity_total, quantity_reserved, quantity_available, snapshot_at, raw_attributes, created_at, updated_at
FROM stocks
WHERE seller_account_id = $1
ORDER BY id ASC
`

func (q *Queries) ListStocksBySellerAccountID(ctx context.Context, sellerAccountID int64) ([]Stock, error) {
	rows, err := q.db.Query(ctx, listStocksBySellerAccountID, sellerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stock
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.ProductExternalID,
			&i.WarehouseExternalID,
			&i.QuantityTotal,
			&i.QuantityReserved,
			&i.QuantityAvailable,
			&i.SnapshotAt,
			&i.RawAttributes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStock = `-- name: UpsertStock :one
INSERT INTO stocks (
    seller_account_id,
    product_external_id,
    warehouse_external_id,
    quantity_total,
    quantity_reserved,
    quantity_available,
    snapshot_at,
    raw_attributes,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW()
)
ON CONFLICT (seller_account_id, product_external_id, warehouse_external_id)
DO UPDATE SET
    quantity_total = EXCLUDED.quantity_total,
    quantity_reserved = EXCLUDED.quantity_reserved,
    quantity_available = EXCLUDED.quantity_available,
    snapshot_at = EXCLUDED.snapshot_at,
    raw_attributes = EXCLUDED.raw_attributes,
    updated_at = NOW()
RETURNING id, seller_account_id, product_external_id, warehouse_external_id, quantity_total, quantity_reserved, quantity_available, snapshot_at, raw_attributes, created_at, updated_at
`

type UpsertStockParams struct {
	SellerAccountID     int64
	ProductExternalID   string
	WarehouseExternalID string
	QuantityTotal       pgtype.Int4
	QuantityReserved    pgtype.Int4
	QuantityAvailable   pgtype.Int4
	SnapshotAt          pgtype.Timestamptz
	RawAttributes       []byte
}

func (q *Queries) UpsertStock(ctx context.Context, arg UpsertStockParams) (Stock, error) {
	row := q.db.QueryRow(ctx, upsertStock,
		arg.SellerAccountID,
		arg.ProductExternalID,
		arg.WarehouseExternalID,
		arg.QuantityTotal,
		arg.QuantityReserved,
		arg.QuantityAvailable,
		arg.SnapshotAt,
		arg.RawAttributes,
	)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.ProductExternalID,
		&i.WarehouseExternalID,
		&i.QuantityTotal,
		&i.QuantityReserved,
		&i.QuantityAvailable,
		&i.SnapshotAt,
		&i.RawAttributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
