// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock_metrics.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCurrentStockProductSummariesBySellerAccountID = `-- name: ListCurrentStockProductSummariesBySellerAccountID :many
WITH latest_stock_per_warehouse AS (
    SELECT DISTINCT ON (st.product_external_id, st.warehouse_external_id)
        st.product_external_id,
        st.warehouse_external_id,
        st.quantity_total,
        st.quantity_reserved,
        st.quantity_available,
        st.snapshot_at,
        st.id
    FROM stocks st
    WHERE st.seller_account_id = $1
      AND st.product_external_id ~ '^[0-9]+$'
    ORDER BY
        st.product_external_id,
        st.warehouse_external_id,
        st.snapshot_at DESC NULLS LAST,
        st.id DESC
)
SELECT
    l.product_external_id::bigint AS ozon_product_id,
    p.offer_id,
    p.sku,
    p.name AS product_name,
    COUNT(*)::integer AS warehouse_count,
    COALESCE(SUM(l.quantity_total), 0)::integer AS total_stock,
    COALESCE(SUM(l.quantity_reserved), 0)::integer AS reserved_stock,
    COALESCE(SUM(l.quantity_available), 0)::integer AS available_stock,
    MAX(l.snapshot_at)::timestamptz AS snapshot_at
FROM latest_stock_per_warehouse l
LEFT JOIN products p
    ON p.seller_account_id = $1
   AND p.ozon_product_id = l.product_external_id::bigint
GROUP BY
    l.product_external_id::bigint,
    p.offer_id,
    p.sku,
    p.name
ORDER BY available_stock DESC, l.product_external_id::bigint ASC
`

type ListCurrentStockProductSummariesBySellerAccountIDRow struct {
	OzonProductID  int64
	OfferID        pgtype.Text
	Sku            pgtype.Int8
	ProductName    pgtype.Text
	WarehouseCount int32
	TotalStock     int32
	ReservedStock  int32
	AvailableStock int32
	SnapshotAt     pgtype.Timestamptz
}

func (q *Queries) ListCurrentStockProductSummariesBySellerAccountID(ctx context.Context, sellerAccountID int64) ([]ListCurrentStockProductSummariesBySellerAccountIDRow, error) {
	rows, err := q.db.Query(ctx, listCurrentStockProductSummariesBySellerAccountID, sellerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentStockProductSummariesBySellerAccountIDRow
	for rows.Next() {
		var i ListCurrentStockProductSummariesBySellerAccountIDRow
		if err := rows.Scan(
			&i.OzonProductID,
			&i.OfferID,
			&i.Sku,
			&i.ProductName,
			&i.WarehouseCount,
			&i.TotalStock,
			&i.ReservedStock,
			&i.AvailableStock,
			&i.SnapshotAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentStockWarehouseRowsBySellerAccountID = `-- name: ListCurrentStockWarehouseRowsBySellerAccountID :many
WITH latest_stock_per_warehouse AS (
    SELECT DISTINCT ON (st.product_external_id, st.warehouse_external_id)
        st.product_external_id,
        st.warehouse_external_id,
        st.quantity_total,
        st.quantity_reserved,
        st.quantity_available,
        st.snapshot_at,
        st.id
    FROM stocks st
    WHERE st.seller_account_id = $1
      AND st.product_external_id ~ '^[0-9]+$'
    ORDER BY
        st.product_external_id,
        st.warehouse_external_id,
        st.snapshot_at DESC NULLS LAST,
        st.id DESC
)
SELECT
    l.product_external_id::bigint AS ozon_product_id,
    l.warehouse_external_id,
    COALESCE(l.quantity_total, 0)::integer AS total_stock,
    COALESCE(l.quantity_reserved, 0)::integer AS reserved_stock,
    COALESCE(l.quantity_available, 0)::integer AS available_stock,
    l.snapshot_at
FROM latest_stock_per_warehouse l
ORDER BY l.product_external_id::bigint ASC, l.warehouse_external_id ASC
`

type ListCurrentStockWarehouseRowsBySellerAccountIDRow struct {
	OzonProductID       int64
	WarehouseExternalID string
	TotalStock          int32
	ReservedStock       int32
	AvailableStock      int32
	SnapshotAt          pgtype.Timestamptz
}

func (q *Queries) ListCurrentStockWarehouseRowsBySellerAccountID(ctx context.Context, sellerAccountID int64) ([]ListCurrentStockWarehouseRowsBySellerAccountIDRow, error) {
	rows, err := q.db.Query(ctx, listCurrentStockWarehouseRowsBySellerAccountID, sellerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentStockWarehouseRowsBySellerAccountIDRow
	for rows.Next() {
		var i ListCurrentStockWarehouseRowsBySellerAccountIDRow
		if err := rows.Scan(
			&i.OzonProductID,
			&i.WarehouseExternalID,
			&i.TotalStock,
			&i.ReservedStock,
			&i.AvailableStock,
			&i.SnapshotAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
