// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_cursors.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSyncCursorBySellerAccountDomainAndType = `-- name: GetSyncCursorBySellerAccountDomainAndType :one
SELECT id, seller_account_id, domain, cursor_type, cursor_value, updated_at
FROM sync_cursors
WHERE seller_account_id = $1
  AND domain = $2
  AND cursor_type = $3
LIMIT 1
`

type GetSyncCursorBySellerAccountDomainAndTypeParams struct {
	SellerAccountID int64
	Domain          string
	CursorType      string
}

func (q *Queries) GetSyncCursorBySellerAccountDomainAndType(ctx context.Context, arg GetSyncCursorBySellerAccountDomainAndTypeParams) (SyncCursor, error) {
	row := q.db.QueryRow(ctx, getSyncCursorBySellerAccountDomainAndType, arg.SellerAccountID, arg.Domain, arg.CursorType)
	var i SyncCursor
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.Domain,
		&i.CursorType,
		&i.CursorValue,
		&i.UpdatedAt,
	)
	return i, err
}

const listSyncCursorsBySellerAccountID = `-- name: ListSyncCursorsBySellerAccountID :many
SELECT id, seller_account_id, domain, cursor_type, cursor_value, updated_at
FROM sync_cursors
WHERE seller_account_id = $1
ORDER BY domain, cursor_type
`

func (q *Queries) ListSyncCursorsBySellerAccountID(ctx context.Context, sellerAccountID int64) ([]SyncCursor, error) {
	rows, err := q.db.Query(ctx, listSyncCursorsBySellerAccountID, sellerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncCursor
	for rows.Next() {
		var i SyncCursor
		if err := rows.Scan(
			&i.ID,
			&i.SellerAccountID,
			&i.Domain,
			&i.CursorType,
			&i.CursorValue,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSyncCursor = `-- name: UpsertSyncCursor :one
INSERT INTO sync_cursors (
    seller_account_id,
    domain,
    cursor_type,
    cursor_value,
    updated_at
) VALUES (
    $1, $2, $3, $4, NOW()
)
ON CONFLICT (seller_account_id, domain, cursor_type)
DO UPDATE SET
    cursor_value = EXCLUDED.cursor_value,
    updated_at = NOW()
RETURNING id, seller_account_id, domain, cursor_type, cursor_value, updated_at
`

type UpsertSyncCursorParams struct {
	SellerAccountID int64
	Domain          string
	CursorType      string
	CursorValue     pgtype.Text
}

func (q *Queries) UpsertSyncCursor(ctx context.Context, arg UpsertSyncCursorParams) (SyncCursor, error) {
	row := q.db.QueryRow(ctx, upsertSyncCursor,
		arg.SellerAccountID,
		arg.Domain,
		arg.CursorType,
		arg.CursorValue,
	)
	var i SyncCursor
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.Domain,
		&i.CursorType,
		&i.CursorValue,
		&i.UpdatedAt,
	)
	return i, err
}
