// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_jobs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSyncJob = `-- name: CreateSyncJob :one
INSERT INTO sync_jobs (
    seller_account_id,
    type,
    status,
    started_at,
    finished_at,
    error_message
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, seller_account_id, type, status, started_at, finished_at, error_message, created_at
`

type CreateSyncJobParams struct {
	SellerAccountID int64
	Type            string
	Status          string
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	ErrorMessage    pgtype.Text
}

func (q *Queries) CreateSyncJob(ctx context.Context, arg CreateSyncJobParams) (SyncJob, error) {
	row := q.db.QueryRow(ctx, createSyncJob,
		arg.SellerAccountID,
		arg.Type,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ErrorMessage,
	)
	var i SyncJob
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.Type,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSyncJobBySellerAccountIDAndType = `-- name: GetLatestSyncJobBySellerAccountIDAndType :one
SELECT id, seller_account_id, type, status, started_at, finished_at, error_message, created_at
FROM sync_jobs
WHERE seller_account_id = $1
  AND type = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestSyncJobBySellerAccountIDAndTypeParams struct {
	SellerAccountID int64
	Type            string
}

func (q *Queries) GetLatestSyncJobBySellerAccountIDAndType(ctx context.Context, arg GetLatestSyncJobBySellerAccountIDAndTypeParams) (SyncJob, error) {
	row := q.db.QueryRow(ctx, getLatestSyncJobBySellerAccountIDAndType, arg.SellerAccountID, arg.Type)
	var i SyncJob
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.Type,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const updateSyncJobToCompleted = `-- name: UpdateSyncJobToCompleted :one
UPDATE sync_jobs
SET
    status = 'completed',
    finished_at = NOW(),
    error_message = NULL
WHERE id = $1
RETURNING id, seller_account_id, type, status, started_at, finished_at, error_message, created_at
`

func (q *Queries) UpdateSyncJobToCompleted(ctx context.Context, id int64) (SyncJob, error) {
	row := q.db.QueryRow(ctx, updateSyncJobToCompleted, id)
	var i SyncJob
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.Type,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const updateSyncJobToFailed = `-- name: UpdateSyncJobToFailed :one
UPDATE sync_jobs
SET
    status = 'failed',
    finished_at = NOW(),
    error_message = $2
WHERE id = $1
RETURNING id, seller_account_id, type, status, started_at, finished_at, error_message, created_at
`

type UpdateSyncJobToFailedParams struct {
	ID           int64
	ErrorMessage pgtype.Text
}

func (q *Queries) UpdateSyncJobToFailed(ctx context.Context, arg UpdateSyncJobToFailedParams) (SyncJob, error) {
	row := q.db.QueryRow(ctx, updateSyncJobToFailed, arg.ID, arg.ErrorMessage)
	var i SyncJob
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.Type,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const updateSyncJobToRunning = `-- name: UpdateSyncJobToRunning :one
UPDATE sync_jobs
SET
    status = 'running',
    started_at = NOW()
WHERE id = $1
RETURNING id, seller_account_id, type, status, started_at, finished_at, error_message, created_at
`

func (q *Queries) UpdateSyncJobToRunning(ctx context.Context, id int64) (SyncJob, error) {
	row := q.db.QueryRow(ctx, updateSyncJobToRunning, id)
	var i SyncJob
	err := row.Scan(
		&i.ID,
		&i.SellerAccountID,
		&i.Type,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}
