global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "backend-api"
    static_configs:
      - targets:
          - "host.docker.internal:8081"

  - job_name: "backend-worker"
    static_configs:
      - targets:
          - "host.docker.internal:9091"