/** Общие UI-строки на русском */

export const ui = {
  loading: "Загрузка…",
  loadingEllipsis: (what: string) => `Загрузка: ${what}…`,
  refresh: "Обновить",
  refreshing: "Обновление…",
  save: "Сохранить",
  saving: "Сохранение…",
  cancel: "Отмена",
  close: "Закрыть",
  back: "Назад",
  next: "Далее",
  prev: "Назад",
  search: "Поиск",
  reset: "Сбросить",
  filters: "Фильтры",
  actions: "Действия",
  details: "Подробнее",
  expand: "Развернуть",
  collapse: "Свернуть",
  yes: "Да",
  no: "Нет",
  all: "Все",
  none: "—",
  unknown: "Неизвестно",
  unavailable: "Недоступно",
  error: "Ошибка",
  success: "Готово",

  email: "Email",
  password: "Пароль",
  login: "Вход",
  logout: "Выйти",
  signingOut: "Выход…",
  signingIn: "Вход…",
  register: "Регистрация",
  creatingAccount: "Создание аккаунта…",

  openMenu: "Открыть меню",
  closeMenu: "Закрыть меню",
  primaryNav: "Основная навигация",

  marketplaceAI: "Marketplace AI",
  mvp: "MVP",
  admin: "Админ",

  sellerAccount: "Аккаунт продавца",
  adminSupport: "Админ / Поддержка",

  noData: "Нет данных",
  requestFailed: "Запрос не выполнен",
  tryAgainLater: "Попробуйте позже",

  status: "Статус",
  title: "Заголовок",
  message: "Сообщение",
  date: "Дата",
  type: "Тип",
  group: "Группа",
  severity: "Важность",
  urgency: "Срочность",
  entity: "Сущность",
  product: "Товар",
  revenue: "Выручка",
  orders: "Заказы",
  stock: "Остаток",
  limit: "Лимит",
  offset: "Смещение",
} as const;

export const nav = {
  mvpHome: "Главная MVP",
  dashboard: "Дашборд",
  ozonIntegration: "Интеграция Ozon",
  syncStatus: "Статус синхронизации",
  criticalSkus: "Критические SKU",
  stocksReplenishment: "Остатки и пополнение",
  advertising: "Реклама",
  pricingConstraints: "Ценовые ограничения",
  alerts: "Алерты",
  recommendations: "Рекомендации",
  aiChat: "AI-чат",
  adminSupport: "Админ / Поддержка",
  sellerAccount: "Аккаунт продавца",
} as const;

export const sectionTitles: Record<string, string> = {
  "/app": nav.mvpHome,
  "/app/dashboard": nav.dashboard,
  "/app/integrations/ozon": nav.ozonIntegration,
  "/app/sync-status": nav.syncStatus,
  "/app/critical-skus": nav.criticalSkus,
  "/app/stocks-replenishment": nav.stocksReplenishment,
  "/app/advertising": nav.advertising,
  "/app/pricing-constraints": nav.pricingConstraints,
  "/app/alerts": nav.alerts,
  "/app/recommendations": nav.recommendations,
  "/app/chat": nav.aiChat,
  "/app/account": nav.sellerAccount,
  "/app/admin": nav.adminSupport,
};
